### ISSUE TITLE
Index text documents from local folder

### ISSUE THREAD

**Issue by benutzer1234** [dadoonet/fscrawler#113]
Hi,

I'm new to elastic search and fs river and also no computer science guy but try to run this for my research project. I'm trying to index all text files of a folder with the mapper-plugin and fs river. Despite looking at the documentation from both plugins and several other posts I am still not able to index the documents.  I will try to describe my problem as detailed as I can but let me know if I should provide more information.

I installed elasticsearch 1.3.1, with river-plugin 1.3.1 and mapper-plugin 2.3.2 on my ubuntu 14.04 . After starting elasticsearch and making sure the plugins have been loaded (loaded [mapper-attachments, marvel, river-fs]) I executed the follwing code in bash.
The raw text-files to index reside in ```~/Software/elasticsearch-1.3.1/test_data/test_documents ```.

```
host=localhost:9200
index=river_index


curl -X DELETE "${host}/${index}"

# set up index
curl -X PUT "${host}/${index}" -d '{
  "settings" : { "index" : { "number_of_shards" : 1, "number_of_replicas" : 0 }}
}'
  
# set  mapping properties
curl -X PUT "${host}/${index}/attachment/_mapping" -d '{
  "attachment" : {
    "properties" : {
      "text" : {
        "type" : "attachment",
        "fields" : {
          "title" : { "store" : "yes" },
          "text" : { "term_vector":"with_positions_offsets", "store":"yes" }
        }
      }
    }
  }
}'

# create a river
curl -XPUT 'localhost:9200/_river/documentsriver/_meta' -d '{
   "type": "fs",
   "fs": {
     "url": "~/Software/elasticsearch-1.3.1/test_data/test_documents",
     "update_rate": 10000,
     "includes": [ "*.txt" ]
   },
   "index": {
     "index": "river_index",
     "type": "attachment",
     "bulk_size": 3
   }
}'


# count number of documents
curl -XGET "${host}/${index}/_count"
```
Checking the number of documents after setting up rivers says the index is empty.

The infomation from elasticsearch reveals there is an error while indexing:
```
[2015-06-25 13:41:49,552][INFO ][cluster.metadata         ] [Hamilton Slade] [river_index] deleting index
[2015-06-25 13:41:49,630][INFO ][cluster.metadata         ] [Hamilton Slade] [river_index] creating index, cause [api], shards [1]/[0], mappings []
[2015-06-25 13:41:49,731][INFO ][cluster.metadata         ] [Hamilton Slade] [river_index] create_mapping [attachment]
[2015-06-25 13:41:50,419][INFO ][cluster.metadata         ] [Hamilton Slade] [_river] update_mapping [documentsriver] (dynamic)
[2015-06-25 13:41:50,428][INFO ][fr.pilato.elasticsearch.river.fs.river.FsRiver] [Hamilton Slade] [fs][documentsriver] Starting fs river scanning
[2015-06-25 13:41:50,471][INFO ][fr.pilato.elasticsearch.river.fs.river.FsRiver] [Hamilton Slade] [fs][documentsriver] creating fs river [documentsriver] for [~/Software/elasticsearch-1.3.1/test_data/test_documents] every [1.6m]
[2015-06-25 13:41:50,473][WARN ][fr.pilato.elasticsearch.river.fs.river.FsRiver] [Hamilton Slade] [fs][documentsriver] Error while indexing content from ~/Software/elasticsearch-1.3.1/test_data/test_documents
[2015-06-25 13:41:50,474][INFO ][cluster.metadata         ] [Hamilton Slade] [_river] update_mapping [documentsriver] (dynamic)
```

Please let me know if you know what to do. Thank you.

**Comment by dadoonet** [comment]
Have a look at this section https://github.com/dadoonet/fsriver#debug-mode
So add more debug level. Can't tell from those logs.

**Comment by benutzer1234** [comment]
After adding
 ```# TRACE fsriver```
  ```fr.pilato.elasticsearch.river.fs: TRACE```
to the logging.yml and then executing the code above I got this warning:

```
[2015-06-25 14:18:50,002][INFO ][node                     ] [Abraham Cornelius] version[1.5.2], pid[23159], build[62ff986/2015-04-27T09:21:06Z]
[2015-06-25 14:18:50,002][INFO ][node                     ] [Abraham Cornelius] initializing ...
[2015-06-25 14:18:50,035][INFO ][plugins                  ] [Abraham Cornelius] loaded [mapper-attachments, marvel], sites [marvel]
[2015-06-25 14:18:52,449][INFO ][marvel.agent             ] [Abraham Cornelius] collecting disabled by settings
[2015-06-25 14:18:52,466][INFO ][node                     ] [Abraham Cornelius] initialized
[2015-06-25 14:18:52,466][INFO ][node                     ] [Abraham Cornelius] starting ...
[2015-06-25 14:18:52,545][INFO ][transport                ] [Abraham Cornelius] bound_address {inet[/0:0:0:0:0:0:0:0:9300]}, publish_address {inet[/192.168.0.14:9300]}
[2015-06-25 14:18:52,563][INFO ][discovery                ] [Abraham Cornelius] Felix_cluster/9jmwArvEQziRt1kmfUarVQ
[2015-06-25 14:18:56,347][INFO ][cluster.service          ] [Abraham Cornelius] new_master [Abraham Cornelius][9jmwArvEQziRt1kmfUarVQ][Magda][inet[/192.168.0.14:9300]], reason: zen-disco-join (elected_as_master)
[2015-06-25 14:18:56,407][INFO ][http                     ] [Abraham Cornelius] bound_address {inet[/0:0:0:0:0:0:0:0:9200]}, publish_address {inet[/192.168.0.14:9200]}
[2015-06-25 14:18:56,407][INFO ][node                     ] [Abraham Cornelius] started
[2015-06-25 14:18:57,100][INFO ][gateway                  ] [Abraham Cornelius] recovered [19] indices into cluster_state
[2015-06-25 14:21:06,943][INFO ][cluster.metadata         ] [Abraham Cornelius] [river_index] creating index, cause [api], templates [], shards [1]/[0], mappings []
[2015-06-25 14:21:07,104][INFO ][cluster.metadata         ] [Abraham Cornelius] [river_index] create_mapping [attachment]
[2015-06-25 14:21:07,232][INFO ][cluster.metadata         ] [Abraham Cornelius] [_river] update_mapping [documentsriver] (dynamic)
[2015-06-25 14:21:08,276][WARN ][river                    ] [Abraham Cornelius] failed to create river [fs][documentsriver]
org.elasticsearch.common.settings.NoClassSettingsException: Failed to load class with value [fs]
	at org.elasticsearch.river.RiverModule.loadTypeModule(RiverModule.java:87)
	at org.elasticsearch.river.RiverModule.spawnModules(RiverModule.java:58)
	at org.elasticsearch.common.inject.ModulesBuilder.add(ModulesBuilder.java:44)
	at org.elasticsearch.river.RiversService.createRiver(RiversService.java:137)
	at org.elasticsearch.river.RiversService$ApplyRivers$2.onResponse(RiversService.java:273)
	at org.elasticsearch.river.RiversService$ApplyRivers$2.onResponse(RiversService.java:267)
	at org.elasticsearch.action.support.TransportAction$ThreadedActionListener$1.run(TransportAction.java:113)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: fs
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.elasticsearch.river.RiverModule.loadTypeModule(RiverModule.java:73)
	... 9 more


```

**Comment by dadoonet** [comment]
Did you restart Elasticsearch ?

**Comment by dadoonet** [comment]
Yes you did but fsriver is not installed

**Comment by dadoonet** [comment]
No news on that. And fscrawler 2.0.0 has been released in the meantime.
