### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/JsonSerializer

### ISSUE THREAD

**Issue by slowfranklin** [dadoonet/fscrawler#1157]
**Describe the bug**

I'm having problems with using fscrawler on Fedora 33. With the stock Java I'm getting class errors:

```
./fscrawler-es7-2.7-SNAPSHOT/bin/fscrawler test
Error: LinkageError occurred while loading main class fr.pilato.elasticsearch.crawler.fs.cli.FsCrawler
        java.lang.UnsupportedClassVersionError: fr/pilato/elasticsearch/crawler/fs/cli/FsCrawler has been compiled by a more recent version of the Java Runtime (class file version 58.0), this version of the Java Runtime only recognizes class file versions up to 55.0
```

This is with a snapshot downloaded just today.

Java version is:

```
java -version
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment 18.9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.11+9, mixed mode, sharing)
```

I dowloaded openjdk 16:

```
$  $JAVA_HOME/bin/java -version
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment (build 16.0.1+9-24)
OpenJDK 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)
```

... but when using that I get a the error in the subject:

```
./fscrawler-es7-2.7-SNAPSHOT/bin/fscrawler test
...
Exception in thread "main" java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/JsonSerializer
        at fr.pilato.elasticsearch.crawler.fs.settings.FsSettingsParser.toYaml(FsSettingsParser.java:32)
        at fr.pilato.elasticsearch.crawler.fs.settings.FsSettingsFileHandler.write(FsSettingsFileHandler.java:81)
        at fr.pilato.elasticsearch.crawler.fs.cli.FsCrawlerCli.main(FsCrawlerCli.java:247)
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.JsonSerializer
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
```

How is this supposed to be work?

Thanks!

**Comment by dadoonet** [comment]
I never tested yet with java16. Could you try with java15?

**Comment by dadoonet** [comment]
Could you try with Java 15?

**Comment by slowfranklin** [comment]
Well, I guess I could, but to me it seems more of a problem that an external Java libary is being used here (jackson) and while that is install generallly in the system, the specific backend (json) being used is missing from the package on Fedora. Is this possible?

This is the list of installed jackson packages:
```
rpm -qa | grep jackson
jackson-core-2.11.4-1.fc33.noarch
jackson-dataformat-yaml-2.9.8-5.fc33.noarch
jackson-annotations-2.11.4-1.fc33.noarch
jackson-databind-2.11.4-1.fc33.noarch
jackson-jaxrs-providers-2.11.4-1.fc33.noarch
jackson-module-jaxb-annotations-2.11.4-1.fc33.noarch
jackson-jaxrs-json-provider-2.11.4-1.fc33.noarch
jackson-databind-javadoc-2.11.4-1.fc33.noarch
```

I've now switches to the Fedora provided Java 16 instead of using a manually downloaded one, didn't know it existed. Just had to install openjdk-latest and configure to use it via alternatives --config java.

I don't thing there's a Java 15 package, but I'll check.

**Comment by dadoonet** [comment]
Thanks! Sounds like there's an error in the packaging as there's an older Jackson lib here.

i will check as soon as I have some free time.

**Comment by slowfranklin** [comment]
Just noticed I was using fscrawler-es7-2.7-20210426.091911-176.zip. Trying again with fscrawler-es7-2.7-20210505.084329-178.zip
