### ISSUE TITLE
Creation date is null when using SSH crawler

### ISSUE THREAD

**Issue by JacksonPhoong** [dadoonet/fscrawler#1216]
**Describe the bug**

I am trying to index files to use in Elastic Workplace Search. When using SSH settings to crawl files, I encountered NullPointerException due to the creation date being null. 

I had a look at the source code and in **FileAbstractorSSH** line 54, the creation date is defaulted to null and this is causing the issue when formatting date in **WorkplaceSearchClientUtil** line 153. 

**Job Settings**

```yml
---
name: "job_name"
fs:
  url: "path to dir"
  update_rate: "15m"
  excludes:
  - "*/~*"
  json_support: false
  filename_as_id: false
  add_filesize: true
  remove_deleted: true
  add_as_inner_object: false
  store_source: false
  index_content: true
  attributes_support: false
  raw_metadata: false
  xml_support: false
  index_folders: true
  lang_detect: false
  continue_on_error: false
  ocr:
    language: "eng"
    enabled: true
    pdf_strategy: "ocr_and_text"
  follow_symlinks: false
server:
  hostname: "myhostname.domain.com"
  port: 22
  username: "user"
  password: "password"
  protocol: "ssh"
elasticsearch:
  username: "elastic"
  password: "password"  
  nodes:
  - cloud_id: "elastic cloud id"
  bulk_size: 100
  flush_interval: "5s"
  byte_size: "10mb"
  ssl_verification: true
workplace_search:
  access_token: "access token"
  key: "source identifier"
  server: "elastic workplace search url"
```

**Logs**

```
11:27:36,129 WARN  [f.p.e.c.f.FsParserAbstract] Full stacktrace
java.lang.NullPointerException: null
	at java.util.Calendar.setTime(Calendar.java:1801) ~[?:?]
	at java.text.SimpleDateFormat.format(SimpleDateFormat.java:975) ~[?:?]
	at java.text.SimpleDateFormat.format(SimpleDateFormat.java:968) ~[?:?]
	at java.text.DateFormat.format(DateFormat.java:375) ~[?:?]
	at fr.pilato.elasticsearch.crawler.fs.client.WorkplaceSearchClientUtil.toRFC3339(WorkplaceSearchClientUtil.java:153) ~[fscrawler-elasticsearch-client-base-2.7-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.client.WorkplaceSearchClientUtil.docToJson(WorkplaceSearchClientUtil.java:186) ~[fscrawler-elasticsearch-client-base-2.7-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.client.v7.WorkplaceSearchClientV7.index(WorkplaceSearchClientV7.java:157) ~[fscrawler-elasticsearch-client-v7-2.7-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.service.FsCrawlerDocumentServiceWorkplaceSearchImpl.index(FsCrawlerDocumentServiceWorkplaceSearchImpl.java:74) ~[fscrawler-core-2.7-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.FsParserAbstract.indexFile(FsParserAbstract.java:441) ~[fscrawler-core-2.7-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.FsParserAbstract.addFilesRecursively(FsParserAbstract.java:274) ~[fscrawler-core-2.7-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.FsParserAbstract.addFilesRecursively(FsParserAbstract.java:298) ~[fscrawler-core-2.7-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.FsParserAbstract.addFilesRecursively(FsParserAbstract.java:298) ~[fscrawler-core-2.7-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.FsParserAbstract.run(FsParserAbstract.java:153) [fscrawler-core-2.7-SNAPSHOT.jar:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
```

**Expected behavior**

No exceptions and files are crawled successfully

**Versions:**
 - OS: Windows
 - Version fscrawler-es7-2.7-20210802.185816-223

**Attachment**

None

**Comment by dadoonet** [comment]
I see. Thanks for reporting!

i never tested ssh input with workplace search output 😉
