### ISSUE TITLE
 Got a hard failure when executing the bulk request java.net.SocketTimeoutException: 30,000 milliseconds timeout 

### ISSUE THREAD

**Issue by sarce666** [dadoonet/fscrawler#1375]
hello 

i m using fscrawler 2.8
on debian
it index data to elastic cloud 
here is my _settings :

name: "a-next-projects"
fs:
  url: "/home/data/projects"
  update_rate: "15m"
  excludes:
  - "*/~*"
  json_support: false
  filename_as_id: false
  add_filesize: true
  remove_deleted: true
  add_as_inner_object: false
  store_source: false
  index_content: true
  attributes_support: false
  raw_metadata: true
  xml_support: false
  index_folders: true
  lang_detect: false
  continue_on_error: true
  ocr:
    language: "eng"
    enabled: true
    pdf_strategy: "auto"
  follow_symlinks: false
elasticsearch:
  bulk_size: 2
  pipeline: "nlp-pipeline"
  username: "****"
  password: "****"
  nodes:
  - cloud_id: "****"

and i got the error : 

08:38:49,588 WARN  [f.p.e.c.f.c.v.ElasticsearchClientV7] Got a hard failure when executing the bulk request
java.net.SocketTimeoutException: 30,000 milliseconds timeout on connection http-outgoing-8 [ACTIVE]
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.timeout(HttpAsyncRequestExecutor.java:387) [httpcore-nio-4.4.14.jar:4.4.14]
	at org.apache.http.impl.nio.client.InternalIODispatch.onTimeout(InternalIODispatch.java:92) [httpasyncclient-4.1.4.jar:4.1.4]
	at org.apache.http.impl.nio.client.InternalIODispatch.onTimeout(InternalIODispatch.java:39) [httpasyncclient-4.1.4.jar:4.1.4]
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.timeout(AbstractIODispatch.java:175) [httpcore-nio-4.4.14.jar:4.4.14]
	at org.apache.http.impl.nio.reactor.BaseIOReactor.sessionTimedOut(BaseIOReactor.java:261) [httpcore-nio-4.4.14.jar:4.4.14]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.timeoutCheck(AbstractIOReactor.java:502) [httpcore-nio-4.4.14.jar:4.4.14]
	at org.apache.http.impl.nio.reactor.BaseIOReactor.validate(BaseIOReactor.java:211) [httpcore-nio-4.4.14.jar:4.4.14]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:280) [httpcore-nio-4.4.14.jar:4.4.14]
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104) [httpcore-nio-4.4.14.jar:4.4.14]
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591) [httpcore-nio-4.4.14.jar:4.4.14]
	at java.lang.Thread.run(Thread.java:829) [?:?]

thanks so much for your help

**Comment by dadoonet** [comment]
Hi @sarce666 


Is this happening everytime you start FSCrawler of sometime?

**Comment by sarce666** [comment]
hello 

yes every time , with different folder , different index

**Comment by dadoonet** [comment]
So, just to be clear: no document at all is indexed, right?

Could you share please the full logs when running your job again using the `--debug --restart` options?

Please format the logs with `<>` icon as it will be easier to read them.

Thanks!

**Comment by sarce666** [comment]
hello 
no no, some documents are indexed , but some not 
i did the index with --trace --restart

and here is what i get. :
09:35:04,353 DEBUG [f.p.e.c.f.s.FsCrawlerDocumentServiceElasticsearchImpl] Indexing a-next-projects/a2fccfb918e39c2864edaf68bfb0a777?pipeline=nlp-pipeline
09:35:33,893 WARN  [f.p.e.c.f.c.v.ElasticsearchClientV7] Got a hard failure when executing the bulk request
java.net.SocketTimeoutException: 30,000 milliseconds timeout on connection http-outgoing-110 [ACTIVE]
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.timeout(HttpAsyncRequestExecutor.java:387) [httpcore-nio-4.4.14.jar:4.4.14]
	at org.apache.http.impl.nio.client.InternalIODispatch.onTimeout(InternalIODispatch.java:92) [httpasyncclient-4.1.4.jar:4.1.4]
	at org.apache.http.impl.nio.client.InternalIODispatch.onTimeout(InternalIODispatch.java:39) [httpasyncclient-4.1.4.jar:4.1.4]
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.timeout(AbstractIODispatch.java:175) [httpcore-nio-4.4.14.jar:4.4.14]
	at org.apache.http.impl.nio.reactor.BaseIOReactor.sessionTimedOut(BaseIOReactor.java:261) [httpcore-nio-4.4.14.jar:4.4.14]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.timeoutCheck(AbstractIOReactor.java:502) [httpcore-nio-4.4.14.jar:4.4.14]
	at org.apache.http.impl.nio.reactor.BaseIOReactor.validate(BaseIOReactor.java:211) [httpcore-nio-4.4.14.jar:4.4.14]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:280) [httpcore-nio-4.4.14.jar:4.4.14]
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104) [httpcore-nio-4.4.14.jar:4.4.14]
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591) [httpcore-nio-4.4.14.jar:4.4.14]
	at java.lang.Thread.run(Thread.java:829) [?:?]
09:35:33,903 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] computeVirtualPathName(/home/data/projects, /home/data/projects/Symmetry/Technical_Intel_Forensics-documents/HackingTeam/price_scheme_2015q3.pdf) = /Symmetry/Technical_Intel_Forensics-documents/HackingTeam/price_scheme_2015q3.pdf

**Comment by sarce666** [comment]
on this exemple  : 

```
09:35:04,353 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] computeVirtualPathName(/home/data/projects, /home/data/projects/Symmetry/Technical_Intel_Forensics-documents/HackingTeam/hackback.pdf) = /Symmetry/Technical_Intel_Forensics-documents/HackingTeam/hackback.pdf
09:35:04,353 DEBUG [f.p.e.c.f.s.FsCrawlerDocumentServiceElasticsearchImpl] Indexing a-next-projects/a2fccfb918e39c2864edaf68bfb0a777?pipeline=nlp-pipeline
09:35:33,893 WARN  [f.p.e.c.f.c.v.ElasticsearchClientV7] Got a hard failure when executing the bulk request
java.net.SocketTimeoutException: 30,000 milliseconds timeout on connection http-outgoing-110 [ACTIVE]
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.timeout(HttpAsyncRequestExecutor.java:387) [httpcore-nio-4.4.14.jar:4.4.14]
	at org.apache.http.impl.nio.client.InternalIODispatch.onTimeout(InternalIODispatch.java:92) [httpasyncclient-4.1.4.jar:4.1.4]
	at org.apache.http.impl.nio.client.InternalIODispatch.onTimeout(InternalIODispatch.java:39) [httpasyncclient-4.1.4.jar:4.1.4]
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.timeout(AbstractIODispatch.java:175) [httpcore-nio-4.4.14.jar:4.4.14]
	at org.apache.http.impl.nio.reactor.BaseIOReactor.sessionTimedOut(BaseIOReactor.java:261) [httpcore-nio-4.4.14.jar:4.4.14]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.timeoutCheck(AbstractIOReactor.java:502) [httpcore-nio-4.4.14.jar:4.4.14]
	at org.apache.http.impl.nio.reactor.BaseIOReactor.validate(BaseIOReactor.java:211) [httpcore-nio-4.4.14.jar:4.4.14]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:280) [httpcore-nio-4.4.14.jar:4.4.14]
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104) [httpcore-nio-4.4.14.jar:4.4.14]
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591) [httpcore-nio-4.4.14.jar:4.4.14]
	at java.lang.Thread.run(Thread.java:829) [?:?]

```

the file hackback.pdf is not indexed

**Comment by dadoonet** [comment]
Could you share the full logs please?

**Comment by dadoonet** [comment]
How big is `hackback.pdf` file?

**Comment by dadoonet** [comment]
My guess is that the nlp-pipeline takes too long to be processed and that's why we are seeing this error here.
