### ISSUE TITLE
timeout when indexing large folders 

### ISSUE THREAD

**Issue by jackpenman123** [dadoonet/fscrawler#1429]
**Describe the bug**

when indexing a folder with over a million files in it we appear to be getting a timeout error java.lang.RuntimeException: Request execution cancelled

Is there anyway we can get around this as currently the crawler just attempts to crawl the folder then just hits this exception everytime

additionally we have ran large folders with over a million results previously, this is the first time we have seen this error
**Job Settings**

```yml
---
name: "XXXX"
fs:
  url: "XXXXX"
  update_rate: "5m"
  json_support: false
  filename_as_id: false
  add_filesize: true
  remove_deleted: true
  add_as_inner_object: false
  store_source: false
  index_content: true
  indexed_chars: "1"
  attributes_support: true
  raw_metadata: true
  xml_support: false
  index_folders: true
  lang_detect: false
  continueOnError: true
  ocr:
    language: "eng"
    enabled: true
    pdf_strategy: "ocr_and_text"
  follow_symlinks: true
elasticsearch:
  nodes:
  - url: "XXXXX"
  index: "XXXX"
  bulk_size: 10000
  flush_interval: "5s"
  byte_size: "10mb"
  ssl_verification: false
  pipeline: "XXXX"
  username: "XXXX" 
  password: "XXXXX"

```

**Logs**

```
Request execution cancelled

03:50:16,056 WARN  [f.p.e.c.f.FsParserAbstract] Full stacktrace

java.lang.RuntimeException: Request execution cancelled

          at org.elasticsearch.client.RestClient.extractAndWrapCause(RestClient.java:904) ~[elasticsearch-rest-client-7.16.2.jar:7.16.2]

          at org.elasticsearch.client.RestClient.performRequest(RestClient.java:288) ~[elasticsearch-rest-client-7.16.2.jar:7.16.2]

          at org.elasticsearch.client.RestClient.performRequest(RestClient.java:291) ~[elasticsearch-rest-client-7.16.2.jar:7.16.2]

          at org.elasticsearch.client.RestClient.performRequest(RestClient.java:291) ~[elasticsearch-rest-client-7.16.2.jar:7.16.2]

          at org.elasticsearch.client.RestClient.performRequest(RestClient.java:291) ~[elasticsearch-rest-client-7.16.2.jar:7.16.2]

          at org.elasticsearch.client.RestClient.performRequest(RestClient.java:291) ~[elasticsearch-rest-client-7.16.2.jar:7.16.2]

          at org.elasticsearch.client.RestClient.performRequest(RestClient.java:291) ~[elasticsearch-rest-client-7.16.2.jar:7.16.2]

          at org.elasticsearch.client.RestClient.performRequest(RestClient.java:291) ~[elasticsearch-rest-client-7.16.2.jar:7.16.2]

          at org.elasticsearch.client.RestClient.performRequest(RestClient.java:276) ~[elasticsearch-rest-client-7.16.2.jar:7.16.2]

          at org.elasticsearch.client.RestHighLevelClient.performClientRequest(RestHighLevelClient.java:2699) ~[elasticsearch-rest-high-level-client-7.16.2.jar:7.16.2]

          at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:2171) ~[elasticsearch-rest-high-level-client-7.16.2.jar:7.16.2]

          at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:2137) ~[elasticsearch-rest-high-level-client-7.16.2.jar:7.16.2]

          at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:2105) ~[elasticsearch-rest-high-level-client-7.16.2.jar:7.16.2]

          at org.elasticsearch.client.RestHighLevelClient.search(RestHighLevelClient.java:1367) ~[elasticsearch-rest-high-level-client-7.16.2.jar:7.16.2]

          at fr.pilato.elasticsearch.crawler.fs.client.v7.ElasticsearchClientV7.search(ElasticsearchClientV7.java:518) ~[fscrawler-elasticsearch-client-v7-2.10-SNAPSHOT.jar:?]

          at fr.pilato.elasticsearch.crawler.fs.service.FsCrawlerManagementServiceElasticsearchImpl.getFileDirectory(FsCrawlerManagementServiceElasticsearchImpl.java:87) ~[fscrawler-core-2.10-SNAPSHOT.jar:?]

          at fr.pilato.elasticsearch.crawler.fs.FsParserAbstract.getFileDirectory(FsParserAbstract.java:374) ~[fscrawler-core-2.10-SNAPSHOT.jar:?]

          at fr.pilato.elasticsearch.crawler.fs.FsParserAbstract.addFilesRecursively(FsParserAbstract.java:334) ~[fscrawler-core-2.10-SNAPSHOT.jar:?]

          at fr.pilato.elasticsearch.crawler.fs.FsParserAbstract.run(FsParserAbstract.java:161) [fscrawler-core-2.10-SNAPSHOT.jar:?]

          at java.lang.Thread.run(Thread.java:832) [?:?]

          Suppressed: java.lang.RuntimeException: Request execution cancelled

                   at org.elasticsearch.client.RestClient.extractAndWrapCause(RestClient.java:904) ~[elasticsearch-rest-client-7.16.2.jar:7.16.2]

                   at org.elasticsearch.client.RestClient.performRequest(RestClient.java:288) ~[elasticsearch-rest-client-7.16.2.jar:7.16.2]

                   at org.elasticsearch.client.RestClient.performRequest(RestClient.java:291) ~[elasticsearch-rest-client-7.16.2.jar:7.16.2]

                   at org.elasticsearch.client.RestClient.performRequest(RestClient.java:291) ~[elasticsearch-rest-client-7.16.2.jar:7.16.2]

                   at org.elasticsearch.client.RestClient.performRequest(RestClient.java:291) ~[elasticsearch-rest-client-7.16.2.jar:7.16.2]

                   at org.elasticsearch.client.RestClient.performRequest(RestClient.java:291) ~[elasticsearch-rest-client-7.16.2.jar:7.16.2]

                   at org.elasticsearch.client.RestClient.performRequest(RestClient.java:291) ~[elasticsearch-rest-client-7.16.2.jar:7.16.2]

                   at org.elasticsearch.client.RestClient.performRequest(RestClient.java:276) ~[elasticsearch-rest-client-7.16.2.jar:7.16.2]

                   at org.elasticsearch.client.RestHighLevelClient.performClientRequest(RestHighLevelClient.java:2699) ~[elasticsearch-rest-high-level-client-7.16.2.jar:7.16.2]

                   at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:2171) ~[elasticsearch-rest-high-level-client-7.16.2.jar:7.16.2]

                   at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:2137) ~[elasticsearch-rest-high-level-client-7.16.2.jar:7.16.2]

                   at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:2105) ~[elasticsearch-rest-high-level-client-7.16.2.jar:7.16.2]

                   at org.elasticsearch.client.RestHighLevelClient.search(RestHighLevelClient.java:1367) ~[elasticsearch-rest-high-level-client-7.16.2.jar:7.16.2]

                   at fr.pilato.elasticsearch.crawler.fs.client.v7.ElasticsearchClientV7.search(ElasticsearchClientV7.java:518) ~[fscrawler-elasticsearch-client-v7-2.10-SNAPSHOT.jar:?]

                   at fr.pilato.elasticsearch.crawler.fs.service.FsCrawlerManagementServiceElasticsearchImpl.getFileDirectory(FsCrawlerManagementServiceElasticsearchImpl.java:87) ~[fscrawler-core-2.10-SNAPSHOT.jar:?]

                   at fr.pilato.elasticsearch.crawler.fs.FsParserAbstract.getFileDirectory(FsParserAbstract.java:374) ~[fscrawler-core-2.10-SNAPSHOT.jar:?]

                   at fr.pilato.elasticsearch.crawler.fs.FsParserAbstract.addFilesRecursively(FsParserAbstract.java:334) ~[fscrawler-core-2.10-SNAPSHOT.jar:?]

                   at fr.pilato.elasticsearch.crawler.fs.FsParserAbstract.run(FsParserAbstract.java:161) [fscrawler-core-2.10-SNAPSHOT.jar:?]

                   at java.lang.Thread.run(Thread.java:832) [?:?]

                   Suppressed: java.lang.RuntimeException: Request execution cancelled

                             at org.elasticsearch.client.RestClient.extractAndWrapCause(RestClient.java:904) ~[elasticsearch-rest-client-7.16.2.jar:7.16.2]

                             at org.elasticsearch.client.RestClient.performRequest(RestClient.java:288) ~[elasticsearch-rest-client-7.16.2.jar:7.16.2]

                             at org.elasticsearch.client.RestClient.performRequest(RestClient.java:291) ~[elasticsearch-rest-client-7.16.2.jar:7.16.2]

                             at org.elasticsearch.client.RestClient.performRequest(RestClient.java:291) ~[elasticsearch-rest-client-7.16.2.jar:7.16.2]

                             at org.elasticsearch.client.RestClient.performRequest(RestClient.java:291) ~[elasticsearch-rest-client-7.16.2.jar:7.16.2]

                             at org.elasticsearch.client.RestClient.performRequest(RestClient.java:291) ~[elasticsearch-rest-client-7.16.2.jar:7.16.2]

                             at org.elasticsearch.client.RestClient.performRequest(RestClient.java:276) ~[elasticsearch-rest-client-7.16.2.jar:7.16.2]

                             at org.elasticsearch.client.RestHighLevelClient.performClientRequest(RestHighLevelClient.java:2699) ~[elasticsearch-rest-high-level-client-7.16.2.jar:7.16.2]

                             at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:2171) ~[elasticsearch-rest-high-level-client-7.16.2.jar:7.16.2]

                             at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:2137) ~[elasticsearch-rest-high-level-client-7.16.2.jar:7.16.2]

                             at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:2105) ~[elasticsearch-rest-high-level-client-7.16.2.jar:7.16.2]

                             at org.elasticsearch.client.RestHighLevelClient.search(RestHighLevelClient.java:1367) ~[elasticsearch-rest-high-level-client-7.16.2.jar:7.16.2]

                             at fr.pilato.elasticsearch.crawler.fs.client.v7.ElasticsearchClientV7.search(ElasticsearchClientV7.java:518) ~[fscrawler-elasticsearch-client-v7-2.10-SNAPSHOT.jar:?]

                             at fr.pilato.elasticsearch.crawler.fs.service.FsCrawlerManagementServiceElasticsearchImpl.getFileDirectory(FsCrawlerManagementServiceElasticsearchImpl.java:87) ~[fscrawler-core-2.10-SNAPSHOT.jar:?]

                             at fr.pilato.elasticsearch.crawler.fs.FsParserAbstract.getFileDirectory(FsParserAbstract.java:374) ~[fscrawler-core-2.10-SNAPSHOT.jar:?]

                             at fr.pilato.elasticsearch.crawler.fs.FsParserAbstract.addFilesRecursively(FsParserAbstract.java:334) ~[fscrawler-core-2.10-SNAPSHOT.jar:?]

                             at fr.pilato.elasticsearch.crawler.fs.FsParserAbstract.run(FsParserAbstract.java:161) [fscrawler-core-2.10-SNAPSHOT.jar:?]

                             at java.lang.Thread.run(Thread.java:832) [?:?]

                             Suppressed: java.lang.RuntimeException: Request execution cancelled

                                      at org.elasticsearch.client.RestClient.extractAndWrapCause(RestClient.java:904) ~[elasticsearch-rest-client-7.16.2.jar:7.16.2]

                                      at org.elasticsearch.client.RestClient.performRequest(RestClient.java:288) ~[elasticsearch-rest-client-7.16.2.jar:7.16.2]

                                      at org.elasticsearch.client.RestClient.performRequest(RestClient.java:291) ~[elasticsearch-rest-client-7.16.2.jar:7.16.2]

                                      at org.elasticsearch.client.RestClient.performRequest(RestClient.java:291) ~[elasticsearch-rest-client-7.16.2.jar:7.16.2]

                                      at org.elasticsearch.client.RestClient.performRequest(RestClient.java:291) ~[elasticsearch-rest-client-7.16.2.jar:7.16.2]

                                      at org.elasticsearch.client.RestClient.performRequest(RestClient.java:276) ~[elasticsearch-rest-client-7.16.2.jar:7.16.2]

                                      at org.elasticsearch.client.RestHighLevelClient.performClientRequest(RestHighLevelClient.java:2699) ~[elasticsearch-rest-high-level-client-7.16.2.jar:7.16.2]

                                      at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:2171) ~[elasticsearch-rest-high-level-client-7.16.2.jar:7.16.2]

                                      at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:2137) ~[elasticsearch-rest-high-level-client-7.16.2.jar:7.16.2]

                                      at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:2105) ~[elasticsearch-rest-high-level-client-7.16.2.jar:7.16.2]

                                      at org.elasticsearch.client.RestHighLevelClient.search(RestHighLevelClient.java:1367) ~[elasticsearch-rest-high-level-client-7.16.2.jar:7.16.2]

                                      at fr.pilato.elasticsearch.crawler.fs.client.v7.ElasticsearchClientV7.search(ElasticsearchClientV7.java:518) ~[fscrawler-elasticsearch-client-v7-2.10-SNAPSHOT.jar:?]

                                      at fr.pilato.elasticsearch.crawler.fs.service.FsCrawlerManagementServiceElasticsearchImpl.getFileDirectory(FsCrawlerManagementServiceElasticsearchImpl.java:87) ~[fscrawler-core-2.10-SNAPSHOT.jar:?]

                                      at fr.pilato.elasticsearch.crawler.fs.FsParserAbstract.getFileDirectory(FsParserAbstract.java:374) ~[fscrawler-core-2.10-SNAPSHOT.jar:?]

                                      at fr.pilato.elasticsearch.crawler.fs.FsParserAbstract.addFilesRecursively(FsParserAbstract.java:334) ~[fscrawler-core-2.10-SNAPSHOT.jar:?]

                                      at fr.pilato.elasticsearch.crawler.fs.FsParserAbstract.run(FsParserAbstract.java:161) [fscrawler-core-2.10-SNAPSHOT.jar:?]

                                      at java.lang.Thread.run(Thread.java:832) [?:?]

                                      Suppressed: java.lang.RuntimeException: Request execution cancelled

                                                at org.elasticsearch.client.RestClient.extractAndWrapCause(RestClient.java:904) ~[elasticsearch-rest-client-7.16.2.jar:7.16.2]

                                                at org.elasticsearch.client.RestClient.performRequest(RestClient.java:288) ~[elasticsearch-rest-client-7.16.2.jar:7.16.2]

                                                at org.elasticsearch.client.RestClient.performRequest(RestClient.java:291) ~[elasticsearch-rest-client-7.16.2.jar:7.16.2]

                                                at org.elasticsearch.client.RestClient.performRequest(RestClient.java:291) ~[elasticsearch-rest-client-7.16.2.jar:7.16.2]

                                                at org.elasticsearch.client.RestClient.performRequest(RestClient.java:276) ~[elasticsearch-rest-client-7.16.2.jar:7.16.2]

                                                at org.elasticsearch.client.RestHighLevelClient.performClientRequest(RestHighLevelClient.java:2699) ~[elasticsearch-rest-high-level-client-7.16.2.jar:7.16.2]

                                                at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:2171) ~[elasticsearch-rest-high-level-client-7.16.2.jar:7.16.2]

                                                at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:2137) ~[elasticsearch-rest-high-level-client-7.16.2.jar:7.16.2]

                                                at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:2105) ~[elasticsearch-rest-high-level-client-7.16.2.jar:7.16.2]

                                                at org.elasticsearch.client.RestHighLevelClient.search(RestHighLevelClient.java:1367) ~[elasticsearch-rest-high-level-client-7.16.2.jar:7.16.2]

                                                at fr.pilato.elasticsearch.crawler.fs.client.v7.ElasticsearchClientV7.search(ElasticsearchClientV7.java:518) ~[fscrawler-elasticsearch-client-v7-2.10-SNAPSHOT.jar:?]

                                                at fr.pilato.elasticsearch.crawler.fs.service.FsCrawlerManagementServiceElasticsearchImpl.getFileDirectory(FsCrawlerManagementServiceElasticsearchImpl.java:87) ~[fscrawler-core-2.10-SNAPSHOT.jar:?]

                                                at fr.pilato.elasticsearch.crawler.fs.FsParserAbstract.getFileDirectory(FsParserAbstract.java:374) ~[fscrawler-core-2.10-SNAPSHOT.jar:?]

                                                at fr.pilato.elasticsearch.crawler.fs.FsParserAbstract.addFilesRecursively(FsParserAbstract.java:334) ~[fscrawler-core-2.10-SNAPSHOT.jar:?]

                                                at fr.pilato.elasticsearch.crawler.fs.FsParserAbstract.run(FsParserAbstract.java:161) [fscrawler-core-2.10-SNAPSHOT.jar:?]

                                                at java.lang.Thread.run(Thread.java:832) [?:?]

                                                Suppressed: java.lang.RuntimeException: Request execution cancelled

                                                          at org.elasticsearch.client.RestClient.extractAndWrapCause(RestClient.java:904) ~[elasticsearch-rest-client-7.16.2.jar:7.16.2]

                                                          at org.elasticsearch.client.RestClient.performRequest(RestClient.java:288) ~[elasticsearch-rest-client-7.16.2.jar:7.16.2]

                                                          at org.elasticsearch.client.RestClient.performRequest(RestClient.java:291) ~[elasticsearch-rest-client-7.16.2.jar:7.16.2]

                                                          at org.elasticsearch.client.RestClient.performRequest(RestClient.java:276) ~[elasticsearch-rest-client-7.16.2.jar:7.16.2]

                                                          at org.elasticsearch.client.RestHighLevelClient.performClientRequest(RestHighLevelClient.java:2699) ~[elasticsearch-rest-high-level-client-7.16.2.jar:7.16.2]

                                                          at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:2171) ~[elasticsearch-rest-high-level-client-7.16.2.jar:7.16.2]

                                                          at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:2137) ~[elasticsearch-rest-high-level-client-7.16.2.jar:7.16.2]

                                                          at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:2105) ~[elasticsearch-rest-high-level-client-7.16.2.jar:7.16.2]

                                                          at org.elasticsearch.client.RestHighLevelClient.search(RestHighLevelClient.java:1367) ~[elasticsearch-rest-high-level-client-7.16.2.jar:7.16.2]

                                                          at fr.pilato.elasticsearch.crawler.fs.client.v7.ElasticsearchClientV7.search(ElasticsearchClientV7.java:518) ~[fscrawler-elasticsearch-client-v7-2.10-SNAPSHOT.jar:?]

                                                          at fr.pilato.elasticsearch.crawler.fs.service.FsCrawlerManagementServiceElasticsearchImpl.getFileDirectory(FsCrawlerManagementServiceElasticsearchImpl.java:87) ~[fscrawler-core-2.10-SNAPSHOT.jar:?]

                                                          at fr.pilato.elasticsearch.crawler.fs.FsParserAbstract.getFileDirectory(FsParserAbstract.java:374) ~[fscrawler-core-2.10-SNAPSHOT.jar:?]

                                                          at fr.pilato.elasticsearch.crawler.fs.FsParserAbstract.addFilesRecursively(FsParserAbstract.java:334) ~[fscrawler-core-2.10-SNAPSHOT.jar:?]

                                                          at fr.pilato.elasticsearch.crawler.fs.FsParserAbstract.run(FsParserAbstract.java:161) [fscrawler-core-2.10-SNAPSHOT.jar:?]

                                                          at java.lang.Thread.run(Thread.java:832) [?:?]

                                                          Suppressed: java.lang.RuntimeException: Request execution cancelled

                                                                   at org.elasticsearch.client.RestClient.extractAndWrapCause(RestClient.java:904) ~[elasticsearch-rest-client-7.16.2.jar:7.16.2]

                                                                   at org.elasticsearch.client.RestClient.performRequest(RestClient.java:288) ~[elasticsearch-rest-client-7.16.2.jar:7.16.2]

                                                                   at org.elasticsearch.client.RestClient.performRequest(RestClient.java:276) ~[elasticsearch-rest-client-7.16.2.jar:7.16.2]

                                                                   at org.elasticsearch.client.RestHighLevelClient.performClientRequest(RestHighLevelClient.java:2699) ~[elasticsearch-rest-high-level-client-7.16.2.jar:7.16.2]

                                                                   at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:2171) ~[elasticsearch-rest-high-level-client-7.16.2.jar:7.16.2]

                                                                   at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:2137) ~[elasticsearch-rest-high-level-client-7.16.2.jar:7.16.2]

                                                                   at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:2105) ~[elasticsearch-rest-high-level-client-7.16.2.jar:7.16.2]

                                                                   at org.elasticsearch.client.RestHighLevelClient.search(RestHighLevelClient.java:1367) ~[elasticsearch-rest-high-level-client-7.16.2.jar:7.16.2]

                                                                   at fr.pilato.elasticsearch.crawler.fs.client.v7.ElasticsearchClientV7.search(ElasticsearchClientV7.java:518) ~[fscrawler-elasticsearch-client-v7-2.10-SNAPSHOT.jar:?]

                                                                   at fr.pilato.elasticsearch.crawler.fs.service.FsCrawlerManagementServiceElasticsearchImpl.getFileDirectory(FsCrawlerManagementServiceElasticsearchImpl.java:87) ~[fscrawler-core-2.10-SNAPSHOT.jar:?]

                                                                   at fr.pilato.elasticsearch.crawler.fs.FsParserAbstract.getFileDirectory(FsParserAbstract.java:374) ~[fscrawler-core-2.10-SNAPSHOT.jar:?]

                                                                   at fr.pilato.elasticsearch.crawler.fs.FsParserAbstract.addFilesRecursively(FsParserAbstract.java:334) ~[fscrawler-core-2.10-SNAPSHOT.jar:?]

                                                                   at fr.pilato.elasticsearch.crawler.fs.FsParserAbstract.run(FsParserAbstract.java:161) [fscrawler-core-2.10-SNAPSHOT.jar:?]

                                                                   at java.lang.Thread.run(Thread.java:832) [?:?]

                                                          Caused by: java.util.concurrent.CancellationException: Request execution cancelled

                                                                   at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase.execute(CloseableHttpAsyncClientBase.java:114) ~[httpasyncclient-4.1.5.jar:4.1.5]

                                                                   at org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute(InternalHttpAsyncClient.java:138) ~[httpasyncclient-4.1.5.jar:4.1.5]

                                                                   at org.elasticsearch.client.RestClient.performRequest(RestClient.java:284) ~[elasticsearch-rest-client-7.16.2.jar:7.16.2]

                                                                   ... 12 more

                                                Caused by: java.util.concurrent.CancellationException: Request execution cancelled

                                                          at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase.execute(CloseableHttpAsyncClientBase.java:114) ~[httpasyncclient-4.1.5.jar:4.1.5]

                                                          at org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute(InternalHttpAsyncClient.java:138) ~[httpasyncclient-4.1.5.jar:4.1.5]

                                                          at org.elasticsearch.client.RestClient.performRequest(RestClient.java:284) ~[elasticsearch-rest-client-7.16.2.jar:7.16.2]

                                                          ... 13 more

                                      Caused by: java.util.concurrent.CancellationException: Request execution cancelled

                                                at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase.execute(CloseableHttpAsyncClientBase.java:114) ~[httpasyncclient-4.1.5.jar:4.1.5]

                                                at org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute(InternalHttpAsyncClient.java:138) ~[httpasyncclient-4.1.5.jar:4.1.5]

                                                at org.elasticsearch.client.RestClient.performRequest(RestClient.java:284) ~[elasticsearch-rest-client-7.16.2.jar:7.16.2]

                                                ... 14 more

                             Caused by: java.util.concurrent.CancellationException: Request execution cancelled

                                      at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase.execute(CloseableHttpAsyncClientBase.java:114) ~[httpasyncclient-4.1.5.jar:4.1.5]

                                      at org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute(InternalHttpAsyncClient.java:138) ~[httpasyncclient-4.1.5.jar:4.1.5]

                                      at org.elasticsearch.client.RestClient.performRequest(RestClient.java:284) ~[elasticsearch-rest-client-7.16.2.jar:7.16.2]

                                      ... 15 more

                   Caused by: java.util.concurrent.CancellationException: Request execution cancelled

                             at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase.execute(CloseableHttpAsyncClientBase.java:114) ~[httpasyncclient-4.1.5.jar:4.1.5]

                             at org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute(InternalHttpAsyncClient.java:138) ~[httpasyncclient-4.1.5.jar:4.1.5]

                             at org.elasticsearch.client.RestClient.performRequest(RestClient.java:284) ~[elasticsearch-rest-client-7.16.2.jar:7.16.2]

                             ... 16 more

          Caused by: java.util.concurrent.CancellationException: Request execution cancelled

                   at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase.execute(CloseableHttpAsyncClientBase.java:114) ~[httpasyncclient-4.1.5.jar:4.1.5]

                   at org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute(InternalHttpAsyncClient.java:138) ~[httpasyncclient-4.1.5.jar:4.1.5]

                   at org.elasticsearch.client.RestClient.performRequest(RestClient.java:284) ~[elasticsearch-rest-client-7.16.2.jar:7.16.2]

                   ... 17 more

Caused by: java.util.concurrent.CancellationException: Request execution cancelled

          at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase.execute(CloseableHttpAsyncClientBase.java:114) ~[httpasyncclient-4.1.5.jar:4.1.5]

          at org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute(InternalHttpAsyncClient.java:138) ~[httpasyncclient-4.1.5.jar:4.1.5]

          at org.elasticsearch.client.RestClient.performRequest(RestClient.java:284) ~[elasticsearch-rest-client-7.16.2.jar:7.16.2]

          ... 18 more

03:50:16,072 DEBUG [f.p.e.c.f.FsParserAbstract] Fs crawler is going to sleep for 1d

xxx

xxx--this is JC stopping the service
```

**Expected behavior**

We would expect that the large folder would be indexed the same as a smaller folder 

**Versions:**
version 2.10 on windows 10

**Comment by dadoonet** [comment]
I think we need to implement this #805

**Comment by dadoonet** [comment]
I think that now we have [checkpoints](https://fscrawler--2526.org.readthedocs.build/en/2526/admin/status.html), this should be better...
