### ISSUE TITLE
Exception starting fscrawler with docker-compose

### ISSUE THREAD

**Issue by jmls** [dadoonet/fscrawler#1435]
**Describe the bug**

Following the example at https://fscrawler.readthedocs.io/en/latest/installation.html#using-docker-compose 

When I run the  **_docker-compose up fscrawler_** command I get the error

```
Attaching to fscrawler
fscrawler  | Exception in thread "main" java.util.NoSuchElementException
fscrawler  |    at java.base/java.util.Scanner.throwFor(Scanner.java:937)
fscrawler  |    at java.base/java.util.Scanner.next(Scanner.java:1478)
fscrawler  |    at fr.pilato.elasticsearch.crawler.fs.cli.FsCrawlerCli.main(FsCrawlerCli.java:254)
fscrawler exited with code 1
fscrawler  | Exception in thread "main" java.util.NoSuchElementException
fscrawler  |    at java.base/java.util.Scanner.throwFor(Scanner.java:937)
fscrawler  |    at java.base/java.util.Scanner.next(Scanner.java:1478)
fscrawler  |    at fr.pilato.elasticsearch.crawler.fs.cli.FsCrawlerCli.main(FsCrawlerCli.java:254)
fscrawler exited with code 1
```

**Job Settings**

```yml
name: 'build-one-scan'
elasticsearch:
    nodes:
        - url: 'http://elasticsearch:9200'

```

**Logs**

```
the only thin in the logs is the errors above
```

**Expected behavior**

For fscrawler to start running

**Versions:**
 - OS:Ubuntu
 - Version 20.04.4 LTS

**Comment by dadoonet** [comment]
Could you try with 2.10-SNAPSHOT ?

**Comment by dadoonet** [comment]
No further comment. I updated [the documentation](https://fscrawler.readthedocs.io/en/latest/installation.html#using-docker-compose) recently and I think it works fine now.
