### ISSUE TITLE
Stabilize tests

### ISSUE THREAD

**Issue by dadoonet** [dadoonet/fscrawler#191]
https://travis-ci.org/dadoonet/fscrawler/builds/143157508

```
HEARTBEAT J2 PID(3226@testing-worker-linux-docker-3c04b0c4-3377-linux-15): 2016-07-07T20:32:25, stalled for 10.8s at: FsCrawlerImplAllDocumentsIT (suite)
  1> 20:32:17,409 INFO  [f.p.e.c.f.t.AbstractFSCrawlerTestCase] Starting integration tests against an external cluster running elasticsearch [1.7.5]
  1> 20:32:17,430 INFO  [f.p.e.c.f.t.AbstractFSCrawlerTestCase]  -> Removing existing index [fscrawler_test_all_documents]
  1> 20:32:17,494 INFO  [f.p.e.c.f.t.AbstractFSCrawlerTestCase]   --> starting crawler in [/tmp/junit8378720724504413751/resources]
  1> 20:32:17,521 INFO  [f.p.e.c.f.FsCrawlerImpl] Starting FS crawler
  1> 20:32:20,229 INFO  [f.p.e.c.f.FsCrawlerImpl] FS crawler started for [fscrawler_test_all_documents] for [/tmp/junit8378720724504413751/resources] every [15m]
  1> 20:32:30,826 INFO  [f.p.e.c.f.t.AbstractFSCrawlerTestCase] Stopping integration tests against an external cluster
  2> Jul 07, 2016 8:32:30 PM com.carrotsearch.randomizedtesting.ThreadLeakControl checkThreadLeaks
  2> SEVERE: 2 threads leaked from SUITE scope at fr.pilato.elasticsearch.crawler.fs.test.integration.FsCrawlerImplAllDocumentsIT: 
  2>    1) Thread[id=27, name=fs-crawler, state=RUNNABLE, group=TGRP-FsCrawlerImplAllDocumentsIT]
  2>         at java.lang.ClassLoader.addClass(ClassLoader.java:263)
  2>         at java.lang.ClassLoader.defineClass1(Native Method)
  2>         at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
  2>         at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
  2>         at java.net.URLClassLoader.defineClass(URLClassLoader.java:455)
  2>         at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
  2>         at java.net.URLClassLoader$1.run(URLClassLoader.java:367)
  2>         at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
  2>         at java.security.AccessController.doPrivileged(Native Method)
  2>         at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
  2>         at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  2>         at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
  2>         at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  2>         at org.apache.pdfbox.pdmodel.font.PDTrueTypeFont.<init>(PDTrueTypeFont.java:177)
  2>         at org.apache.pdfbox.pdmodel.font.PDFontFactory.createFont(PDFontFactory.java:75)
  2>         at org.apache.pdfbox.pdmodel.PDResources.getFont(PDResources.java:123)
  2>         at org.apache.pdfbox.contentstream.operator.text.SetFontAndSize.process(SetFontAndSize.java:60)
  2>         at org.apache.pdfbox.contentstream.PDFStreamEngine.processOperator(PDFStreamEngine.java:815)
  2>         at org.apache.pdfbox.contentstream.PDFStreamEngine.processStreamOperators(PDFStreamEngine.java:472)
  2>         at org.apache.pdfbox.contentstream.PDFStreamEngine.processStream(PDFStreamEngine.java:446)
  2>         at org.apache.pdfbox.contentstream.PDFStreamEngine.processPage(PDFStreamEngine.java:149)
  2>         at org.apache.pdfbox.text.PDFTextStreamEngine.processPage(PDFTextStreamEngine.java:136)
  2>         at org.apache.pdfbox.text.PDFTextStripper.processPage(PDFTextStripper.java:391)
  2>         at org.apache.tika.parser.pdf.PDF2XHTML.processPage(PDF2XHTML.java:214)
  2>         at org.apache.pdfbox.text.PDFTextStripper.processPages(PDFTextStripper.java:319)
  2>         at org.apache.pdfbox.text.PDFTextStripper.writeText(PDFTextStripper.java:266)
  2>         at org.apache.tika.parser.pdf.PDF2XHTML.process(PDF2XHTML.java:160)
  2>         at org.apache.tika.parser.pdf.PDFParser.parse(PDFParser.java:144)
  2>         at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
  2>         at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
  2>         at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:120)
  2>         at org.apache.tika.Tika.parseToString(Tika.java:568)
  2>         at fr.pilato.elasticsearch.crawler.fs.tika.TikaDocParser.generate(TikaDocParser.java:63)
  2>         at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.indexFile(FsCrawlerImpl.java:589)
  2>         at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.addFilesRecursively(FsCrawlerImpl.java:378)
  2>         at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.run(FsCrawlerImpl.java:278)
  2>         at java.lang.Thread.run(Thread.java:745)
  2>    2) Thread[id=26, name=pool-2-thread-1, state=TIMED_WAITING, group=TGRP-FsCrawlerImplAllDocumentsIT]
  2>         at sun.misc.Unsafe.park(Native Method)
  2>         at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
  2>         at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
  2>         at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
  2>         at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
  2>         at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
  2>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
  2>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  2>         at java.lang.Thread.run(Thread.java:745)
  2> Jul 07, 2016 8:32:30 PM com.carrotsearch.randomizedtesting.ThreadLeakControl tryToInterruptAll
  2> INFO: Starting to interrupt leaked threads:
  2>    1) Thread[id=27, name=fs-crawler, state=RUNNABLE, group=TGRP-FsCrawlerImplAllDocumentsIT]
  2>    2) Thread[id=26, name=pool-2-thread-1, state=TIMED_WAITING, group=TGRP-FsCrawlerImplAllDocumentsIT]
  1> 20:32:31,139 WARN  [f.p.e.c.f.FsCrawlerImpl] Error while indexing content from /tmp/junit8378720724504413751/resources
  1> 20:32:31,139 WARN  [f.p.e.c.f.FsCrawlerImpl] Error while indexing content from /tmp/junit8378720724504413751/resources
  1> 20:32:31,415 WARN  [f.p.e.c.f.FsCrawlerImpl] Error while indexing content from /tmp/junit8378720724504413751/resources
  1> 20:32:31,917 WARN  [f.p.e.c.f.FsCrawlerImpl] Error while indexing content from /tmp/junit8378720724504413751/resources
  1> 20:32:32,418 WARN  [f.p.e.c.f.FsCrawlerImpl] Error while indexing content from /tmp/junit8378720724504413751/resources
  1> 20:32:32,919 WARN  [f.p.e.c.f.FsCrawlerImpl] Error while indexing content from /tmp/junit8378720724504413751/resources
  1> 20:32:33,421 WARN  [f.p.e.c.f.FsCrawlerImpl] Error while indexing content from /tmp/junit8378720724504413751/resources
  2> Jul 07, 2016 8:32:33 PM com.carrotsearch.randomizedtesting.ThreadLeakControl tryToInterruptAll
  2> SEVERE: There are still zombie threads that couldn't be terminated:
  2>    1) Thread[id=27, name=fs-crawler, state=TIMED_WAITING, group=TGRP-FsCrawlerImplAllDocumentsIT]
  2>         at java.lang.Object.wait(Native Method)
  2>         at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.run(FsCrawlerImpl.java:302)
  2>         at java.lang.Thread.run(Thread.java:745)
  2>    2) Thread[id=26, name=pool-2-thread-1, state=TIMED_WAITING, group=TGRP-FsCrawlerImplAllDocumentsIT]
  2>         at sun.misc.Unsafe.park(Native Method)
  2>         at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
  2>         at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
  2>         at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
  2>         at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
  2>         at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
  2>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
  2>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  2>         at java.lang.Thread.run(Thread.java:745)
  2> REPRODUCE WITH:
  2> mvn test -Dtests.seed=4BE2D28E8B73442D -Dtests.class=fr.pilato.elasticsearch.crawler.fs.test.integration.FsCrawlerImplAllDocumentsIT -Dtests.locale=en-US -Dtests.timezone=Etc/UTC
  2> REPRODUCE WITH:
  2> mvn test -Dtests.seed=4BE2D28E8B73442D -Dtests.class=fr.pilato.elasticsearch.crawler.fs.test.integration.FsCrawlerImplAllDocumentsIT -Dtests.locale=en-US -Dtests.timezone=Etc/UTC
  2> REPRODUCE WITH:
  2> mvn test -Dtests.seed=4BE2D28E8B73442D -Dtests.class=fr.pilato.elasticsearch.crawler.fs.test.integration.FsCrawlerImplAllDocumentsIT -Dtests.locale=en-US -Dtests.timezone=Etc/UTC
```

**Comment by dadoonet** [comment]
Reopening. Still failing: https://travis-ci.org/dadoonet/fscrawler/builds/143172241

```
HEARTBEAT J2 PID(5292@testing-worker-linux-docker-b5ea8833-3393-linux-16): 2016-07-07T21:37:04, stalled for 10.5s at: FsCrawlerImplAllDocumentsIT (suite)
  1> 21:36:56,729 [32mINFO [m [f.p.e.c.f.t.AbstractFSCrawlerTestCase] Starting integration tests against an external cluster running elasticsearch [5.0.0-alpha4]
  1> 21:36:56,770 [32mINFO [m [f.p.e.c.f.t.AbstractFSCrawlerTestCase]  -> Removing existing index [fscrawler_test_all_documents]
  1> 21:36:56,795 [32mINFO [m [f.p.e.c.f.t.AbstractFSCrawlerTestCase]   --> starting crawler in [/tmp/junit2787961957161839478/resources] which contains [10] files
  1> 21:36:56,805 [32mINFO [m [f.p.e.c.f.FsCrawlerImpl] Starting FS crawler
  1> 21:36:58,055 [32mINFO [m [f.p.e.c.f.FsCrawlerImpl] FS crawler started for [fscrawler_test_all_documents] for [/tmp/junit2787961957161839478/resources] every [15m]
  1> 21:37:08,086 [32mINFO [m [f.p.e.c.f.t.AbstractFSCrawlerTestCase] Stopping integration tests against an external cluster
  2> Jul 07, 2016 9:37:08 PM com.carrotsearch.randomizedtesting.ThreadLeakControl checkThreadLeaks
  2> SEVERE: 2 threads leaked from SUITE scope at fr.pilato.elasticsearch.crawler.fs.test.integration.FsCrawlerImplAllDocumentsIT: 
  2>    1) Thread[id=27, name=fs-crawler, state=RUNNABLE, group=TGRP-FsCrawlerImplAllDocumentsIT]
  2>         at org.apache.tika.parser.rtf.TextExtractor.isAlpha(TextExtractor.java:328)
  2>         at org.apache.tika.parser.rtf.TextExtractor.parseControlWord(TextExtractor.java:530)
  2>         at org.apache.tika.parser.rtf.TextExtractor.parseControlToken(TextExtractor.java:488)
  2>         at org.apache.tika.parser.rtf.TextExtractor.extract(TextExtractor.java:450)
  2>         at org.apache.tika.parser.rtf.TextExtractor.extract(TextExtractor.java:439)
  2>         at org.apache.tika.parser.rtf.RTFParser.parse(RTFParser.java:87)
  2>         at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
  2>         at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
  2>         at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:120)
  2>         at org.apache.tika.Tika.parseToString(Tika.java:568)
  2>         at fr.pilato.elasticsearch.crawler.fs.tika.TikaDocParser.generate(TikaDocParser.java:63)
  2>         at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.indexFile(FsCrawlerImpl.java:589)
  2>         at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.addFilesRecursively(FsCrawlerImpl.java:378)
  2>         at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.run(FsCrawlerImpl.java:278)
  2>         at java.lang.Thread.run(Thread.java:745)
  2>    2) Thread[id=26, name=pool-2-thread-1, state=TIMED_WAITING, group=TGRP-FsCrawlerImplAllDocumentsIT]
  2>         at sun.misc.Unsafe.park(Native Method)
  2>         at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
  2>         at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
  2>         at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
  2>         at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
  2>         at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
  2>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
  2>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  2>         at java.lang.Thread.run(Thread.java:745)
  2> Jul 07, 2016 9:37:08 PM com.carrotsearch.randomizedtesting.ThreadLeakControl tryToInterruptAll
  2> INFO: Starting to interrupt leaked threads:
  2>    1) Thread[id=27, name=fs-crawler, state=BLOCKED, group=TGRP-FsCrawlerImplAllDocumentsIT]
  2>    2) Thread[id=26, name=pool-2-thread-1, state=RUNNABLE, group=TGRP-FsCrawlerImplAllDocumentsIT]
```

**Comment by dadoonet** [comment]
The error is actually generated by a bulk test which expects 0 documents but it could happen that we actually already indexed some docs when we run this assertion.

**Comment by dadoonet** [comment]
Issue is still here: https://travis-ci.org/dadoonet/fscrawler/builds/143532146

**Comment by dadoonet** [comment]
After more digging, it still failing but for race reasons.

Apparently sometimes the FSCrawler is not stoppable because some pending BULK requests or queries are not yet consumed.
So the REST client leaves the channel opened and that might explain some errors we are seeing recently.

**Comment by dadoonet** [comment]
It sounds like that tests are now stable. Closing this for now.

**Comment by dadoonet** [comment]
Spoke too fast: https://travis-ci.org/dadoonet/fscrawler/builds/160489717

**Comment by dadoonet** [comment]
From what I can see now, I don't see anymore Threadleaks failures.
I do see other Travis failures but that's something else. So I'm closing this one now.
