### ISSUE TITLE
Out of memory errors: potential memory leak

### ISSUE THREAD

**Issue by Muffinman** [dadoonet/fscrawler#196]
Hi,

I've been trying to compile the master branch & run manually but I'm getting out of memory errors:

(I'm running fscrawler with 8G heap)

```
10:12:35,510 WARN  [f.p.e.c.f.c.BulkProcessor] Error executing bulk
java.io.IOException: insufficient data written
	at sun.net.www.protocol.http.HttpURLConnection$StreamingOutputStream.close(HttpURLConnection.java:3501) ~[?:1.8.0_91]
	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:81) ~[google-http-client-1.20.0.jar:1.20.0]
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:972) ~[google-http-client-1.20.0.jar:1.20.0]
	at fr.pilato.elasticsearch.crawler.fs.client.ElasticsearchClient.bulk(ElasticsearchClient.java:231) ~[fscrawler-2.1-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.client.ElasticsearchClient.bulk(ElasticsearchClient.java:243) ~[fscrawler-2.1-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.client.BulkProcessor.execute(BulkProcessor.java:136) [fscrawler-2.1-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.client.BulkProcessor.executeIfNeeded(BulkProcessor.java:116) [fscrawler-2.1-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.client.BulkProcessor.internalAdd(BulkProcessor.java:109) [fscrawler-2.1-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.client.BulkProcessor.add(BulkProcessor.java:97) [fscrawler-2.1-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.client.BulkProcessor.add(BulkProcessor.java:83) [fscrawler-2.1-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.esIndex(FsCrawlerImpl.java:708) [fscrawler-2.1-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.esIndex(FsCrawlerImpl.java:697) [fscrawler-2.1-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.indexDirectory(FsCrawlerImpl.java:628) [fscrawler-2.1-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.indexDirectory(FsCrawlerImpl.java:639) [fscrawler-2.1-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.addFilesRecursively(FsCrawlerImpl.java:406) [fscrawler-2.1-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.addFilesRecursively(FsCrawlerImpl.java:407) [fscrawler-2.1-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.addFilesRecursively(FsCrawlerImpl.java:407) [fscrawler-2.1-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.run(FsCrawlerImpl.java:299) [fscrawler-2.1-SNAPSHOT.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
```

Our _settings.json

```
{
  "name" : "archive",
  "fs" : {
    "url" : "/media/raid/archive",
    "update_rate" : "1h",
    "includes": [
      "*.*"
    ],
    "excludes": [
      ".git",
      "node_modules",
      "vendor"
    ],
    "json_support" : true,
    "attributes_support" : true,
    "raw_metadata" : false,
    "filename_as_id" : false,
    "add_filesize" : true,
    "remove_deleted" : true,
    "store_source" : false,
    "indexed_chars" : 10000,
    "checksum" : "MD5",
    "index_content" : true
  },
  "elasticsearch" : {
    "nodes" : [ {
      "host" : "192.168.10.30",
      "port" : 9200
    } ],
    "index" : "fscrawler_archive",
    "type" : "doc",
    "bulk_size" : 100,
    "flush_interval" : "5s"
  }
}
```

It may be that the master branch is not stable right now? Any news on a 2.1 release date?

**Comment by dadoonet** [comment]
Release is close I think. May be in a week.

Did you try the new option FS_JAVA_OPTS when launching FS Crawler?

**Comment by Muffinman** [comment]
Hi, yes in htop I can see that it's filled all 8g of memory I told it to use.

We're running it on a large volume (probably a few million files), perhaps it's legitimately filling the memory?

I was just assuming there's a memory leak somewhere.

**Comment by dadoonet** [comment]
Very interesting. I never ran FS Crawler on very big files... I need to dig into this more.

**Comment by petosorus** [comment]
I think this comes from the way files are read before indexing.
In `FsCrawlerImpl`, a file is first read into a byte array, and only after is `indexedChars` taken into account.

Code snippet: 
```
if (fsSettings.getFs().isIndexContent()) {
                
                byte[] buffer = new byte[1024];
                ByteArrayOutputStream bos = new ByteArrayOutputStream();
                int i;
                while (-1 != (i = fileReader.read(buffer))) {
                    bos.write(buffer, 0, i);
                }
                byte[] data = bos.toByteArray();

                fileReader.close();
                bos.close();

                // https://github.com/dadoonet/fscrawler/issues/5 : Support JSon files
                if (fsSettings.getFs().isJsonSupport()) {
                    String id;
                    if (fsSettings.getFs().isFilenameAsId()) {
                        id = filename;
                        int pos = id.lastIndexOf(".");
                        if (pos > 0) {
                            id = id.substring(0, pos);
                        }
                    } else {
                        id = SignTool.sign((new File(filepath, filename)).toString());
                    }
                    esIndex(fsSettings.getElasticsearch().getIndex(),
                            fsSettings.getElasticsearch().getType(),
                            id,
                            new String(data, "UTF-8"));
                    return;
                } else {
                    // Extracting content with Tika
                    // See #38: https://github.com/dadoonet/fscrawler/issues/38
                    int indexedChars = 100000;
                    if (fsSettings.getFs().getIndexedChars() != null) {
                        if (fsSettings.getFs().getIndexedChars().percentage()) {
                            indexedChars = (int) Math.round(data.length * fsSettings.getFs().getIndexedChars().asDouble());
                            logger.trace("using percentage [{}] to define indexed chars: [{}]",
                                    fsSettings.getFs().getIndexedChars(), indexedChars);
                        } else {
                            indexedChars = (int) fsSettings.getFs().getIndexedChars().value();
                            logger.trace("indexed chars [{}]",
                                    indexedChars == -1 ? "has been disabled. All text will be extracted" : indexedChars);
                        }
                    }
                    Metadata metadata = new Metadata();

                    String parsedContent = null;
                    try {
                        // Set the maximum length of strings returned by the parseToString method, -1 sets no limit
                        parsedContent = tika().parseToString(new ByteArrayInputStream(data), metadata, indexedChars);
                    } catch (Throwable e) {
                        logger.debug("Failed to extract [" + indexedChars + "] characters of text for [" + filename + "]", e);
                    }
```

**Comment by dadoonet** [comment]
Makes sense. I need to simply stream the file to Tika...
Will give a look ASAP. I expect a fix for the end of this week.

**Comment by Muffinman** [comment]
Just tried this on our files, still no luck sorry ;(

We're running the following:

Ubuntu 14.04
Elasticsearch 2.3.4 (on a different machine on the LAN, not that this should matter)
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)


````
root@file-server ~/fscrawler-2.2-SNAPSHOT# ./bin/fscrawler archive
17:18:20,692 INFO  [f.p.e.c.f.FsCrawlerImpl] Starting FS crawler
17:18:20,744 INFO  [f.p.e.c.f.FsCrawlerImpl] FS crawler started for [archive] for [/media/raid/archive] every [1h]
17:18:29,974 WARN  [f.p.e.c.f.c.BulkProcessor] Error executing bulk
java.io.IOException: insufficient data written
	at sun.net.www.protocol.http.HttpURLConnection$StreamingOutputStream.close(HttpURLConnection.java:3501) ~[?:1.8.0_101]
	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:81) ~[google-http-client-1.20.0.jar:1.20.0]
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:972) ~[google-http-client-1.20.0.jar:1.20.0]
	at fr.pilato.elasticsearch.crawler.fs.client.ElasticsearchClient.bulk(ElasticsearchClient.java:231) ~[fscrawler-2.2-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.client.ElasticsearchClient.bulk(ElasticsearchClient.java:243) ~[fscrawler-2.2-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.client.BulkProcessor.execute(BulkProcessor.java:136) ~[fscrawler-2.2-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.client.BulkProcessor.executeWhenNeeded(BulkProcessor.java:123) ~[fscrawler-2.2-SNAPSHOT.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_101]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_101]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_101]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
17:18:38,404 WARN  [f.p.e.c.f.c.BulkProcessor] Error executing bulk
java.io.IOException: insufficient data written
	at sun.net.www.protocol.http.HttpURLConnection$StreamingOutputStream.close(HttpURLConnection.java:3501) ~[?:1.8.0_101]
	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:81) ~[google-http-client-1.20.0.jar:1.20.0]
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:972) ~[google-http-client-1.20.0.jar:1.20.0]
	at fr.pilato.elasticsearch.crawler.fs.client.ElasticsearchClient.bulk(ElasticsearchClient.java:231) ~[fscrawler-2.2-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.client.ElasticsearchClient.bulk(ElasticsearchClient.java:243) ~[fscrawler-2.2-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.client.BulkProcessor.execute(BulkProcessor.java:136) [fscrawler-2.2-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.client.BulkProcessor.executeIfNeeded(BulkProcessor.java:116) [fscrawler-2.2-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.client.BulkProcessor.internalAdd(BulkProcessor.java:109) [fscrawler-2.2-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.client.BulkProcessor.add(BulkProcessor.java:97) [fscrawler-2.2-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.client.BulkProcessor.add(BulkProcessor.java:83) [fscrawler-2.2-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.esIndex(FsCrawlerImpl.java:704) [fscrawler-2.2-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.indexFile(FsCrawlerImpl.java:592) [fscrawler-2.2-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.addFilesRecursively(FsCrawlerImpl.java:396) [fscrawler-2.2-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.addFilesRecursively(FsCrawlerImpl.java:406) [fscrawler-2.2-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.addFilesRecursively(FsCrawlerImpl.java:406) [fscrawler-2.2-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.addFilesRecursively(FsCrawlerImpl.java:406) [fscrawler-2.2-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.run(FsCrawlerImpl.java:298) [fscrawler-2.2-SNAPSHOT.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
17:18:50,771 WARN  [f.p.e.c.f.c.BulkProcessor] Error executing bulk
java.io.IOException: insufficient data written
	at sun.net.www.protocol.http.HttpURLConnection$StreamingOutputStream.close(HttpURLConnection.java:3501) ~[?:1.8.0_101]
	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:81) ~[google-http-client-1.20.0.jar:1.20.0]
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:972) ~[google-http-client-1.20.0.jar:1.20.0]
	at fr.pilato.elasticsearch.crawler.fs.client.ElasticsearchClient.bulk(ElasticsearchClient.java:231) ~[fscrawler-2.2-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.client.ElasticsearchClient.bulk(ElasticsearchClient.java:243) ~[fscrawler-2.2-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.client.BulkProcessor.execute(BulkProcessor.java:136) [fscrawler-2.2-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.client.BulkProcessor.executeIfNeeded(BulkProcessor.java:116) [fscrawler-2.2-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.client.BulkProcessor.internalAdd(BulkProcessor.java:109) [fscrawler-2.2-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.client.BulkProcessor.add(BulkProcessor.java:97) [fscrawler-2.2-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.client.BulkProcessor.add(BulkProcessor.java:83) [fscrawler-2.2-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.esIndex(FsCrawlerImpl.java:704) [fscrawler-2.2-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.indexFile(FsCrawlerImpl.java:592) [fscrawler-2.2-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.addFilesRecursively(FsCrawlerImpl.java:396) [fscrawler-2.2-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.addFilesRecursively(FsCrawlerImpl.java:406) [fscrawler-2.2-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.addFilesRecursively(FsCrawlerImpl.java:406) [fscrawler-2.2-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.addFilesRecursively(FsCrawlerImpl.java:406) [fscrawler-2.2-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.run(FsCrawlerImpl.java:298) [fscrawler-2.2-SNAPSHOT.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
17:19:01,011 WARN  [f.p.e.c.f.c.BulkProcessor] Error executing bulk
java.io.IOException: insufficient data written
	at sun.net.www.protocol.http.HttpURLConnection$StreamingOutputStream.close(HttpURLConnection.java:3501) ~[?:1.8.0_101]
	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:81) ~[google-http-client-1.20.0.jar:1.20.0]
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:972) ~[google-http-client-1.20.0.jar:1.20.0]
	at fr.pilato.elasticsearch.crawler.fs.client.ElasticsearchClient.bulk(ElasticsearchClient.java:231) ~[fscrawler-2.2-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.client.ElasticsearchClient.bulk(ElasticsearchClient.java:243) ~[fscrawler-2.2-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.client.BulkProcessor.execute(BulkProcessor.java:136) ~[fscrawler-2.2-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.client.BulkProcessor.executeWhenNeeded(BulkProcessor.java:123) ~[fscrawler-2.2-SNAPSHOT.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_101]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_101]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_101]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Exception in thread "fs-crawler" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:137)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:121)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:421)
	at java.lang.StringBuilder.append(StringBuilder.java:136)
	at java.lang.StringBuilder.append(StringBuilder.java:76)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:457)
	at java.lang.StringBuilder.append(StringBuilder.java:166)
	at java.util.StringJoiner.add(StringJoiner.java:185)
	at java.util.stream.Collectors$$Lambda$35/1226760401.accept(Unknown Source)
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.read(FsCrawlerImpl.java:612)
	at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.indexFile(FsCrawlerImpl.java:595)
	at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.addFilesRecursively(FsCrawlerImpl.java:396)
	at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.addFilesRecursively(FsCrawlerImpl.java:406)
	at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.addFilesRecursively(FsCrawlerImpl.java:406)
	at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.addFilesRecursively(FsCrawlerImpl.java:406)
	at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.addFilesRecursively(FsCrawlerImpl.java:406)
	at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.run(FsCrawlerImpl.java:298)
	at java.lang.Thread.run(Thread.java:745)

````

**Comment by dadoonet** [comment]
Ha! I missed that you are actually using `"index_content" : true`. This is causing the issue you have.
Let me reopen and come with another fix specific to this part.

**Comment by dadoonet** [comment]
Actually I read the code again and your issue. `"json_support" : true`. So you are sending a very very big JSON document. Is that what you are doing?

**Comment by Muffinman** [comment]
Hmm I didn't notice we had that set to true. I don't think we actually have any JSON documents so I'll try turning that off. Will report back shortly!

**Comment by Muffinman** [comment]
Yes that does seem to have resolved our problems! Many thanks!

So was that config option assuming that ALL files being indexed were JSON?

**Comment by dadoonet** [comment]
This option basically directly copy the file content without any extraction by Tika and add them as is to the BulkProcessor.
Sending a binary content file as a BulkRequest would probably produce bad behavior.

I don't understand though why FSCrawler did not report errors (wrong format or something) though.
I need to add a test.

Thanks for confirming. 

Funny story: your bug report made me discover that we can do better in term of memory usage by using streams instead of converting to `byte[]` all the time...
Definitely we have a better code now! :)

**Comment by tcarolan** [comment]
The issue of large files is going to prove difficult.  For example, A 200MB CSV file is being stored multiple times throughout the code in Strings - my heap expands beyond 26 Gigs  - all the memory I could afford to allocate.  This happens even when using a BulkSize of 1. The line it finally blows up with OOM is `StringEntity entity = new StringEntity(sbf.toString(), Charset.defaultCharset());` in ElasticSearchClient class. 

The use of an InputStreamEntity could help but the entire file's content would have to be streamed from Tika and converted to JSON without using Strings to store the content - I don't even know if this is doable, perhaps?  I don't think the new ES 5 Java client can avoid this problem because it's not HTTP transmission issue - it's a memory problem within fscrawler.  

One solution may be to break up the document into chunks so it can be indexed as separate but related docs. This would be a pretty major change for fscrawler since it would have to resolve the related docs somehow and clean up deleted files, re-index across multiple ES docs when the file changes,, etc. 

A simple solution would be to put a max file size parameter on fscrawler for now. Kinda hacky, but could help avoid OOM problems when somebody adds a monster file that somehow gets indexed.
