### ISSUE TITLE
'failed to determine group ' error

### ISSUE THREAD

**Issue by neetubhatt** [dadoonet/fscrawler#219]
{
  "name" : "demo",
  "fs" : {
	  "attributes_support" : true
    "url" : "C:/test",
    "update_rate" : "15m",
    "includes": [
      "*.*"
    ],
    "excludes" : null,
    "json_support" : true,
    "filename_as_id" : true,
    "add_filesize" : true,
    "remove_deleted" : true,
    "store_source" : false,
    "index_content" : true,
    "indexed_chars" : "10000",
    "attributes_support" : false,
    "raw_metadata" : true,
    "checksum" : null
  },
  "server" : {
    "hostname" : null,
    "port" : 22,
    "username" : null,
    "password" : null,
    "protocol" : "local",
    "pem_path" : null
  },
  "elasticsearch" : {
    "nodes" : [ {
      "host" : "127.0.0.1",
      "port" : 9200
    } ],
    "index" : "docs",
    "type" : "doc",
    "bulk_size" : 100,
    "flush_interval" : "5s"
  }
}

THis is my json file _settings.json  but when iam running fscrawler demo iam getting error as :12:35:00,517 ←[33mWARN ←[m [f.p.e.c.f.u.FsCrawlerUtil] Failed to determine 'grou
p' of C:\test\Worldwide Payroll Contacts and Calendars 2015.xlsx: null .
Please let me know what iam doing wrong over here .

**Comment by dadoonet** [comment]
It's just a warn.

Fixed in #211

**Comment by neetubhatt** [comment]
But in logs also iam getting error as   :[2016-08-18 13:06:44,475][DEBUG][action.bulk ] [Access] [docs][3] failed to execute bulk item (index) index {[docs][doc][Tricky Question_jpg_jpg],
source[_na_]}
MapperParsingException[failed to parse]; nested: NotXContentException[Compressor
 detection can only be called on some xcontent bytes or compressed xcontent byte
s];
        at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentP
arser.java:154)
        at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.ja
va:309)
        at org.elasticsearch.index.shard.IndexShard.prepareIndex(IndexShard.java
:580)
        at org.elasticsearch.index.shard.IndexShard.prepareIndexOnPrimary(IndexS
hard.java:559)

**Comment by dadoonet** [comment]
I think you should have a more detailed stacktrace on Elasticsearch node, right? Could you paste it?

**Comment by dadoonet** [comment]
Could you try the SNAPSHOT build?

**Comment by neetubhatt** [comment]
[2016-08-18 13:06:44,475][DEBUG][action.bulk              ] [Access] [docs][3] f
ailed to execute bulk item (index) index {[docs][doc][Tricky Question_jpg_jpg],
source[_na_]}
MapperParsingException[failed to parse]; nested: NotXContentException[Compressor
 detection can only be called on some xcontent bytes or compressed xcontent byte
s];
        at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentP
arser.java:154)
        at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.ja
va:309)
        at org.elasticsearch.index.shard.IndexShard.prepareIndex(IndexShard.java
:580)
        at org.elasticsearch.index.shard.IndexShard.prepareIndexOnPrimary(IndexS
hard.java:559)
        at org.elasticsearch.action.index.TransportIndexAction.prepareIndexOpera
tionOnPrimary(TransportIndexAction.java:212)
        at org.elasticsearch.action.index.TransportIndexAction.executeIndexReque
stOnPrimary(TransportIndexAction.java:224)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardIndexOper
ation(TransportShardBulkAction.java:327)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperation
OnPrimary(TransportShardBulkAction.java:120)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperation
OnPrimary(TransportShardBulkAction.java:68)
        at org.elasticsearch.action.support.replication.TransportReplicationActi
on$PrimaryPhase.doRun(TransportReplicationAction.java:639)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(Abstrac
tRunnable.java:37)
        at org.elasticsearch.action.support.replication.TransportReplicationActi
on$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.j
ava:279)
        at org.elasticsearch.action.support.replication.TransportReplicationActi
on$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.j
ava:271)
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageRece
ived(RequestHandlerRegistry.java:75)
        at org.elasticsearch.transport.TransportService$4.doRun(TransportService
.java:376)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(Abstrac
tRunnable.java:37)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.common.compress.NotXContentException: Compressor de
tection can only be called on some xcontent bytes or compressed xcontent bytes
        at org.elasticsearch.common.compress.CompressorFactory.compressor(Compre
ssorFactory.java:85)
        at org.elasticsearch.common.xcontent.XContentHelper.createParser(XConten
tHelper.java:50)
        at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentP
arser.java:90)
        ... 18 more
[2016-08-18 13:21:46,519][DEBUG][action.bulk              ] [Access] [docs][4] f
ailed to execute bulk item (index) index {[docs][doc][test2], source[_na_]}
MapperParsingException[failed to parse]; nested: NotXContentException[Compressor
 detection can only be called on some xcontent bytes or compressed xcontent byte
s];
        at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentP
arser.java:154)
        at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.ja
va:309)
        at org.elasticsearch.index.shard.IndexShard.prepareIndex(IndexShard.java
:580)
        at org.elasticsearch.index.shard.IndexShard.prepareIndexOnPrimary(IndexS
hard.java:559)
        at org.elasticsearch.action.index.TransportIndexAction.prepareIndexOpera
tionOnPrimary(TransportIndexAction.java:212)
        at org.elasticsearch.action.index.TransportIndexAction.executeIndexReque
stOnPrimary(TransportIndexAction.java:224)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardIndexOper
ation(TransportShardBulkAction.java:327)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperation
OnPrimary(TransportShardBulkAction.java:120)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperation
OnPrimary(TransportShardBulkAction.java:68)
        at org.elasticsearch.action.support.replication.TransportReplicationActi
on$PrimaryPhase.doRun(TransportReplicationAction.java:639)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(Abstrac
tRunnable.java:37)
        at org.elasticsearch.action.support.replication.TransportReplicationActi
on$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.j
ava:279)
        at org.elasticsearch.action.support.replication.TransportReplicationActi
on$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.j
ava:271)
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageRece
ived(RequestHandlerRegistry.java:75)
        at org.elasticsearch.transport.TransportService$4.doRun(TransportService
.java:376)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(Abstrac
tRunnable.java:37)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.common.compress.NotXContentException: Compressor de
tection can only be called on some xcontent bytes or compressed xcontent bytes
        at org.elasticsearch.common.compress.CompressorFactory.compressor(Compre
ssorFactory.java:85)
        at org.elasticsearch.common.xcontent.XContentHelper.createParser(XConten
tHelper.java:50)
        at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentP
arser.java:90)
        ... 18 more
[2016-08-18 13:21:46,675][DEBUG][action.bulk              ] [Access] [docs][3] f
ailed to execute bulk item (index) index {[docs][doc][hrportal], source[_na_]}
MapperParsingException[failed to parse]; nested: NotXContentException[Compressor
 detection can only be called on some xcontent bytes or compressed xcontent byte
s];
        at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentP
arser.java:154)
        at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.ja
va:309)
        at org.elasticsearch.index.shard.IndexShard.prepareIndex(IndexShard.java
:580)
        at org.elasticsearch.index.shard.IndexShard.prepareIndexOnPrimary(IndexS
hard.java:559)
        at org.elasticsearch.action.index.TransportIndexAction.prepareIndexOpera
tionOnPrimary(TransportIndexAction.java:212)
        at org.elasticsearch.action.index.TransportIndexAction.executeIndexReque
stOnPrimary(TransportIndexAction.java:224)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardIndexOper
ation(TransportShardBulkAction.java:327)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperation
OnPrimary(TransportShardBulkAction.java:120)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperation
OnPrimary(TransportShardBulkAction.java:68)
        at org.elasticsearch.action.support.replication.TransportReplicationActi
on$PrimaryPhase.doRun(TransportReplicationAction.java:639)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(Abstrac
tRunnable.java:37)
        at org.elasticsearch.action.support.replication.TransportReplicationActi
on$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.j
ava:279)
        at org.elasticsearch.action.support.replication.TransportReplicationActi
on$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.j
ava:271)
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageRece
ived(RequestHandlerRegistry.java:75)
        at org.elasticsearch.transport.TransportService$4.doRun(TransportService
.java:376)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(Abstrac
tRunnable.java:37)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.common.compress.NotXContentException: Compressor de
tection can only be called on some xcontent bytes or compressed xcontent bytes
        at org.elasticsearch.common.compress.CompressorFactory.compressor(Compre
ssorFactory.java:85)
        at org.elasticsearch.common.xcontent.XContentHelper.createParser(XConten
tHelper.java:50)
        at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentP
arser.java:90)
        ... 18 more
[2016-08-18 13:21:46,675][DEBUG][action.bulk              ] [Access] [docs][3] f
ailed to execute bulk item (index) index {[docs][doc][HR], source[_na_]}
MapperParsingException[failed to parse]; nested: NotXContentException[Compressor
 detection can only be called on some xcontent bytes or compressed xcontent byte
s];
        at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentP
arser.java:154)
        at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.ja
va:309)
        at org.elasticsearch.index.shard.IndexShard.prepareIndex(IndexShard.java
:580)
        at org.elasticsearch.index.shard.IndexShard.prepareIndexOnPrimary(IndexS
hard.java:559)
        at org.elasticsearch.action.index.TransportIndexAction.prepareIndexOpera
tionOnPrimary(TransportIndexAction.java:212)
        at org.elasticsearch.action.index.TransportIndexAction.executeIndexReque
stOnPrimary(TransportIndexAction.java:224)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardIndexOper
ation(TransportShardBulkAction.java:327)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperation
OnPrimary(TransportShardBulkAction.java:120)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperation
OnPrimary(TransportShardBulkAction.java:68)
        at org.elasticsearch.action.support.replication.TransportReplicationActi
on$PrimaryPhase.doRun(TransportReplicationAction.java:639)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(Abstrac
tRunnable.java:37)
        at org.elasticsearch.action.support.replication.TransportReplicationActi
on$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.j
ava:279)
        at org.elasticsearch.action.support.replication.TransportReplicationActi
on$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.j
ava:271)
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageRece
ived(RequestHandlerRegistry.java:75)
        at org.elasticsearch.transport.TransportService$4.doRun(TransportService
.java:376)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(Abstrac
tRunnable.java:37)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.common.compress.NotXContentException: Compressor de
tection can only be called on some xcontent bytes or compressed xcontent bytes
        at org.elasticsearch.common.compress.CompressorFactory.compressor(Compre
ssorFactory.java:85)
        at org.elasticsearch.common.xcontent.XContentHelper.createParser(XConten
tHelper.java:50)
        at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentP
arser.java:90)
        ... 18 more
[2016-08-18 13:21:46,675][DEBUG][action.bulk              ] [Access] [docs][3] f
ailed to execute bulk item (index) index {[docs][doc][style-slider], source[_na_
]}
MapperParsingException[failed to parse]; nested: NotXContentException[Compressor
 detection can only be called on some xcontent bytes or compressed xcontent byte
s];
        at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentP
arser.java:154)
        at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.ja
va:309)
        at org.elasticsearch.index.shard.IndexShard.prepareIndex(IndexShard.java
:580)
        at org.elasticsearch.index.shard.IndexShard.prepareIndexOnPrimary(IndexS
hard.java:559)
        at org.elasticsearch.action.index.TransportIndexAction.prepareIndexOpera
tionOnPrimary(TransportIndexAction.java:212)
        at org.elasticsearch.action.index.TransportIndexAction.executeIndexReque
stOnPrimary(TransportIndexAction.java:224)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardIndexOper
ation(TransportShardBulkAction.java:327)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperation
OnPrimary(TransportShardBulkAction.java:120)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperation
OnPrimary(TransportShardBulkAction.java:68)
        at org.elasticsearch.action.support.replication.TransportReplicationActi
on$PrimaryPhase.doRun(TransportReplicationAction.java:639)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(Abstrac
tRunnable.java:37)
        at org.elasticsearch.action.support.replication.TransportReplicationActi
on$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.j
ava:279)
        at org.elasticsearch.action.support.replication.TransportReplicationActi
on$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.j
ava:271)
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageRece
ived(RequestHandlerRegistry.java:75)
        at org.elasticsearch.transport.TransportService$4.doRun(TransportService
.java:376)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(Abstrac
tRunnable.java:37)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.common.compress.NotXContentException: Compressor de
tection can only be called on some xcontent bytes or compressed xcontent bytes
        at org.elasticsearch.common.compress.CompressorFactory.compressor(Compre
ssorFactory.java:85)
        at org.elasticsearch.common.xcontent.XContentHelper.createParser(XConten
tHelper.java:50)
        at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentP
arser.java:90)
        ... 18 more

**Comment by dadoonet** [comment]
@neetubhatt It sounds like it's totally a different error. Could you:

* open another issue
* share your FSCrawler settings
* share the content of files which are failing: `style-slider`, `HR`, `Tricky Question_jpg_jpg`, `hrportal` and `test2`
* share the full logs of FSCrawler
* share the full logs of Elasticsearch
* Try with `--trace` option and share the full logs

Thanks!
