### ISSUE TITLE
Add filename in logs when an error occurs

### ISSUE THREAD

**Issue by lm-edi** [dadoonet/fscrawler#221]
Hello,

I'am using Fscrawler 2.1 and i made index on a directory with 13484 docs & folders, some errors appear but i don't see on which files and only 13469 are present in ElasticSeach ?
After, i add and delete some files and it work fine, but i would like to know if it is possible to have log file to see the differents actions and errors on files (i don't see in documentation).
Thank you very much for your answer.
Best regards,
Lionel

**Comment by dadoonet** [comment]
I think that debug mode could tell you more. Nothing in logs as warn?

**Comment by lm-edi** [comment]
Hello,
Thank you very much for your answer. I look with "debug" mode and effectively i see all the file which are indexed.
I have some "warn" like this "14:49:37,928 [33mWARN [m [o.a.p.p.f.PDSimpleFont] No Unicode mapping for 11 (1) in font RWYRVC+Wingdings", but it seem not important.

For the errors i find some different group of problem like this :
.../...
14:49:51,349 ^[[36mDEBUG^[[m [f.p.e.c.f.u.FsCrawlerUtil] filename = [8178_CV_-_Sam.pdf], includes = [null], excludes = [null]
14:49:51,349 ^[[36mDEBUG^[[m [f.p.e.c.f.FsCrawlerImpl] [8178_CV_-_Sam.pdf] can be indexed: [true]
14:49:51,349 ^[[36mDEBUG^[[m [f.p.e.c.f.FsCrawlerImpl]   - file: 8178_CV_-_Sam.pdf
14:49:51,349 ^[[36mDEBUG^[[m [f.p.e.c.f.FsCrawlerImpl] fetching content from [/var/gdr_dups/documents/cand_coll/5085/],[8178_CV_-_Sam.pdf]
14:49:51,361 ^[[33mWARN ^[[m [o.a.p.p.f.PDFont] Invalid ToUnicode CMap in font RobotoSlab-Regular
14:49:51,364 ^[[33mWARN ^[[m [o.a.p.p.f.PDCIDFontType2] Could not read embedded TTF for font RobotoSlab-Regular
java.io.IOException: loca is mandatory
        at org.apache.fontbox.ttf.TTFParser.parseTables(TTFParser.java:206) ~[fontbox-2.0.1.jar:2.0.1]
        at org.apache.fontbox.ttf.TTFParser.parse(TTFParser.java:150) ~[fontbox-2.0.1.jar:2.0.1]
        at org.apache.fontbox.ttf.TTFParser.parse(TTFParser.java:106) ~[fontbox-2.0.1.jar:2.0.1]
        at org.apache.pdfbox.pdmodel.font.PDCIDFontType2.<init>(PDCIDFontType2.java:111) [pdfbox-2.0.1.jar:2.0.1]
        at org.apache.pdfbox.pdmodel.font.PDCIDFontType2.<init>(PDCIDFontType2.java:70) [pdfbox-2.0.1.jar:2.0.1]
        at org.apache.pdfbox.pdmodel.font.PDFontFactory.createDescendantFont(PDFontFactory.java:125) [pdfbox-2.0.1.jar:2.0.1]
        at org.apache.pdfbox.pdmodel.font.PDType0Font.<init>(PDType0Font.java:128) [pdfbox-2.0.1.jar:2.0.1]
        at org.apache.pdfbox.pdmodel.font.PDFontFactory.createFont(PDFontFactory.java:83) [pdfbox-2.0.1.jar:2.0.1]
        at org.apache.pdfbox.pdmodel.PDResources.getFont(PDResources.java:123) [pdfbox-2.0.1.jar:2.0.1]
        at org.apache.pdfbox.contentstream.operator.text.SetFontAndSize.process(SetFontAndSize.java:60) [pdfbox-2.0.1.jar:2.0.1]
        at org.apache.pdfbox.contentstream.PDFStreamEngine.processOperator(PDFStreamEngine.java:815) [pdfbox-2.0.1.jar:2.0.1]
        at org.apache.pdfbox.contentstream.PDFStreamEngine.processStreamOperators(PDFStreamEngine.java:472) [pdfbox-2.0.1.jar:2.0.1]
        at org.apache.pdfbox.contentstream.PDFStreamEngine.processStream(PDFStreamEngine.java:446) [pdfbox-2.0.1.jar:2.0.1]
        at org.apache.pdfbox.contentstream.PDFStreamEngine.processPage(PDFStreamEngine.java:149) [pdfbox-2.0.1.jar:2.0.1]
        at org.apache.pdfbox.text.PDFTextStreamEngine.processPage(PDFTextStreamEngine.java:136) [pdfbox-2.0.1.jar:2.0.1]
        at org.apache.pdfbox.text.PDFTextStripper.processPage(PDFTextStripper.java:391) [pdfbox-2.0.1.jar:2.0.1]
        at org.apache.tika.parser.pdf.PDF2XHTML.processPage(PDF2XHTML.java:214) [tika-parsers-1.13.jar:1.13]
        at org.apache.pdfbox.text.PDFTextStripper.processPages(PDFTextStripper.java:319) [pdfbox-2.0.1.jar:2.0.1]
        at org.apache.pdfbox.text.PDFTextStripper.writeText(PDFTextStripper.java:266) [pdfbox-2.0.1.jar:2.0.1]
        at org.apache.tika.parser.pdf.PDF2XHTML.process(PDF2XHTML.java:160) [tika-parsers-1.13.jar:1.13]
        at org.apache.tika.parser.pdf.PDFParser.parse(PDFParser.java:144) [tika-parsers-1.13.jar:1.13]
        at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280) [tika-core-1.13.jar:1.13]
        at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280) [tika-core-1.13.jar:1.13]
        at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:120) [tika-core-1.13.jar:1.13]
        at org.apache.tika.Tika.parseToString(Tika.java:568) [tika-core-1.13.jar:1.13]
        at fr.pilato.elasticsearch.crawler.fs.tika.TikaDocParser.generate(TikaDocParser.java:77) [fscrawler-2.1.jar:?]
        at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.indexFile(FsCrawlerImpl.java:608) [fscrawler-2.1.jar:?]
        at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.addFilesRecursively(FsCrawlerImpl.java:396) [fscrawler-2.1.jar:?]
        at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.addFilesRecursively(FsCrawlerImpl.java:406) [fscrawler-2.1.jar:?]
        at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.run(FsCrawlerImpl.java:298) [fscrawler-2.1.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
14:49:51,375 ^[[33mWARN ^[[m [o.a.p.p.f.PDCIDFontType2] Using fallback font LiberationSans for CID-keyed TrueType font RobotoSlab-Regular
.../...
or
.../...
14:49:54,603 [36mDEBUG[m [f.p.e.c.f.FsCrawlerImpl] [6543_DC_-__Ni.doc] can be indexed: [true]
14:49:54,603 [36mDEBUG[m [f.p.e.c.f.FsCrawlerImpl]   - file: 6543_DC_-__Ni.doc
14:49:54,603 [36mDEBUG[m [f.p.e.c.f.FsCrawlerImpl] fetching content from [/var/gdr_dups/documents/cand_coll/3903/],[6543_DC_-__Ni.doc]
14:49:54,637 [36mDEBUG[m [f.p.e.c.f.t.TikaDocParser] Failed to extract [100000] characters of text for [6543_DC_-__Ni.doc]
org.apache.tika.exception.TikaException: Unexpected RuntimeException from org.apache.tika.parser.microsoft.OfficeParser@78c0a445
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:282) ~[tika-core-1.13.jar:1.13]
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280) ~[tika-core-1.13.jar:1.13]
	at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:120) ~[tika-core-1.13.jar:1.13]
	at org.apache.tika.Tika.parseToString(Tika.java:568) ~[tika-core-1.13.jar:1.13]
	at fr.pilato.elasticsearch.crawler.fs.tika.TikaDocParser.generate(TikaDocParser.java:77) [fscrawler-2.1.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.indexFile(FsCrawlerImpl.java:608) [fscrawler-2.1.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.addFilesRecursively(FsCrawlerImpl.java:396) [fscrawler-2.1.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.addFilesRecursively(FsCrawlerImpl.java:406) [fscrawler-2.1.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.run(FsCrawlerImpl.java:298) [fscrawler-2.1.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.IllegalArgumentException: This paragraph is not the first one in the table
	at org.apache.poi.hwpf.usermodel.Range.getTable(Range.java:925) ~[poi-scratchpad-3.15-beta1.jar:3.15-beta1]
	at org.apache.tika.parser.microsoft.WordExtractor.handleParagraph(WordExtractor.java:241) ~[tika-parsers-1.13.jar:1.13]
	at org.apache.tika.parser.microsoft.WordExtractor.handleHeaderFooter(WordExtractor.java:226) ~[tika-parsers-1.13.jar:1.13]
	at org.apache.tika.parser.microsoft.WordExtractor.parse(WordExtractor.java:192) ~[tika-parsers-1.13.jar:1.13]
	at org.apache.tika.parser.microsoft.OfficeParser.parse(OfficeParser.java:146) ~[tika-parsers-1.13.jar:1.13]
	at org.apache.tika.parser.microsoft.OfficeParser.parse(OfficeParser.java:117) ~[tika-parsers-1.13.jar:1.13]
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280) ~[tika-core-1.13.jar:1.13]
	... 9 more
.../...

But i don't know what is it exactly ?

Thank you for your help.
Lionel

**Comment by dadoonet** [comment]
Looks like a Tika issue. Could you share the file which is causing this trace? May be a bug to report to Tika team...

**Comment by dadoonet** [comment]
@lm-edi Any news?

**Comment by lm-edi** [comment]
Hello,

I am sorry to respond so late but i am currently on a lot of things.
I can't report anything to Tika team because the documents contain personnal informations. But in fact, it's not really the problem, if i can know the name of the files which  have errors.
In the normal mode, FsCrawler give only information that an error appear but not the name of the file (see below). In DEBUG or TRACE mode, too much informations are given and they can't be stored to find the name of the problematic files.
Have you any idea to find the names of the files which are on error during indexing ?
Thank you very much for you naswer.
Lionel

========================
18:35:15,609 ←[32mINFO ←[m [f.p.e.c.f.FsCrawlerImpl] Starting FS crawler
18:35:15,985 ←[32mINFO ←[m [f.p.e.c.f.FsCrawlerImpl] creating fs crawler thread [gdr] for [k:/cand_coll] every [3m]
18:36:25,152 ←[33mWARN ←[m [o.a.p.p.PDFStreamParser] ignoring 'EI' assumed to be in the middle of inline image
18:36:25,153 ←[33mWARN ←[m [o.a.p.p.PDFStreamParser] ignoring 'EI' assumed to be in the middle of inline image
18:36:59,181 ←[32mINFO ←[m [o.a.p.p.PDFParser] Document is encrypted
18:37:00,400 ←[32mINFO ←[m [o.a.p.p.PDFParser] Document is encrypted
18:37:20,952 ←[32mINFO ←[m [o.a.p.p.PDFParser] Document is encrypted
18:38:56,581 ←[1;31mERROR←[m [o.a.p.f.FlateFilter] FlateFilter: stop reading corrupt stream due to a DataFormatException
18:39:03,790 ←[33mWARN ←[m [o.a.p.p.PDFStreamParser] ignoring 'EI' assumed to be in the middle of inline image
18:39:03,792 ←[33mWARN ←[m [o.a.p.p.PDFStreamParser] ignoring 'EI' assumed to be in the middle of inline image
18:39:03,804 ←[33mWARN ←[m [o.a.p.p.PDFStreamParser] ignoring 'EI' assumed to be in the middle of inline image
18:39:03,831 ←[33mWARN ←[m [o.a.p.p.PDFStreamParser] ignoring 'EI' assumed to be in the middle of inline image
18:39:03,832 ←[33mWARN ←[m [o.a.p.p.PDFStreamParser] ignoring 'EI' assumed to be in the middle of inline image
18:39:03,833 ←[33mWARN ←[m [o.a.p.p.PDFStreamParser] ignoring 'EI' assumed to be in the middle of inline image
18:39:35,112 ←[32mINFO ←[m [o.a.p.p.PDFParser] Document is encrypted
18:39:52,906 ←[1;31mERROR←[m [o.a.p.p.f.PDFont] An error occurs while reading a CMap
java.io.IOException: Error : ~bfchar contains an unexpected operator : endcmap
        at org.apache.fontbox.cmap.CMapParser.parse(CMapParser.java:173) ~[fontbox-1.8.10.jar:1.8.10]
        at org.apache.pdfbox.pdmodel.font.PDFont.parseCmap(PDFont.java:626) [pdfbox-1.8.10.jar:1.8.10]
        at org.apache.pdfbox.pdmodel.font.PDSimpleFont.extractToUnicodeEncoding(PDSimpleFont.java:457) [pdfbox-1.8.10.jar:1.8.10]
        at org.apache.pdfbox.pdmodel.font.PDSimpleFont.determineEncoding(PDSimpleFont.java:411) [pdfbox-1.8.10.jar:1.8.10]
        at org.apache.pdfbox.pdmodel.font.PDFont.<init>(PDFont.java:214) [pdfbox-1.8.10.jar:1.8.10]
        at org.apache.pdfbox.pdmodel.font.PDSimpleFont.<init>(PDSimpleFont.java:89) [pdfbox-1.8.10.jar:1.8.10]
        at org.apache.pdfbox.pdmodel.font.PDType0Font.<init>(PDType0Font.java:67) [pdfbox-1.8.10.jar:1.8.10]
        at org.apache.pdfbox.pdmodel.font.PDFontFactory.createFont(PDFontFactory.java:108) [pdfbox-1.8.10.jar:1.8.10]
        at org.apache.pdfbox.pdmodel.PDResources.getFonts(PDResources.java:213) [pdfbox-1.8.10.jar:1.8.10]
        at org.apache.pdfbox.util.PDFStreamEngine.getFonts(PDFStreamEngine.java:607) [pdfbox-1.8.10.jar:1.8.10]
        at org.apache.pdfbox.util.operator.SetTextFont.process(SetTextFont.java:59) [pdfbox-1.8.10.jar:1.8.10]
        at org.apache.pdfbox.util.PDFStreamEngine.processOperator(PDFStreamEngine.java:557) [pdfbox-1.8.10.jar:1.8.10]
        at org.apache.pdfbox.util.PDFStreamEngine.processSubStream(PDFStreamEngine.java:268) [pdfbox-1.8.10.jar:1.8.10]
        at org.apache.pdfbox.util.PDFStreamEngine.processSubStream(PDFStreamEngine.java:235) [pdfbox-1.8.10.jar:1.8.10]
        at org.apache.pdfbox.util.PDFStreamEngine.processStream(PDFStreamEngine.java:215) [pdfbox-1.8.10.jar:1.8.10]
        at org.apache.pdfbox.util.PDFTextStripper.processPage(PDFTextStripper.java:458) [pdfbox-1.8.10.jar:1.8.10]
        at org.apache.pdfbox.util.PDFTextStripper.processPages(PDFTextStripper.java:383) [pdfbox-1.8.10.jar:1.8.10]
        at org.apache.pdfbox.util.PDFTextStripper.writeText(PDFTextStripper.java:342) [pdfbox-1.8.10.jar:1.8.10]
        at org.apache.tika.parser.pdf.PDF2XHTML.process(PDF2XHTML.java:141) [tika-parsers-1.10.jar:1.10]
        at org.apache.tika.parser.pdf.PDFParser.parse(PDFParser.java:148) [tika-parsers-1.10.jar:1.10]
        at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280) [tika-core-1.10.jar:1.10]
        at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280) [tika-core-1.10.jar:1.10]
        at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:120) [tika-core-1.10.jar:1.10]
        at org.apache.tika.Tika.parseToString(Tika.java:506) [tika-core-1.10.jar:1.10]
        at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.indexFile(FsCrawlerImpl.java:498) [fscrawler-2.0.0.jar:?]
        at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.addFilesRecursively(FsCrawlerImpl.java:308) [fscrawler-2.0.0.jar:?]
        at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.addFilesRecursively(FsCrawlerImpl.java:319) [fscrawler-2.0.0.jar:?]
        at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.run(FsCrawlerImpl.java:216) [fscrawler-2.0.0.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_92]
18:39:52,977 ←[1;31mERROR←[m [o.a.p.p.f.PDFont] An error occurs while reading a CMap
java.io.IOException: Error : ~bfchar contains an unexpected operator : endcmap
        at org.apache.fontbox.cmap.CMapParser.parse(CMapParser.java:173) ~[fontbox-1.8.10.jar:1.8.10]
        at org.apache.pdfbox.pdmodel.font.PDFont.parseCmap(PDFont.java:626) [pdfbox-1.8.10.jar:1.8.10]
        at org.apache.pdfbox.pdmodel.font.PDSimpleFont.extractToUnicodeEncoding(PDSimpleFont.java:457) [pdfbox-1.8.10.jar:1.8.10]
        at org.apache.pdfbox.pdmodel.font.PDSimpleFont.determineEncoding(PDSimpleFont.java:411) [pdfbox-1.8.10.jar:1.8.10]
        at org.apache.pdfbox.pdmodel.font.PDFont.<init>(PDFont.java:214) [pdfbox-1.8.10.jar:1.8.10]
        at org.apache.pdfbox.pdmodel.font.PDSimpleFont.<init>(PDSimpleFont.java:89) [pdfbox-1.8.10.jar:1.8.10]
        at org.apache.pdfbox.pdmodel.font.PDType0Font.<init>(PDType0Font.java:67) [pdfbox-1.8.10.jar:1.8.10]
        at org.apache.pdfbox.pdmodel.font.PDFontFactory.createFont(PDFontFactory.java:108) [pdfbox-1.8.10.jar:1.8.10]
        at org.apache.pdfbox.pdmodel.PDResources.getFonts(PDResources.java:213) [pdfbox-1.8.10.jar:1.8.10]

**Comment by dadoonet** [comment]
So there is sadly nothing I can do here unless I have a similar file even with no sensitive data on it.

**Comment by lm-edi** [comment]
Sorry, i'am not very clear in my question. I reformulate it.
When i run FsCrawler, i redirect "stdout" in a file : "bin/fscrawler lm >> traces"
and i look at the file ("traces") every day to see if some problem appear.
When i see a problem, actually i don't know on which file this problem appear because it's not write in my "traces" file. And in a first time i am interested to know the name.
I hope my question more clear.
Thank you very much,
Lionel

**Comment by dadoonet** [comment]
Got it. Thanks for the explanation. Reopening to add a better logging experience in such a case.

**Comment by dadoonet** [comment]
Could you share by any chance a failing document which I can reuse in a test? I can't reproduce for now as I don't have failing docs :) .

**Comment by lm-edi** [comment]
Actually i can't because personnal data are in the files, but this week i'll try to find one (or more) for you.

Otherwise , I seen that the documents which have an error are all indexed and present in  ElasticSearch data. But some others files are missing in ElasticSearch data (i don't know which ?), i have 8297 files under the directory that i give to FsCrawler and i have only 8283 docs in the ElasticSearch data.
All are readable, and i don't see error for others files. I'll try this week to list and sort all the different name to make a difference.
Have you any idea about this problem ?
Thank you very much,
Lionel

**Comment by dadoonet** [comment]
> Have you any idea about this problem ?

Well. It depends on the documents. For example, if you have a PDF document which is a scanned document then no text will be extracted by default from it as you have only images. That could explain what you are seeing. Can't tell more with a concrete example.

**Comment by dadoonet** [comment]
Well. You told me that you are seeing some errors when indexing. Can that explain the difference? I mean that you may be have 14 documents which have errors.

Note that some documents are ignored (those which contain `~` character). See https://github.com/dadoonet/fscrawler/blob/master/src/main/java/fr/pilato/elasticsearch/crawler/fs/util/FsCrawlerUtil.java#L176-L179

**Comment by lm-edi** [comment]
Yes of course, i think so. But it's not the same files ... I make a "diff" between filenames in file system directory and doc in ElasticSearch data.
I give you two files where i remove the personnal data but have always problems 
- doc1.pdf seem to be OK for FsCrawler but is not in the ElasticSearch data ?
- doc2.pdf have "java problem" but is present in the ElasticSearch data.

Ask me if you need more informations.
[BadFiles.zip](https://github.com/dadoonet/fscrawler/files/482193/BadFiles.zip)

**Comment by lm-edi** [comment]
Hello,
Do you find something about doc1.pdf ? Why it isn't in the ElasticSeach data ?
Lionel

**Comment by dadoonet** [comment]
No sorry. Traveling ATM.
May be next week.

**Comment by dadoonet** [comment]
Sorry for the looong delay.

I tried both documents on current FSCrawler 2.2 SNAPSHOT.
Note that I updated recently to Tika 1.14 so things might have changed.

When running tests I can see the documents:

```sh
curl "localhost:9200/index/_search?q=FORMATIONS&pretty"
```

gives

```json
{
  "took" : 3,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 2,
    "max_score" : 1.3787371,
    "hits" : [
      {
        "_index" : "fscrawler_test_all_documents",
        "_type" : "doc",
        "_id" : "f2ad4a551cad7bb7e0602b239c169a99",
        "_score" : 1.3787371,
        "_source" : {
          "path" : {
            "encoded" : "148e1f1ab45ae25b9bbb6fd0bd1abe5",
            "root" : "148e1f1ab45ae25b9bbb6fd0bd1abe5",
            "real" : "/var/folders/r_/r14sy86n2zb91jyz1ptb5b4w0000gn/T/junit2695287560280932713/resources/issue-221-doc2.pdf"
          },
          "file" : {
            "extension" : "pdf",
            "content_type" : "application/pdf",
            "last_modified" : "2016-12-22T18:16:35Z",
            "indexing_date" : "2016-12-22T18:16:38.096Z",
            "filesize" : 113398,
            "filename" : "issue-221-doc2.pdf",
            "url" : "file:///var/folders/r_/r14sy86n2zb91jyz1ptb5b4w0000gn/T/junit2695287560280932713/resources/issue-221-doc2.pdf"
          },
          "meta" : {
            "raw" : {
              "date" : "2016-09-19T14:29:37Z",
              "pdf:PDFVersion" : "1.7",
              "xmp:CreatorTool" : "HTML2PDF - TCPDF",
              "access_permission:modify_annotations" : "true",
              "access_permission:can_print_degraded" : "true",
              "dcterms:created" : "2016-06-21T10:13:04Z",
              "Last-Modified" : "2016-09-19T14:29:37Z",
              "dcterms:modified" : "2016-09-19T14:29:37Z",
              "dc:format" : "application/pdf; version=1.7",
              "xmpMM:DocumentID" : "uuid:d3ed4592-716e-43ae-a7da-edf8e3974c19",
              "Last-Save-Date" : "2016-09-19T14:29:37Z",
              "pdf:docinfo:creator_tool" : "HTML2PDF - TCPDF",
              "access_permission:fill_in_form" : "true",
              "pdf:docinfo:modified" : "2016-09-19T14:29:37Z",
              "meta:save-date" : "2016-09-19T14:29:37Z",
              "pdf:encrypted" : "false",
              "modified" : "2016-09-19T14:29:37Z",
              "Content-Type" : "application/pdf",
              "X-Parsed-By" : "org.apache.tika.parser.DefaultParser",
              "meta:creation-date" : "2016-06-21T10:13:04Z",
              "created" : "Tue Jun 21 14:13:04 RET 2016",
              "access_permission:extract_for_accessibility" : "true",
              "access_permission:assemble_document" : "true",
              "xmpTPg:NPages" : "2",
              "Creation-Date" : "2016-06-21T10:13:04Z",
              "access_permission:extract_content" : "true",
              "access_permission:can_print" : "true",
              "producer" : "TCPDF 5.0.002 (http://www.tcpdf.org) (TCPDF)",
              "access_permission:can_modify" : "true",
              "pdf:docinfo:producer" : "TCPDF 5.0.002 (http://www.tcpdf.org) (TCPDF)",
              "pdf:docinfo:created" : "2016-06-21T10:13:04Z"
            }
          },
          "content" : "\nPermis de conduire : 2\n\n \n\nEXPERIENCES\n\nmarchandise \n\nFORMATIONS\n\n QUALITY ACADEMY\n\n \n\n  DUT\n\n \n\n \n\n \n\n  Niveau Bac - Ecole de spécialité\n\n\n\nCOMPETENCES\n\n\n"
        }
      },
      {
        "_index" : "fscrawler_test_all_documents",
        "_type" : "doc",
        "_id" : "fec6cadb8de1f4928f5793fb93c2af3",
        "_score" : 0.53182393,
        "_source" : {
          "path" : {
            "encoded" : "148e1f1ab45ae25b9bbb6fd0bd1abe5",
            "root" : "148e1f1ab45ae25b9bbb6fd0bd1abe5",
            "real" : "/var/folders/r_/r14sy86n2zb91jyz1ptb5b4w0000gn/T/junit2695287560280932713/resources/issue-221-doc1.pdf"
          },
          "file" : {
            "extension" : "pdf",
            "content_type" : "application/pdf",
            "last_modified" : "2016-12-22T18:16:35Z",
            "indexing_date" : "2016-12-22T18:16:37.577Z",
            "filesize" : 10226,
            "filename" : "issue-221-doc1.pdf",
            "url" : "file:///var/folders/r_/r14sy86n2zb91jyz1ptb5b4w0000gn/T/junit2695287560280932713/resources/issue-221-doc1.pdf"
          },
          "meta" : {
            "author" : "Tidiane DIALLO",
            "title" : "Tidiane DIALLO – Ingénieur Recherche et dévelopement",
            "keywords" : [
              "Tidiane DIALLO",
              " curriculum vitæ",
              " resumé"
            ],
            "raw" : {
              "date" : "2016-09-20T09:38:56Z",
              "pdf:PDFVersion" : "1.6",
              "pdf:docinfo:title" : "Tidiane DIALLO – Ingénieur Recherche et dévelopement",
              "xmp:CreatorTool" : "LaTeX with 'moderncv' package",
              "access_permission:can_print_degraded" : "true",
              "subject" : "Resumé of Tidiane DIALLO",
              "dc:format" : "application/pdf; version=1.6",
              "pdf:docinfo:creator_tool" : "LaTeX with 'moderncv' package",
              "access_permission:fill_in_form" : "true",
              "pdf:encrypted" : "false",
              "dc:title" : "Tidiane DIALLO – Ingénieur Recherche et dévelopement",
              "modified" : "2016-09-20T09:38:56Z",
              "cp:subject" : "Resumé of Tidiane DIALLO",
              "pdf:docinfo:subject" : "Resumé of Tidiane DIALLO",
              "pdf:docinfo:creator" : "Tidiane DIALLO",
              "PTEX.Fullbanner" : "This is MiKTeX-pdfTeX 2.9.5496 (1.40.15)",
              "meta:author" : "Tidiane DIALLO",
              "trapped" : "False",
              "meta:creation-date" : "2015-04-30T10:51:49Z",
              "created" : "Thu Apr 30 14:51:49 RET 2015",
              "access_permission:extract_for_accessibility" : "true",
              "Creation-Date" : "2015-04-30T10:51:49Z",
              "Author" : "Tidiane DIALLO",
              "producer" : "pdfTeX-1.40.15",
              "pdf:docinfo:producer" : "pdfTeX-1.40.15",
              "dc:description" : "Resumé of Tidiane DIALLO",
              "Keywords" : "Tidiane DIALLO, curriculum vitæ, resumé",
              "access_permission:modify_annotations" : "true",
              "dc:creator" : "Tidiane DIALLO",
              "description" : "Resumé of Tidiane DIALLO",
              "dcterms:created" : "2015-04-30T10:51:49Z",
              "Last-Modified" : "2016-09-20T09:38:56Z",
              "dcterms:modified" : "2016-09-20T09:38:56Z",
              "title" : "Tidiane DIALLO – Ingénieur Recherche et dévelopement",
              "xmpMM:DocumentID" : "uuid:8f5f2254-0e30-4ee5-b237-f6f7475daccc",
              "Last-Save-Date" : "2016-09-20T09:38:56Z",
              "pdf:docinfo:keywords" : "Tidiane DIALLO, curriculum vitæ, resumé",
              "pdf:docinfo:modified" : "2016-09-20T09:38:56Z",
              "meta:save-date" : "2016-09-20T09:38:56Z",
              "pdf:docinfo:custom:PTEX.Fullbanner" : "This is MiKTeX-pdfTeX 2.9.5496 (1.40.15)",
              "Content-Type" : "application/pdf",
              "X-Parsed-By" : "org.apache.tika.parser.DefaultParser",
              "creator" : "Tidiane DIALLO",
              "dc:subject" : "Tidiane DIALLO, curriculum vitæ, resumé",
              "access_permission:assemble_document" : "true",
              "xmpTPg:NPages" : "2",
              "access_permission:extract_content" : "true",
              "access_permission:can_print" : "true",
              "pdf:docinfo:trapped" : "False",
              "meta:keyword" : "Tidiane DIALLO, curriculum vitæ, resumé",
              "access_permission:can_modify" : "true",
              "pdf:docinfo:created" : "2015-04-30T10:51:49Z"
            }
          },
          "content" : "\nmailto:diallo.a.t@gmail.com\nhttp://www.elisa-aerospace.fr\nhttp://www.elisa-aerospace.fr\nLionel\nTexte tapé à la machine\ncoucou\n\n\n\n\n\tFormations\n\tExpériences\n\tProjets d'étude\n\tCompétences\n\tLangues\n\tInformatique\n\n\tDivers\n\tAssociatif\n\tLoisirs\n\n\n\n\n"
        }
      }
    ]
  }
}
```

If you don't mind, I'm adding the 2 files you provided as a test case so I'm sure it never fails.
