### ISSUE TITLE
fscrawler doesn't exit after last run when --loop is specified

### ISSUE THREAD

**Issue by jberkenbilt** [dadoonet/fscrawler#266]
In the following session, after this:

```
./bin/fscrawler fa3a46bb81e475726bab9ff8127cf0dc3d784743 --loop 1
15:40:31,646 INFO  [f.p.e.c.f.FsCrawlerImpl] Starting FS crawler
15:40:32,672 INFO  [f.p.e.c.f.FsCrawlerImpl] FS crawler started for [fa3a46bb81e475726bab9ff8127cf0dc3d784743] for [.../_/14ee4c89bbef717e3a3d5d7bed8c95dee1d29d7e] every [30m]
15:41:11,449 INFO  [f.p.e.c.f.FsCrawlerImpl] FS crawler is stopping after 1 run
```

fscrawler does not exit. Here is my _settings.json (slightly sanitized):

```
{
  "name" : "fa3a46bb81e475726bab9ff8127cf0dc3d784743",
  "fs" : {
    "url" : ".../_/14ee4c89bbef717e3a3d5d7bed8c95dee1d29d7e",
    "includes": [
      "*.html"
    ],
    "update_rate" : "30m",
    "excludes" : null,
    "json_support" : false,
    "filename_as_id" : false,
    "add_filesize" : true,
    "remove_deleted" : true,
    "store_source" : false,
    "index_content" : true,
    "indexed_chars" : null,
    "attributes_support" : false,
    "raw_metadata" : true,
    "checksum" : null
  },
  "server" : null,
  "elasticsearch" : {
    "nodes" : [
      { "host" : "xxx.example.com", "port" : 443, "scheme" : "HTTPS" }
    ],
    "index" : "fa3a46bb81e475726bab9ff8127cf0dc3d784743",
    "type" : "doc",
    "bulk_size" : 100,
    "flush_interval" : "5s"
  }
}
```

I built fscrawler from source at commit cfde2a1edfa0ca71a03496df2cf822d12d65c021.

java -version says:
```
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
```

Thread dump (relatively unhelpful ):

```
Full thread dump Java HotSpot(TM) 64-Bit Server VM (25.45-b02 mixed mode):

"DestroyJavaVM" #24 prio=5 os_prio=0 tid=0x00007ffa6c00b800 nid=0x7ee6 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"pool-3-thread-1" #22 prio=5 os_prio=0 tid=0x00007ffa6cc40800 nid=0x7f12 waiting on condition [0x00007ffa4aa74000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x000000069f58ae28> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
        at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
        at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

"I/O dispatcher 8" #21 prio=5 os_prio=0 tid=0x00007ff9d40d6800 nid=0x7f0d runnable [0x00007ffa4b199000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
        at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
        at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
        - locked <0x0000000403e14c00> (a sun.nio.ch.Util$2)
        - locked <0x0000000403e14c10> (a java.util.Collections$UnmodifiableSet)
        - locked <0x0000000403e14bb8> (a sun.nio.ch.EPollSelectorImpl)
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:255)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
        at java.lang.Thread.run(Thread.java:745)

"I/O dispatcher 7" #20 prio=5 os_prio=0 tid=0x00007ff9d40d4800 nid=0x7f0c runnable [0x00007ffa4b29a000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
        at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
        at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
        - locked <0x0000000403e24608> (a sun.nio.ch.Util$2)
        - locked <0x0000000403e24618> (a java.util.Collections$UnmodifiableSet)
        - locked <0x0000000403e245c0> (a sun.nio.ch.EPollSelectorImpl)
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:255)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
        at java.lang.Thread.run(Thread.java:745)

"I/O dispatcher 6" #19 prio=5 os_prio=0 tid=0x00007ff9d40d3000 nid=0x7f0b runnable [0x00007ffa4b39b000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
        at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
        at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
        - locked <0x0000000403e1cc78> (a sun.nio.ch.Util$2)
        - locked <0x0000000403e1cc88> (a java.util.Collections$UnmodifiableSet)
        - locked <0x0000000403e1cc30> (a sun.nio.ch.EPollSelectorImpl)
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:255)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
        at java.lang.Thread.run(Thread.java:745)
 
"I/O dispatcher 5" #18 prio=5 os_prio=0 tid=0x00007ff9d40d1000 nid=0x7f0a runnable [0x00007ffa4b49c000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
        at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
        at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
        - locked <0x0000000403e2c5f0> (a sun.nio.ch.Util$2)
        - locked <0x0000000403e2c600> (a java.util.Collections$UnmodifiableSet)
        - locked <0x0000000403e2c5a8> (a sun.nio.ch.EPollSelectorImpl)
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:255)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
        at java.lang.Thread.run(Thread.java:745)
 
"I/O dispatcher 4" #17 prio=5 os_prio=0 tid=0x00007ff9d40cf800 nid=0x7f09 runnable [0x00007ffa4b59d000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
        at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
        at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
        - locked <0x0000000403e14e90> (a sun.nio.ch.Util$2)
        - locked <0x0000000403e14ea0> (a java.util.Collections$UnmodifiableSet)
        - locked <0x0000000403e14e48> (a sun.nio.ch.EPollSelectorImpl)
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:255)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
        at java.lang.Thread.run(Thread.java:745)
 
"I/O dispatcher 3" #16 prio=5 os_prio=0 tid=0x00007ff9d40ce000 nid=0x7f08 runnable [0x00007ffa4b69e000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
        at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
        at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
        - locked <0x0000000403e1d020> (a sun.nio.ch.Util$2)
        - locked <0x0000000403e1d030> (a java.util.Collections$UnmodifiableSet)
        - locked <0x0000000403e1cfd8> (a sun.nio.ch.EPollSelectorImpl)
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:255)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
        at java.lang.Thread.run(Thread.java:745)
 
"I/O dispatcher 2" #15 prio=5 os_prio=0 tid=0x00007ff9d40cc000 nid=0x7f07 runnable [0x00007ffa4b79f000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
        at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
        at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
        - locked <0x0000000403e2c880> (a sun.nio.ch.Util$2)
        - locked <0x0000000403e2c890> (a java.util.Collections$UnmodifiableSet)
        - locked <0x0000000403e2c838> (a sun.nio.ch.EPollSelectorImpl)
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:255)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
        at java.lang.Thread.run(Thread.java:745)
 
"I/O dispatcher 1" #14 prio=5 os_prio=0 tid=0x00007ff9d4001800 nid=0x7f06 runnable [0x00007ffa4b8a0000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
        at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
        at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
        - locked <0x0000000403e2ecd8> (a sun.nio.ch.Util$2)
        - locked <0x000000040427f608> (a java.util.Collections$UnmodifiableSet)
        - locked <0x00000004040e6a68> (a sun.nio.ch.EPollSelectorImpl)
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:255)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
        at java.lang.Thread.run(Thread.java:745)
 
"pool-2-thread-1" #13 prio=5 os_prio=0 tid=0x00007ffa6cc1d800 nid=0x7f05 runnable [0x00007ffa4b9a1000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
        at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
        at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
        - locked <0x0000000403e15558> (a sun.nio.ch.Util$2)
        - locked <0x0000000403e15568> (a java.util.Collections$UnmodifiableSet)
        - locked <0x0000000403e15510> (a sun.nio.ch.EPollSelectorImpl)
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:340)
        at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:192)
        at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64)
        at java.lang.Thread.run(Thread.java:745)
"Service Thread" #9 daemon prio=9 os_prio=0 tid=0x00007ffa6c21d800 nid=0x7ef7 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
 
"C1 CompilerThread3" #8 daemon prio=9 os_prio=0 tid=0x00007ffa6c210000 nid=0x7ef6 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
 
"C2 CompilerThread2" #7 daemon prio=9 os_prio=0 tid=0x00007ffa6c20e000 nid=0x7ef5 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
 
"C2 CompilerThread1" #6 daemon prio=9 os_prio=0 tid=0x00007ffa6c20c800 nid=0x7ef4 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
 
"C2 CompilerThread0" #5 daemon prio=9 os_prio=0 tid=0x00007ffa6c209800 nid=0x7ef3 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
 
"Signal Dispatcher" #4 daemon prio=9 os_prio=0 tid=0x00007ffa6c208000 nid=0x7ef2 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
 
"Finalizer" #3 daemon prio=8 os_prio=0 tid=0x00007ffa6c1cf800 nid=0x7ef1 in Object.wait() [0x00007ffa52209000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0x0000000403e1f4d8> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
        - locked <0x0000000403e1f4d8> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
        at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)
 
"Reference Handler" #2 daemon prio=10 os_prio=0 tid=0x00007ffa6c1cd800 nid=0x7ef0 in Object.wait() [0x00007ff9fe1ee000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0x0000000403e1f6f0> (a java.lang.ref.Reference$Lock)
        at java.lang.Object.wait(Object.java:502)
        at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:157)
        - locked <0x0000000403e1f6f0> (a java.lang.ref.Reference$Lock)
 
"VM Thread" os_prio=0 tid=0x00007ffa6c1c8800 nid=0x7eef runnable
 
"GC task thread#0 (ParallelGC)" os_prio=0 tid=0x00007ffa6c020800 nid=0x7ee7 runnable
 
"GC task thread#1 (ParallelGC)" os_prio=0 tid=0x00007ffa6c022800 nid=0x7ee8 runnable
 
"GC task thread#2 (ParallelGC)" os_prio=0 tid=0x00007ffa6c024000 nid=0x7ee9 runnable
 
"GC task thread#3 (ParallelGC)" os_prio=0 tid=0x00007ffa6c026000 nid=0x7eea runnable
 
"GC task thread#4 (ParallelGC)" os_prio=0 tid=0x00007ffa6c027800 nid=0x7eeb runnable
 
"GC task thread#5 (ParallelGC)" os_prio=0 tid=0x00007ffa6c029800 nid=0x7eec runnable
 
"GC task thread#6 (ParallelGC)" os_prio=0 tid=0x00007ffa6c02b000 nid=0x7eed runnable
 
"GC task thread#7 (ParallelGC)" os_prio=0 tid=0x00007ffa6c02d000 nid=0x7eee runnable
 
"VM Periodic Task Thread" os_prio=0 tid=0x00007ffa6c220000 nid=0x7ef8 waiting on condition
 
JNI global references: 339
 
Heap
 PSYoungGen      total 383488K, used 231300K [0x0000000681500000, 0x00000006a0f00000, 0x00000007c0000000)
  eden space 357376K, 57% used [0x0000000681500000,0x000000068dd74920,0x0000000697200000)
  from space 26112K, 99% used [0x000000069f580000,0x00000006a0eec7e0,0x00000006a0f00000)
  to   space 40448K, 0% used [0x000000069c000000,0x000000069c000000,0x000000069e780000)
 ParOldGen       total 443392K, used 15563K [0x0000000403e00000, 0x000000041ef00000, 0x0000000681500000)
  object space 443392K, 3% used [0x0000000403e00000,0x0000000404d32d58,0x000000041ef00000)
 Metaspace       used 22389K, capacity 22698K, committed 22960K, reserved 1069056K
  class space    used 2627K, capacity 2733K, committed 2816K, reserved 1048576K
```

**Comment by dadoonet** [comment]
Thank you for testing this SNAPSHOT version and reporting this issue!

I can indeed reproduce it. Will find the bug hopefully and fix.

**Comment by jberkenbilt** [comment]
Thanks! I verified that this fixes the issue for us.
