### ISSUE TITLE
Fix Invalid UTF-8 error (wrong encoding)

### ISSUE THREAD

**Issue by rgrativol** [dadoonet/fscrawler#269]
My pdfs are ANSI encoding. I´m getting a json_parse_exception ("Invalid UTF-8 middle byte XXXX").

Is there anyway to set the encode? 

15:52:51,795 [36mDEBUG[m [f.p.e.c.f.c.ElasticsearchClient] bulk response: BulkResponse{items=[BulkItemTopLevelResponse{index=BulkItemResponse{failed=false, index='strj', type='folder', id='f43935b133d25aaa615bcd7be2312bfc', opType=null, failureMessage='null'}, delete=null}, BulkItemTopLevelResponse{index=BulkItemResponse{failed=true, index='strj', type='doc', id='f92cd5abf3afc1b5278711e2f69f714', opType=null, failureMessage='{type=mapper_parsing_exception, reason=failed to parse [_source], caused_by={type=parse_exception, reason=Failed to parse content to map, caused_by={type=json_parse_exception, reason=Invalid UTF-8 middle byte 0x50
 at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@4d2ece98; line: 2, column: 48]}}}'}, delete=null}, BulkItemTopLevelResponse{index=BulkItemResponse{failed=true, index='strj', type='doc', id='13fd36125354f0cbd7f12a83e2afd929', opType=null, failureMessage='{type=mapper_parsing_exception, reason=failed to parse [_source], caused_by={type=parse_exception, reason=Failed to parse content to map, caused_by={type=json_parse_exception, reason=Invalid UTF-8 middle byte 0x72
 at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@2be257ff; line: 2, column: 22]}}}'}, delete=null}, BulkItemTopLevelResponse{index=BulkItemResponse{failed=true, index='strj', type='doc', id='a1693083151b7d831cc085aaafcd5e6a', opType=null, failureMessage='{type=mapper_parsing_exception, reason=failed to parse [_source], caused_by={type=parse_exception, reason=Failed to parse content to map, caused_by={type=json_parse_exception, reason=Invalid UTF-8 middle byte 0x72
 at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@e559806; line: 2, column: 22]}}}'}, delete=null}, BulkItemTopLevelResponse{index=BulkItemResponse{failed=true, index='strj', type='doc', id='82f88c53516c762c6eb28939227fba7f', opType=null, failureMessage='{type=mapper_parsing_exception, reason=failed to parse [_source], caused_by={type=parse_exception, reason=Failed to parse content to map, caused_by={type=json_parse_exception, reason=Invalid UTF-8 middle byte 0x72
 at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@9970686; line: 2, column: 22]}}}'}, delete=null}, BulkItemTopLevelResponse{index=BulkItemResponse{failed=true, index='strj', type='doc', id='27db7b9de846253cceae1b040512d', opType=null, failureMessage='{type=mapper_parsing_exception, reason=failed to parse [_source], caused_by={type=parse_exception, reason=Failed to parse content to map, caused_by={type=json_parse_exception, reason=Invalid UTF-8 middle byte 0x72
 at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@54b52659; line: 2, column: 22]}}}'}, delete=null}]}
15:52:51,795 [36mDEBUG[m [f.p.e.c.f.c.BulkProcessor] Executed bulk composed of 6 actions
15:52:51,799 [33mWARN [m [f.p.e.c.f.c.BulkProcessor] There was failures while executing bulk
java.lang.RuntimeException: strj/doc/f92cd5abf3afc1b5278711e2f69f714:null:{type=mapper_parsing_exception, reason=failed to parse [_source], caused_by={type=parse_exception, reason=Failed to parse content to map, caused_by={type=json_parse_exception, reason=Invalid UTF-8 middle byte 0x50
 at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@4d2ece98; line: 2, column: 48]}}}strj/doc/13fd36125354f0cbd7f12a83e2afd929:null:{type=mapper_parsing_exception, reason=failed to parse [_source], caused_by={type=parse_exception, reason=Failed to parse content to map, caused_by={type=json_parse_exception, reason=Invalid UTF-8 middle byte 0x72
 at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@2be257ff; line: 2, column: 22]}}}strj/doc/a1693083151b7d831cc085aaafcd5e6a:null:{type=mapper_parsing_exception, reason=failed to parse [_source], caused_by={type=parse_exception, reason=Failed to parse content to map, caused_by={type=json_parse_exception, reason=Invalid UTF-8 middle byte 0x72
 at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@e559806; line: 2, column: 22]}}}strj/doc/82f88c53516c762c6eb28939227fba7f:null:{type=mapper_parsing_exception, reason=failed to parse [_source], caused_by={type=parse_exception, reason=Failed to parse content to map, caused_by={type=json_parse_exception, reason=Invalid UTF-8 middle byte 0x72
 at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@9970686; line: 2, column: 22]}}}strj/doc/27db7b9de846253cceae1b040512d:null:{type=mapper_parsing_exception, reason=failed to parse [_source], caused_by={type=parse_exception, reason=Failed to parse content to map, caused_by={type=json_parse_exception, reason=Invalid UTF-8 middle byte 0x72
 at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@54b52659; line: 2, column: 22]}}}
5 failures
        at fr.pilato.elasticsearch.crawler.fs.client.BulkResponse.buildFailureMessage(BulkResponse.java:73) ~[fscrawler-2.2-SNAPSHOT.jar:?]
        at fr.pilato.elasticsearch.crawler.fs.client.BulkProcessor$1.afterBulk(BulkProcessor.java:235) ~[fscrawler-2.2-SNAPSHOT.jar:?]
        at fr.pilato.elasticsearch.crawler.fs.client.BulkProcessor.execute(BulkProcessor.java:159) ~[fscrawler-2.2-SNAPSHOT.jar:?]
        at fr.pilato.elasticsearch.crawler.fs.client.BulkProcessor.executeWhenNeeded(BulkProcessor.java:144) ~[fscrawler-2.2-SNAPSHOT.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_111]
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [?:1.8.0_111]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source) [?:1.8.0_111]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_111]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
15:52:51,805 [36mDEBUG[m [f.p.e.c.f.c.BulkProcessor] Error for strj/doc/f92cd5abf3afc1b5278711e2f69f714 for null operation: {type=mapper_parsing_exception, reason=failed to parse [_source], caused_by={type=parse_exception, reason=Failed to parse content to map, caused_by={type=json_parse_exception, reason=Invalid UTF-8 middle byte 0x50
 at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@4d2ece98; line: 2, column: 48]}}}
15:52:51,805 [36mDEBUG[m [f.p.e.c.f.c.BulkProcessor] Error for strj/doc/13fd36125354f0cbd7f12a83e2afd929 for null operation: {type=mapper_parsing_exception, reason=failed to parse [_source], caused_by={type=parse_exception, reason=Failed to parse content to map, caused_by={type=json_parse_exception, reason=Invalid UTF-8 middle byte 0x72
 at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@2be257ff; line: 2, column: 22]}}}
15:52:51,805 [36mDEBUG[m [f.p.e.c.f.c.BulkProcessor] Error for strj/doc/a1693083151b7d831cc085aaafcd5e6a for null operation: {type=mapper_parsing_exception, reason=failed to parse [_source], caused_by={type=parse_exception, reason=Failed to parse content to map, caused_by={type=json_parse_exception, reason=Invalid UTF-8 middle byte 0x72
 at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@e559806; line: 2, column: 22]}}}
15:52:51,806 [36mDEBUG[m [f.p.e.c.f.c.BulkProcessor] Error for strj/doc/82f88c53516c762c6eb28939227fba7f for null operation: {type=mapper_parsing_exception, reason=failed to parse [_source], caused_by={type=parse_exception, reason=Failed to parse content to map, caused_by={type=json_parse_exception, reason=Invalid UTF-8 middle byte 0x72
 at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@9970686; line: 2, column: 22]}}}
15:52:51,806 [36mDEBUG[m [f.p.e.c.f.c.BulkProcessor] Error for strj/doc/27db7b9de846253cceae1b040512d for null operation: {type=mapper_parsing_exception, reason=failed to parse [_source], caused_by={type=parse_exception, reason=Failed to parse content to map, caused_by={type=json_parse_exception, reason=Invalid UTF-8 middle byte 0x72
 at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@54b52659; line: 2, column: 22]}}}
15:53:13,734 [36mDEBUG[m [f.p.e.c.f.FsCrawlerImpl] Closing FS crawler [strj]
15:53:13,734 [36mDEBUG[m [f.p.e.c.f.FsCrawlerImpl] FS crawler thread is still running
15:53:13,734 [36mDEBUG[m [f.p.e.c.f.FsCrawlerImpl] Fs crawler is now waking up again...

Thanks.

**Comment by dadoonet** [comment]
Is it possible to share a file which is causing this issue? If so can I reuse it within a test case?

**Comment by rgrativol** [comment]
Yes! I attached it so you can see. Is ANSI.
[D.O._23-12-2015.pdf](https://github.com/dadoonet/fscrawler/files/706799/D.O._23-12-2015.pdf)

**Comment by dadoonet** [comment]
So I tested your document on my side and it seems to work well (in a unit test at least).

I suspect that your JVM is not running using UTF8 encoding.
Do you have specific java options on your machine?

**Comment by rgrativol** [comment]
I´m using the default java optio,. I will check if it´s not UTF-8 and try again! Thanks

**Comment by dadoonet** [comment]
I think this is something I probably must fix on my end.

Could you start again with the same file but with `--trace` option and share the full log file either here or as a gist?

Thanks!

**Comment by rgrativol** [comment]
11:25:42,097 [36mDEBUG[m [f.p.e.c.f.c.ElasticsearchClient] bulk response: BulkResponse{items=[BulkItemTopLevelResponse{index=BulkItemResponse{failed=true, index='djrj', type='folder', id='4e36cbbb43c1206818539b7636875c', opType=null, failureMessage='{type=mapper_parsing_exception, reason=failed to parse [real], caused_by={type=json_parse_exception, reason=Invalid UTF-8 middle byte 0x65
 at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@10dc51d9; line: 4, column: 23]}}'}, delete=null}, BulkItemTopLevelResponse{index=BulkItemResponse{failed=true, index='djrj', type='doc', id='9c94533c3a439a591340b731304af7a3', opType=null, failureMessage='{type=mapper_parsing_exception, reason=failed to parse [_source], caused_by={type=parse_exception, reason=Failed to parse content to map, caused_by={type=json_parse_exception, reason=Invalid UTF-8 middle byte 0x50
 at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@3c5b74e1; line: 2, column: 48]}}}'}, delete=null}]}
11:25:42,097 [36mDEBUG[m [f.p.e.c.f.c.BulkProcessor] Executed bulk composed of 2 actions
11:25:42,099 [33mWARN [m [f.p.e.c.f.c.BulkProcessor] There was failures while executing bulk
java.lang.RuntimeException: djrj/folder/4e36cbbb43c1206818539b7636875c:null:{type=mapper_parsing_exception, reason=failed to parse [real], caused_by={type=json_parse_exception, reason=Invalid UTF-8 middle byte 0x65
 at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@10dc51d9; line: 4, column: 23]}}djrj/doc/9c94533c3a439a591340b731304af7a3:null:{type=mapper_parsing_exception, reason=failed to parse [_source], caused_by={type=parse_exception, reason=Failed to parse content to map, caused_by={type=json_parse_exception, reason=Invalid UTF-8 middle byte 0x50
 at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@3c5b74e1; line: 2, column: 48]}}}
2 failures
        at fr.pilato.elasticsearch.crawler.fs.client.BulkResponse.buildFailureMessage(BulkResponse.java:73) ~[fscrawler-2.2-SNAPSHOT.jar:?]
        at fr.pilato.elasticsearch.crawler.fs.client.BulkProcessor$1.afterBulk(BulkProcessor.java:235) ~[fscrawler-2.2-SNAPSHOT.jar:?]
        at fr.pilato.elasticsearch.crawler.fs.client.BulkProcessor.execute(BulkProcessor.java:159) ~[fscrawler-2.2-SNAPSHOT.jar:?]
        at fr.pilato.elasticsearch.crawler.fs.client.BulkProcessor.executeWhenNeeded(BulkProcessor.java:144) ~[fscrawler-2.2-SNAPSHOT.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_111]
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [?:1.8.0_111]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source) [?:1.8.0_111]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_111]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
11:25:42,101 [36mDEBUG[m [f.p.e.c.f.c.BulkProcessor] Error for djrj/folder/4e36cbbb43c1206818539b7636875c for null operation: {type=mapper_parsing_exception, reason=failed to parse [real], caused_by={type=json_parse_exception, reason=Invalid UTF-8 middle byte 0x65
 at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@10dc51d9; line: 4, column: 23]}}
11:25:42,101 [36mDEBUG[m [f.p.e.c.f.c.BulkProcessor] Error for djrj/doc/9c94533c3a439a591340b731304af7a3 for null operation: {type=mapper_parsing_exception, reason=failed to parse [_source], caused_by={type=parse_exception, reason=Failed to parse content to map, caused_by={type=json_parse_exception, reason=Invalid UTF-8 middle byte 0x50
 at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@3c5b74e1; line: 2, column: 48]}}}
11:25:58,687 [36mDEBUG[m [f.p.e.c.f.FsCrawlerImpl] Closing FS crawler [djrj]
11:25:58,688 [36mDEBUG[m [f.p.e.c.f.FsCrawlerImpl] FS crawler thread is still running
11:25:58,688 [36mDEBUG[m [f.p.e.c.f.FsCrawlerImpl] Fs crawler is now waking up again...
11:25:58,691 [36mDEBUG[m [f.p.e.c.f.FsCrawlerImpl] FS crawler thread [djrj] is now marked as closed...

**Comment by rgrativol** [comment]
And it from ElasticSearch Server:

ivedFrom:DocumentID" : "xmp.did:bcdacc03-5d9d-8640-bfa9-3adbd1da      "xmpMM:DerivedFrom:InstanceID" : "xmp.iid:bcdacc03-5d9d-8640-bfa9-3adbd1da}]} "real" : "E:\\Leiloes\\djrj_2016_ate_16_1_2017\\D.O._23-12-2015.pdf"5.pdf"
org.elasticsearch.index.mapper.MapperParsingException: failed to parse [_source]
        at org.elasticsearch.index.mapper.FieldMapper.parse(FieldMapper.java:297) ~[elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.index.mapper.SourceFieldMapper.preParse(SourceFieldMapper.java:220) ~[elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.index.mapper.DocumentParser.internalParseDocument(DocumentParser.java:86) ~[elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentParser.java:66) ~[elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:275) ~[elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.index.shard.IndexShard.prepareIndex(IndexShard.java:533) ~[elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.index.shard.IndexShard.prepareIndexOnPrimary(IndexShard.java:510) ~[elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.action.index.TransportIndexAction.prepareIndexOperationOnPrimary(TransportIndexAction.java:174) ~[elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.action.index.TransportIndexAction.executeIndexRequestOnPrimary(TransportIndexAction.java:179) ~[elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardIndexOperation(TransportShardBulkAction.java:348) [elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.action.bulk.TransportShardBulkAction.index(TransportShardBulkAction.java:155) [elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.action.bulk.TransportShardBulkAction.handleItem(TransportShardBulkAction.java:134) [elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.action.bulk.TransportShardBulkAction.onPrimaryShard(TransportShardBulkAction.java:120) [elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.action.bulk.TransportShardBulkAction.onPrimaryShard(TransportShardBulkAction.java:73) [elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.action.support.replication.TransportWriteAction.shardOperationOnPrimary(TransportWriteAction.java:75) [elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.action.support.replication.TransportWriteAction.shardOperationOnPrimary(TransportWriteAction.java:48) [elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:905) [elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:875) [elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.action.support.replication.ReplicationOperation.execute(ReplicationOperation.java:113) [elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.onResponse(TransportReplicationAction.java:323) [elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.onResponse(TransportReplicationAction.java:258) [elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$1.onResponse(TransportReplicationAction.java:855) [elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$1.onResponse(TransportReplicationAction.java:852) [elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.index.shard.IndexShardOperationsLock.acquire(IndexShardOperationsLock.java:142) [elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.index.shard.IndexShard.acquirePrimaryOperationLock(IndexShard.java:1648) [elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.action.support.replication.TransportReplicationAction.acquirePrimaryShardReference(TransportReplicationAction.java:864) [elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.action.support.replication.TransportReplicationAction.access$400(TransportReplicationAction.java:90) [elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.doRun(TransportReplicationAction.java:275) [elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:254) [elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:246) [elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) [elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.transport.TransportService$6.doRun(TransportService.java:577) [elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:527) [elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-5.1.2.jar:5.1.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_111]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: org.elasticsearch.ElasticsearchParseException: Failed to parse content to map
        at org.elasticsearch.common.xcontent.XContentHelper.convertToMap(XContentHelper.java:85) ~[elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.index.mapper.SourceFieldMapper.parseCreateField(SourceFieldMapper.java:249) ~[elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.index.mapper.FieldMapper.parse(FieldMapper.java:286) ~[elasticsearch-5.1.2.jar:5.1.2]
        ... 37 more
Caused by: com.fasterxml.jackson.core.JsonParseException: Invalid UTF-8 middle byte 0x50
 at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@653f2ac7; line: 2, column: 48]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1702) ~[jackson-core-2.8.1.jar:2.8.1]
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:558) ~[jackson-core-2.8.1.jar:2.8.1]
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidOther(UTF8StreamJsonParser.java:3548) ~[jackson-core-2.8.1.jar:2.8.1]
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidOther(UTF8StreamJsonParser.java:3555) ~[jackson-core-2.8.1.jar:2.8.1]
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._decodeUtf8_2(UTF8StreamJsonParser.java:3329) ~[jackson-core-2.8.1.jar:2.8.1]
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._finishString2(UTF8StreamJsonParser.java:2513) ~[jackson-core-2.8.1.jar:2.8.1]
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._finishAndReturnString(UTF8StreamJsonParser.java:2465) ~[jackson-core-2.8.1.jar:2.8.1]
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.getText(UTF8StreamJsonParser.java:315) ~[jackson-core-2.8.1.jar:2.8.1]
        at org.elasticsearch.common.xcontent.json.JsonXContentParser.text(JsonXContentParser.java:83) ~[elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readValue(AbstractXContentParser.java:347) ~[elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readMap(AbstractXContentParser.java:295) ~[elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readOrderedMap(AbstractXContentParser.java:262) ~[elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.mapOrdered(AbstractXContentParser.java:218) ~[elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.common.xcontent.XContentHelper.convertToMap(XContentHelper.java:79) ~[elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.index.mapper.SourceFieldMapper.parseCreateField(SourceFieldMapper.java:249) ~[elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.index.mapper.FieldMapper.parse(FieldMapper.java:286) ~[elasticsearch-5.1.2.jar:5.1.2]
        ... 37 more

**Comment by rgrativol** [comment]
These are the two main messages:
Caused by: org.elasticsearch.ElasticsearchParseException: Failed to parse content to map
Caused by: com.fasterxml.jackson.core.JsonParseException: Invalid UTF-8 middle byte 0x50

**Comment by dadoonet** [comment]
But I was expecting more `TRACE` logs with `--trace` option happening before `11:25:42,097`. Can you get them?

**Comment by dadoonet** [comment]
I might have found where the issue is coming from.
Sometimes, I'm using `Charset.defaultCharset()` instead of forcing UTF8. That's probably the issue here.

I'll try to fix that, create a SNAPSHOT version you can then test to verify that all is good.

I'll update this thread.

**Comment by dadoonet** [comment]
So I pushed a change which I hope will fix your issue.
Have a look here: https://oss.sonatype.org/content/repositories/snapshots/fr/pilato/elasticsearch/crawler/fscrawler/2.2-SNAPSHOT/

And grab the latest SNAPSHOT available (any version after Wed Jan 18 20:00:00 should be ok)

**Comment by rgrativol** [comment]
Yes, it is fixed! Great! Thanks...

**Comment by dadoonet** [comment]
Awesome! Thanks for reporting and confirming!

**Comment by boindala** [comment]
Hi @dadoonet ,
Is this fixed carried into version "fscrawler-es7-2.7-SNAPSHOT"?

I faced a similar issue:
20:48:28,114 WARN  [f.p.e.c.f.FsParserAbstract] Error while crawling F:\hvr_copy: com.fasterxml.jackson.core.JsonParseException: Invalid UTF-8 middle byte 0xe3 (at char #10, byte #-1)

**Comment by dadoonet** [comment]
> Is this fixed carried into version "fscrawler-es7-2.7-SNAPSHOT"?

Yes.

> I faced a similar issue:

Could you open a new issue? If possible share your file.
Could you also run a test with this file only and with the `--trace` option?

**Comment by boindala** [comment]
Apologies, I will open a new request.

**Comment by dadoonet** [comment]
> Apologies, I will open a new request.

No need to apologize. I do appreciate a lot bug reports anywhere and more than that I appreciate so much when are first trying to find similar issues before asking. Thanks!
