### ISSUE TITLE
Java heap memory on 2.2-SNAPSHOT

### ISSUE THREAD

**Issue by ernestoarbitrio** [dadoonet/fscrawler#321]
I'm indexing tons of data (~20Tb) in a index (10Shards, 2replicas) on a cluster with ~96Gb RAM. After ~4GB (index occupation) i received  this error
```bash
Exception in thread "fs-crawler" java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Arrays.java:3332)
        at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:137)
        at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:121)
        at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:514)
        at java.lang.StringBuffer.append(StringBuffer.java:352)
        at java.util.regex.Matcher.appendReplacement(Matcher.java:888)
        at java.util.regex.Matcher.replaceAll(Matcher.java:955)
        at java.lang.String.replaceAll(String.java:2223)
        at fr.pilato.elasticsearch.crawler.fs.client.ElasticsearchClient.bulk(ElasticsearchClient.java:110)
        at fr.pilato.elasticsearch.crawler.fs.client.BulkProcessor.execute(BulkProcessor.java:137)
        at fr.pilato.elasticsearch.crawler.fs.client.BulkProcessor.executeIfNeeded(BulkProcessor.java:117)
        at fr.pilato.elasticsearch.crawler.fs.client.BulkProcessor.internalAdd(BulkProcessor.java:110)
        at fr.pilato.elasticsearch.crawler.fs.client.BulkProcessor.add(BulkProcessor.java:98)
        at fr.pilato.elasticsearch.crawler.fs.client.BulkProcessor.add(BulkProcessor.java:84)
        at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.esIndex(FsCrawlerImpl.java:723)
        at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.esIndex(FsCrawlerImpl.java:707)
        at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.indexFile(FsCrawlerImpl.java:605)
        at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.addFilesRecursively(FsCrawlerImpl.java:400)
        at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.addFilesRecursively(FsCrawlerImpl.java:410)
        at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.addFilesRecursively(FsCrawlerImpl.java:410)
        at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.addFilesRecursively(FsCrawlerImpl.java:410)
        at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.addFilesRecursively(FsCrawlerImpl.java:410)
        at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.addFilesRecursively(FsCrawlerImpl.java:410)
        at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.addFilesRecursively(FsCrawlerImpl.java:410)
        at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.addFilesRecursively(FsCrawlerImpl.java:410)
        at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.addFilesRecursively(FsCrawlerImpl.java:410)
        at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.addFilesRecursively(FsCrawlerImpl.java:410)
        at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.addFilesRecursively(FsCrawlerImpl.java:410)
        at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.addFilesRecursively(FsCrawlerImpl.java:410)
        at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.addFilesRecursively(FsCrawlerImpl.java:410)
        at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.run(FsCrawlerImpl.java:287)
        at java.lang.Thread.run(Thread.java:745)
```

This is my settings

```json
{
  "name" : "celvin",
  "fs" : {
    "url" : "/pmed2/data/celvin",
    "update_rate" : "5s",
    "includes" : ["*.*"],
    "excludes": ["*.db", "*.dll", "*.ini", "*.exe", "*.bat", "*.drv", "*.sys", "*.cab", "*.7z", "*.sav", "*.ctx", "*.upd"],
    "json_support" : false,
    "filename_as_id" : false,
    "add_filesize" : true,
    "remove_deleted" : true,
    "store_source" : false,
    "indexed_chars" : "-1",
    "index_content" : true
  },
  "elasticsearch" : {
    "nodes" : [ {
      "host" : "127.0.0.1",
      "port" : 9200
    } ],
    "index": "celvin",
    "type" : "doc",
    "bulk_size" : 100,
    "flush_interval" : "5s"
  }
}
```

Any suggestion?

Thanks 

e.

**Comment by dadoonet** [comment]
Can you try to give more HEAP to FSCrawler with this setting? https://github.com/dadoonet/fscrawler#jvm-settings

**Comment by ernestoarbitrio** [comment]
I tried with FS_JAVA_OPTS="-Xmx85021m -Xms5210m" bin/fscrawler; it works fine for more time but then ...
```bash
Exception in thread "fs-crawler" java.lang.OutOfMemoryError: heap allocation failed
        at java.io.UnixFileSystem.list(Native Method)
        at java.io.File.list(File.java:1122)
        at java.io.File.listFiles(File.java:1207)
        at fr.pilato.elasticsearch.crawler.fs.fileabstractor.FileAbstractorFile.getFiles(FileAbstractorFile.java:63)
        at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.addFilesRecursively(FsCrawlerImpl.java:375)
        at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.addFilesRecursively(FsCrawlerImpl.java:410)
        at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.addFilesRecursively(FsCrawlerImpl.java:410)
        at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.addFilesRecursively(FsCrawlerImpl.java:410)
        at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.addFilesRecursively(FsCrawlerImpl.java:410)
        at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.addFilesRecursively(FsCrawlerImpl.java:410)
        at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.addFilesRecursively(FsCrawlerImpl.java:410)
        at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.addFilesRecursively(FsCrawlerImpl.java:410)
        at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.addFilesRecursively(FsCrawlerImpl.java:410)
        at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.addFilesRecursively(FsCrawlerImpl.java:410)
        at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.addFilesRecursively(FsCrawlerImpl.java:410)
        at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.addFilesRecursively(FsCrawlerImpl.java:410)
        at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.addFilesRecursively(FsCrawlerImpl.java:410)
        at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.run(FsCrawlerImpl.java:287)
        at java.lang.Thread.run(Thread.java:745)
```

Where i'm wrong?

Thnaks

**Comment by dadoonet** [comment]
Did you really mean `FS_JAVA_OPTS="-Xmx85021m -Xms5210m"`?

Can you try with same size for both Xms/Xmx settings?
Also what is the version you are using? Can you download 2.2 final version although I don't believe it will fix that issue.

I never tested FSCrawler under a bug volume like this but definitely I should try to diagnose how memory is working under such load. I guess there is a memory leak somewhere in the code.

I wonder if crawling the FS with an external process like "ls -R" and then send each file to FSCrawler in REST mode would avoid such a situation. Is this something you could try?

To start FSCrawler as a REST service, run:

```sh
bin/fscrawler celvin --loop 0 --rest
```

To send a single file to the REST API, run:

```sh
curl -F "file=@test.txt" "http://127.0.0.1:8080/fscrawler/_upload"
```

Thanks!

**Comment by ernestoarbitrio** [comment]
Oh, ok thanks.
For first i will try to set the same size for xmx and xms.
For using REST mode the problem is that i've too much files to parse... but yes i will try it if i cannot solve my problem with classical approach

Thank you again for your willingness.

I will update you on this issue!

**Comment by dadoonet** [comment]
@ernestoarbitrio Any further news on this issue?

**Comment by ernestoarbitrio** [comment]
oh, sorry @dadoonet I forgot to answer. I tried with your hint and with REST mode I fix my problems. Thanks !

**Comment by TheReal1604** [comment]
@ernestoarbitrio And which one solved your issue? :-)
