### ISSUE TITLE
Indexing Json document via bulk indexing folders also

### ISSUE THREAD

**Issue by Spandana-Sai** [dadoonet/fscrawler#327]
I had `settings.json` is as follows.It's trying to index folders too. i want to index only json files. Can anyone please help me out. Is my settings is suffice. 

```json
 "fs" : {
    "url": "/tmp/es",
    "update_rate" : "15m",
    "includes": [ "*.json" ],
    "add_as_inner_object": true,
    "json_support" : true,
    "filename_as_id" : true,
    "add_filesize" : true,
    "remove_deleted" : true,
    "store_source" : false,
    "index_content" : true,
    "indexed_chars": "100%",
    "attributes_support" : false,
    "raw_metadata" : true,
    "xml_support" : false,
    "ignore_folders": true,
    "index_content": true,
    "lang_detect" : false
  },
```

**Comment by dadoonet** [comment]
What do you have in `/tmp/es` dir?
How do you start fscrawler?
Can you add `--debug` to the command line?
And share your logs?

**Comment by Spandana-Sai** [comment]
@dadoonet /tmp/es contains some pdf files, folders (inside folders, we have .java files, .xml files). I dont want to index folders and even inside its files.
bin/fscrawler job_name --restart --debug as want to reindex existing documents
logs 
`16:54:57,358 DEBUG [f.p.e.c.f.FsCrawlerImpl] Indexing in ES job_name, folder, 6736f4fda88a13d67e5435fb1218f653
16:54:57,358 DEBUG [f.p.e.c.f.c.BulkProcessor] {"index":{"_index":"job_name","_type":"folder","_id":"6736f4fda88a13d67e5435fb1218f653"}}
16:54:57,358 DEBUG [f.p.e.c.f.c.BulkProcessor] Going to execute new bulk composed of 1 actions
16:54:57,522 DEBUG [f.p.e.c.f.c.ElasticsearchClient] bulk response: BulkResponse{items=[BulkItemTopLevelResponse{index=BulkItemResponse{failed=false, index='job_name', type='folder', id='6736f4fda88a13d67e5435fb1218f653', opType=null, failureMessage='null'}, delete=null}]}
16:54:57,522 DEBUG [f.p.e.c.f.c.BulkProcessor] Executed bulk composed of 1 actions
`

**Comment by dadoonet** [comment]
Is this all the logs you have?

So let's try with `--trace` instead of debug?

**Comment by dadoonet** [comment]
Ping. Any new logs?

**Comment by Quix0r** [comment]
I cannot index even JPEGs or PDFs, elasticsearch says:
````
[2017-06-14T17:20:01,619][DEBUG][o.e.a.b.TransportShardBulkAction] [node-master] [school][0] failed to execute bulk item (index) BulkShardRequest [[school][0]] containing [index {[school][doc][a569229d27f6047b22f9385ae4cdde5], source[_na_]}]
org.elasticsearch.index.mapper.MapperParsingException: failed to parse
        at org.elasticsearch.index.mapper.DocumentParser.wrapInMapperParsingException(DocumentParser.java:176) ~[elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentParser.java:69) ~[elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:277) ~[elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.index.shard.IndexShard.prepareIndex(IndexShard.java:536) ~[elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.index.shard.IndexShard.prepareIndexOnPrimary(IndexShard.java:513) ~[elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.action.bulk.TransportShardBulkAction.prepareIndexOperationOnPrimary(TransportShardBulkAction.java:450) ~[elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.action.bulk.TransportShardBulkAction.executeIndexRequestOnPrimary(TransportShardBulkAction.java:458) ~[elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.action.bulk.TransportShardBulkAction.executeBulkItemRequest(TransportShardBulkAction.java:143) [elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:113) [elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:69) [elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:939) [elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:908) [elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.action.support.replication.ReplicationOperation.execute(ReplicationOperation.java:113) [elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.onResponse(TransportReplicationAction.java:322) [elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.onResponse(TransportReplicationAction.java:264) [elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$1.onResponse(TransportReplicationAction.java:888) [elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$1.onResponse(TransportReplicationAction.java:885) [elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.index.shard.IndexShardOperationsLock.acquire(IndexShardOperationsLock.java:147) [elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.index.shard.IndexShard.acquirePrimaryOperationLock(IndexShard.java:1656) [elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.action.support.replication.TransportReplicationAction.acquirePrimaryShardReference(TransportReplicationAction.java:897) [elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.action.support.replication.TransportReplicationAction.access$400(TransportReplicationAction.java:93) [elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.doRun(TransportReplicationAction.java:281) [elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:260) [elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:252) [elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) [elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:627) [elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:638) [elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-5.4.1.jar:5.4.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_131]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: org.elasticsearch.common.compress.NotXContentException: Compressor detection can only be called on some xcontent bytes or compressed xcontent bytes
        at org.elasticsearch.common.compress.CompressorFactory.compressor(CompressorFactory.java:58) ~[elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.common.xcontent.XContentHelper.createParser(XContentHelper.java:53) ~[elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentParser.java:62) ~[elasticsearch-5.4.1.jar:5.4.1]
        ... 30 more
````

**Comment by Quix0r** [comment]
See trace.log versus EL 5.4.1 (official download):
https://cloud.mxchange.org/index.php/s/149vSQYmDeENiuY/download?path=%2Ffscrawler-2.3-snapshot&files=trace.log.bz2

**Comment by Quix0r** [comment]
Normal startup logfile shows that ingest-attachment is being loaded:
````
[2017-06-14T17:36:27,499][INFO ][o.e.n.Node               ] [node-master] initializing ...
[2017-06-14T17:36:27,571][INFO ][o.e.e.NodeEnvironment    ] [node-master] using [1] data paths, mounts [[System (C:)]], net usable_space [152.9gb], net total_space [237.9gb], spins? [unknown], types [NTFS]
[2017-06-14T17:36:27,576][INFO ][o.e.e.NodeEnvironment    ] [node-master] heap size [1.9gb], compressed ordinary object pointers [true]
[2017-06-14T17:36:27,663][INFO ][o.e.n.Node               ] [node-master] node name [node-master], node ID [u3QZbpwHTu62bsHLlGJeuQ]
[2017-06-14T17:36:27,665][INFO ][o.e.n.Node               ] [node-master] version[5.4.1], pid[28372], build[2cfe0df/2017-05-29T16:05:51.443Z], OS[Windows 10/10.0/amd64], JVM[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/1.8.0_131/25.131-b11]
[2017-06-14T17:36:27,672][INFO ][o.e.n.Node               ] [node-master] JVM arguments [-Xms2g, -Xmx2g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -XX:+DisableExplicitGC, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -Djdk.io.permissionsUseCanonicalPath=true, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Dlog4j.skipJansi=true, -XX:+HeapDumpOnOutOfMemoryError, -Djava.awt.headless=true, -Delasticsearch, -Des.path.home=C:\Users\Dave\Downloads\elasticsearch-5.4.1]
[2017-06-14T17:36:28,699][INFO ][o.e.p.PluginsService     ] [node-master] loaded module [aggs-matrix-stats]
[2017-06-14T17:36:28,702][INFO ][o.e.p.PluginsService     ] [node-master] loaded module [ingest-common]
[2017-06-14T17:36:28,705][INFO ][o.e.p.PluginsService     ] [node-master] loaded module [lang-expression]
[2017-06-14T17:36:28,708][INFO ][o.e.p.PluginsService     ] [node-master] loaded module [lang-groovy]
[2017-06-14T17:36:28,711][INFO ][o.e.p.PluginsService     ] [node-master] loaded module [lang-mustache]
[2017-06-14T17:36:28,714][INFO ][o.e.p.PluginsService     ] [node-master] loaded module [lang-painless]
[2017-06-14T17:36:28,717][INFO ][o.e.p.PluginsService     ] [node-master] loaded module [percolator]
[2017-06-14T17:36:28,721][INFO ][o.e.p.PluginsService     ] [node-master] loaded module [reindex]
[2017-06-14T17:36:28,724][INFO ][o.e.p.PluginsService     ] [node-master] loaded module [transport-netty3]
[2017-06-14T17:36:28,731][INFO ][o.e.p.PluginsService     ] [node-master] loaded module [transport-netty4]
[2017-06-14T17:36:28,736][INFO ][o.e.p.PluginsService     ] [node-master] loaded plugin [ingest-attachment]
[2017-06-14T17:36:30,294][INFO ][o.e.d.DiscoveryModule    ] [node-master] using discovery type [zen]
[2017-06-14T17:36:30,781][INFO ][o.e.n.Node               ] [node-master] initialized
[2017-06-14T17:36:30,783][INFO ][o.e.n.Node               ] [node-master] starting ...
[2017-06-14T17:36:31,050][INFO ][o.e.t.TransportService   ] [node-master] publish_address {127.0.0.1:9300}, bound_addresses {127.0.0.1:9300}, {[::1]:9300}
[2017-06-14T17:36:34,094][INFO ][o.e.c.s.ClusterService   ] [node-master] new_master {node-master}{u3QZbpwHTu62bsHLlGJeuQ}{Zz_lpEu5QTu3SD-9rYX_wg}{127.0.0.1}{127.0.0.1:9300}, reason: zen-disco-elected-as-master ([0] nodes joined)
[2017-06-14T17:36:34,270][INFO ][o.e.h.n.Netty4HttpServerTransport] [node-master] publish_address {127.0.0.1:9200}, bound_addresses {127.0.0.1:9200}, {[::1]:9200}
[2017-06-14T17:36:34,279][INFO ][o.e.n.Node               ] [node-master] started
[2017-06-14T17:36:34,353][INFO ][o.e.g.GatewayService     ] [node-master] recovered [2] indices into cluster_state
[2017-06-14T17:36:34,680][INFO ][o.e.c.r.a.AllocationService] [node-master] Cluster health status changed from [RED] to [YELLOW] (reason: [shards started [[school][4], [.kibana][0]] ...]).
````

**Comment by dadoonet** [comment]
Is it related to FSCrawler project?

**Comment by Quix0r** [comment]
Yes, I use it to crawl local files (PDF, DOC, JPEG).

**Comment by dadoonet** [comment]
What is the relation with ingest-attachment then?

**Comment by dadoonet** [comment]
Make sure your platform uses UTF8 BTW

**Comment by Quix0r** [comment]
So what does FS require? Only plain ES without any plugins?

**Comment by dadoonet** [comment]
Yes

**Comment by Quix0r** [comment]
Ah, okay. :-)

**Comment by Quix0r** [comment]
Well, here at a Debian box, it works. There at work we have Windows 10.

**Comment by Quix0r** [comment]
Still same error message on Windows, even with same fscrawler version.

**Comment by Quix0r** [comment]
Maybe this helps?

https://github.com/elastic/elasticsearch-rails/issues/606#issuecomment-259675889

**Comment by Quix0r** [comment]
`"store_source" : true` is the cause of the mentioned error message. It looks like you didn't encode the whole file correctly as JSON. It needs to be pre-encoded with BASE64, then it should work.

Here is a small Perl example which I found on stackoverflow which allowed indexing whole source file:
````
coded=$(cat $1 | perl -MMIME::Base64 -ne 'print encode_base64($_)')
json="{\"file\":\"${coded}\"}"
````
This means:
- Encode file contents with BASE64
- Store that resulting string in a JSON field "file"

Then it should work. I think the Apache lib you are using provides such method.

**Comment by dadoonet** [comment]
Great diagnostic @Quix0r! Much appreciated!
