### ISSUE TITLE
java.io.IOException: listener timeout after waiting for [30000] ms

### ISSUE THREAD

**Issue by candido1212** [dadoonet/fscrawler#346]
i download RFCs documents (PDF) and try index it, but, and try bulk_size = 5 until 100

```
/projetos/fscrawler (master) $ FS_JAVA_OPTS="-Xmx1024m -Xms1024m" java -jar /tmp/fscrawler.jar rfc --trace --debug --restart
10:08:31,501 INFO  [f.p.e.c.f.FsCrawlerImpl] Starting FS crawler
10:08:31,507 INFO  [f.p.e.c.f.FsCrawlerImpl] FS crawler started in watch mode. It will run unless you stop it with CTRL+C.
10:08:33,125 INFO  [f.p.e.c.f.FsCrawlerImpl] FS crawler started for [rfc] for [/webphp/testes/elastic/rfc] every [50m]
10:08:33,138 DEBUG [f.p.e.c.f.f.FileAbstractor] Listing local files from /webphp/testes/elastic/rfc
10:08:33,146 DEBUG [f.p.e.c.f.f.FileAbstractor] 1 local files found
10:08:33,147 DEBUG [f.p.e.c.f.f.FileAbstractor] Listing local files from /webphp/testes/elastic/rfc/pdfrfc
10:08:36,101 DEBUG [f.p.e.c.f.f.FileAbstractor] 7988 local files found
10:16:07,813 WARN  [f.p.e.c.f.c.BulkProcessor] Error executing bulk
java.io.IOException: listener timeout after waiting for [30000] ms
	at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:617) ~[jar:rsrc:rest-5.2.2.jar!/:?]
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:212) ~[jar:rsrc:rest-5.2.2.jar!/:?]
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:184) ~[jar:rsrc:rest-5.2.2.jar!/:?]
	at fr.pilato.elasticsearch.crawler.fs.client.ElasticsearchClient.bulk(ElasticsearchClient.java:149) ~[rsrc:./:?]
	at fr.pilato.elasticsearch.crawler.fs.client.BulkProcessor.execute(BulkProcessor.java:157) [rsrc:./:?]
	at fr.pilato.elasticsearch.crawler.fs.client.BulkProcessor.executeIfNeeded(BulkProcessor.java:137) [rsrc:./:?]
	at fr.pilato.elasticsearch.crawler.fs.client.BulkProcessor.internalAdd(BulkProcessor.java:130) [rsrc:./:?]
	at fr.pilato.elasticsearch.crawler.fs.client.BulkProcessor.add(BulkProcessor.java:118) [rsrc:./:?]
	at fr.pilato.elasticsearch.crawler.fs.client.BulkProcessor.add(BulkProcessor.java:86) [rsrc:./:?]
	at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.esIndex(FsCrawlerImpl.java:719) [rsrc:./:?]
	at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.esIndex(FsCrawlerImpl.java:703) [rsrc:./:?]
	at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.indexFile(FsCrawlerImpl.java:596) [rsrc:./:?]
	at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.addFilesRecursively(FsCrawlerImpl.java:386) [rsrc:./:?]
	at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.addFilesRecursively(FsCrawlerImpl.java:405) [rsrc:./:?]
	at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.run(FsCrawlerImpl.java:273) [rsrc:./:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]

```
**job config file**
```

{
  "name" : "rfc",
  "fs" : {
    "url" : "/webphp/testes/elastic/rfc",
    "update_rate" : "50m",
    "excludes" : [ "~*" ],
    "json_support" : false,
    "filename_as_id" : false,
    "add_filesize" : true,
    "remove_deleted" : true,
    "add_as_inner_object" : false,
    "store_source" : false,
    "index_content" : true,
    "attributes_support" : false,
    "raw_metadata" : true,
    "xml_support" : false,
    "index_folders" : true,
    "lang_detect" : false,
    "continue_on_error" : true,
    "indexed_chars" : "1000000",
    "checksum": "SHA-1"
  },
  "elasticsearch" : {
    "nodes" : [ {
      "host" : "10.4.13.146",
      "port" : 80,
      "scheme" : "HTTP"
    } ],
    "type" : "doc",
    "bulk_size" : 1,
    "flush_interval" : "5s"
  },
  "rest" : {
    "scheme" : "HTTP",
    "host" : "127.0.0.1",
    "port" : 8080,
    "endpoint" : "fscrawler"
  }
}

```

**Comment by dadoonet** [comment]
Can you share the elasticsearch logs?

**Comment by dadoonet** [comment]
No further news. Closing. But feel free to reopen or comment.
