### ISSUE TITLE
can not create a new job

### ISSUE THREAD

**Issue by 695172327** [dadoonet/fscrawler#359]
[root@server03 fscrawler]# ./bin/fscrawler job
16:11:18,348 WARN  [f.p.e.c.f.FsCrawler] job [job] does not exist
16:11:18,349 INFO  [f.p.e.c.f.FsCrawler] Do you want to create it (Y/N)?
y
Exception in thread "main" java.nio.file.NoSuchFileException: /root/.fscrawler/job/_settings.json
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)
	at java.nio.file.Files.newOutputStream(Files.java:216)
	at java.nio.file.Files.write(Files.java:3292)
	at fr.pilato.elasticsearch.crawler.fs.meta.MetaFileHandler.writeFile(MetaFileHandler.java:80)
	at fr.pilato.elasticsearch.crawler.fs.meta.settings.FsSettingsFileHandler.write(FsSettingsFileHandler.java:56)
	at fr.pilato.elasticsearch.crawler.fs.FsCrawler.main(FsCrawler.java:181)

**Comment by dadoonet** [comment]
Can you try 2.3-SNAPSHOT and make sure you have the write access to your dir?

**Comment by 695172327** [comment]
we need to manually  create a  folder named new job_name，otherwise, it will be wrong.

**Comment by dadoonet** [comment]
This should not happen as FSCrawler is trying to create this dir by itself if it does not exist yet

**Comment by 695172327** [comment]
However, it happened. The  version of the elasticsearch is 1.5 and the version of  fscrawler is 2.1 .

**Comment by dadoonet** [comment]
Please try 2.3-SNAPSHOT.

**Comment by 695172327** [comment]
Can U tell me how to download  2.3-SNAPSHOT? Thanks！

**Comment by dadoonet** [comment]
Sure. The link is provided here: https://github.com/dadoonet/fscrawler/blob/master/README.md#download-fscrawler

> Note that you can also download a SNAPSHOT version ...

**Comment by dadoonet** [comment]
No further comment. So I guess it's ok now. Feel free to reopen if it's not the case.
