### ISSUE TITLE
You must call start() before client()

### ISSUE THREAD

**Issue by SirWaddles** [dadoonet/fscrawler#387]
I'm getting a weird error from fscrawler on Windows.

After running `./bin/fscrawler crs --trace`

I get the following error log
```
15:59:32,101 [36mDEBUG[m [f.p.e.c.f.u.FsCrawlerUtil] Mapping [1/_settings_doc.json] already exists
15:59:32,102 [36mDEBUG[m [f.p.e.c.f.u.FsCrawlerUtil] Mapping [1/_settings_folder.json] already exists
15:59:32,102 [36mDEBUG[m [f.p.e.c.f.u.FsCrawlerUtil] Mapping [2/_settings_doc.json] already exists
15:59:32,102 [36mDEBUG[m [f.p.e.c.f.u.FsCrawlerUtil] Mapping [2/_settings_folder.json] already exists
15:59:32,103 [36mDEBUG[m [f.p.e.c.f.u.FsCrawlerUtil] Mapping [5/_settings_doc.json] already exists
15:59:32,103 [36mDEBUG[m [f.p.e.c.f.u.FsCrawlerUtil] Mapping [5/_settings_folder.json] already exists
15:59:32,103 [36mDEBUG[m [f.p.e.c.f.u.FsCrawlerUtil] Mapping [6/_settings_doc.json] already exists
15:59:32,103 [36mDEBUG[m [f.p.e.c.f.u.FsCrawlerUtil] Mapping [6/_settings_folder.json] already exists
15:59:32,104 [36mDEBUG[m [f.p.e.c.f.FsCrawler] Starting job [crs]...
15:59:32,182 [30mTRACE[m [f.p.e.c.f.FsCrawler] settings used for this crawler: [{
  "name" : "crs",
  "fs" : {
    "url" : "S:\\Clients",
    "update_rate" : "15m",
    "excludes" : [ "~*" ],
    "json_support" : false,
    "filename_as_id" : false,
    "add_filesize" : true,
    "remove_deleted" : true,
    "add_as_inner_object" : false,
    "store_source" : false,
    "index_content" : true,
    "indexed_chars" : "-1.0",
    "attributes_support" : false,
    "raw_metadata" : true,
    "xml_support" : false,
    "index_folders" : true,
    "lang_detect" : false,
    "continue_on_error" : false,
    "pdf_ocr" : false
  },
  "elasticsearch" : {
    "nodes" : [ {
      "host" : "127.0.0.1",
      "port" : 9200,
      "scheme" : "HTTP"
    } ],
    "bulk_size" : 100,
    "flush_interval" : "5s"
  },
  "rest" : {
    "scheme" : "HTTP",
    "host" : "127.0.0.1",
    "port" : 8080,
    "endpoint" : "fscrawler"
  }
}]
15:59:32,186 [1;31mFATAL[m [f.p.e.c.f.FsCrawler] Fatal error received while running the crawler: [You must call start() before client()]
15:59:32,186 [36mDEBUG[m [f.p.e.c.f.FsCrawler] error caught
java.lang.RuntimeException: You must call start() before client()
	at fr.pilato.elasticsearch.crawler.fs.client.ElasticsearchClientManager.client(ElasticsearchClientManager.java:49) ~[fscrawler-2.3-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.FsCrawler.main(FsCrawler.java:264) [fscrawler-2.3-SNAPSHOT.jar:?]
15:59:32,189 [36mDEBUG[m [f.p.e.c.f.FsCrawlerImpl] Closing FS crawler [crs]
15:59:32,190 [36mDEBUG[m [f.p.e.c.f.FsCrawlerImpl] FS crawler Rest service stopped
15:59:32,190 [36mDEBUG[m [f.p.e.c.f.c.ElasticsearchClientManager] Closing Elasticsearch client manager
15:59:32,190 [36mDEBUG[m [f.p.e.c.f.FsCrawlerImpl] ES Client Manager stopped
15:59:32,190 [32mINFO [m [f.p.e.c.f.FsCrawlerImpl] FS crawler [crs] stopped
15:59:32,191 [36mDEBUG[m [f.p.e.c.f.FsCrawlerImpl] Closing FS crawler [crs]
15:59:32,191 [36mDEBUG[m [f.p.e.c.f.FsCrawlerImpl] FS crawler Rest service stopped
15:59:32,191 [36mDEBUG[m [f.p.e.c.f.c.ElasticsearchClientManager] Closing Elasticsearch client manager
15:59:32,191 [36mDEBUG[m [f.p.e.c.f.FsCrawlerImpl] ES Client Manager stopped
15:59:32,191 [32mINFO [m [f.p.e.c.f.FsCrawlerImpl] FS crawler [crs] stopped

```

I'm using the newest Snapshot version as 2.2 (downloaded from sonatype) doesn't work properly on Windows.

Elasticsearch is running on a separate computer with 20gb of RAM with an operating SSH tunnel. Running a `GET http://127.0.0.1:9200` returns

```json
{
    "name": "M_I8a6H",
    "cluster_name": "elasticsearch",
    "cluster_uuid": "mbROQETsS_6eOocxjNOMqQ",
    "version": {
        "number": "5.4.1",
        "build_hash": "2cfe0df",
        "build_date": "2017-05-29T16:05:51.443Z",
        "build_snapshot": false,
        "lucene_version": "6.5.1"
    },
    "tagline": "You Know, for Search"
}
```

I'm a bit lost here, my best guess is that this error is coming from the start() function, which doesn't make a lot of sense.

**Comment by dadoonet** [comment]
Thanks. Actually that's bad that the latest snapshot is actually built from a WIP branch where I introduced this regression. 

May be this one is more stable: https://oss.sonatype.org/content/repositories/snapshots/fr/pilato/elasticsearch/crawler/fscrawler/2.3-SNAPSHOT/fscrawler-2.3-20170613.231356-48.zip

**Comment by SirWaddles** [comment]
That seems to have solved it, thanks.

**Comment by dadoonet** [comment]
I pushed a change. It should fix the SNAPSHOT anytime soon.
All that is related to this pending PR #385 

Thanks for testing and reporting!
