### ISSUE TITLE
java.io.CharConversionException: Invalid UTF-8 start byte 0xff (at char #1, byte #-1)

### ISSUE THREAD

**Issue by Quix0r** [dadoonet/fscrawler#389]
This error happens when the option `"xml_support": true` is set. The parser encounters a non-XML (here JPEG image) file and tries to parse it as XML. The current only fix is to turn off that option.

````
11:05:04,021 DEBUG [f.p.e.c.f.FsCrawlerImpl] fetching content from [x:\foo-bar\media\imagemap\78],[start.jpg]
11:05:04,021 TRACE [f.p.e.c.f.t.XmlDocParser] Converting XML document [{}]
11:05:04,021 WARN  [f.p.e.c.f.FsCrawlerImpl] Error while crawling x:/foo-bar/media: java.io.IOException: java.io.CharConversionException: Invalid UTF-8 start byte 0xff (at char #1, byte #-1)
11:05:04,021 WARN  [f.p.e.c.f.FsCrawlerImpl] Full stacktrace
java.lang.RuntimeException: java.io.IOException: java.io.CharConversionException: Invalid UTF-8 start byte 0xff (at char #1, byte #-1)
        at fr.pilato.elasticsearch.crawler.fs.tika.XmlDocParser.asMap(XmlDocParser.java:49) ~[fscrawler-2.3-SNAPSHOT.jar:?]
        at fr.pilato.elasticsearch.crawler.fs.tika.XmlDocParser.generate(XmlDocParser.java:58) ~[fscrawler-2.3-SNAPSHOT.jar:?]
        at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.indexFile(FsCrawlerImpl.java:622) ~[fscrawler-2.3-SNAPSHOT.jar:?]
        at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.addFilesRecursively(FsCrawlerImpl.java:392) ~[fscrawler-2.3-SNAPSHOT.jar:?]
        at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.addFilesRecursively(FsCrawlerImpl.java:412) ~[fscrawler-2.3-SNAPSHOT.jar:?]
        at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.addFilesRecursively(FsCrawlerImpl.java:412) ~[fscrawler-2.3-SNAPSHOT.jar:?]
        at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.run(FsCrawlerImpl.java:276) [fscrawler-2.3-SNAPSHOT.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.io.IOException: java.io.CharConversionException: Invalid UTF-8 start byte 0xff (at char #1, byte #-1)
        at com.fasterxml.jackson.dataformat.xml.util.StaxUtil.throwXmlAsIOException(StaxUtil.java:24) ~[jackson-dataformat-xml-2.8.6.jar:2.8.6]
        at com.fasterxml.jackson.dataformat.xml.XmlFactory._createParser(XmlFactory.java:543) ~[jackson-dataformat-xml-2.8.6.jar:2.8.6]
        at com.fasterxml.jackson.dataformat.xml.XmlFactory._createParser(XmlFactory.java:29) ~[jackson-dataformat-xml-2.8.6.jar:2.8.6]
        at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:810) ~[jackson-core-2.8.6.jar:2.8.6]
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2915) ~[jackson-databind-2.8.6.jar:2.8.6]
        at fr.pilato.elasticsearch.crawler.fs.tika.XmlDocParser.asMap(XmlDocParser.java:47) ~[fscrawler-2.3-SNAPSHOT.jar:?]
        ... 7 more
Caused by: java.io.CharConversionException: Invalid UTF-8 start byte 0xff (at char #1, byte #-1)
        at com.ctc.wstx.io.UTF8Reader.reportInvalidInitial(UTF8Reader.java:304) ~[woodstox-core-5.0.3.jar:5.0.3]
        at com.ctc.wstx.io.UTF8Reader.read(UTF8Reader.java:190) ~[woodstox-core-5.0.3.jar:5.0.3]
        at com.ctc.wstx.io.ReaderSource.readInto(ReaderSource.java:89) ~[woodstox-core-5.0.3.jar:5.0.3]
        at com.ctc.wstx.io.BranchingReaderSource.readInto(BranchingReaderSource.java:57) ~[woodstox-core-5.0.3.jar:5.0.3]
        at com.ctc.wstx.sr.StreamScanner.loadMore(StreamScanner.java:998) ~[woodstox-core-5.0.3.jar:5.0.3]
        at com.ctc.wstx.sr.StreamScanner.getNext(StreamScanner.java:757) ~[woodstox-core-5.0.3.jar:5.0.3]
        at com.ctc.wstx.sr.BasicStreamReader.nextFromProlog(BasicStreamReader.java:2081) ~[woodstox-core-5.0.3.jar:5.0.3]
        at com.ctc.wstx.sr.BasicStreamReader.next(BasicStreamReader.java:1181) ~[woodstox-core-5.0.3.jar:5.0.3]
        at com.fasterxml.jackson.dataformat.xml.XmlFactory._initializeXmlReader(XmlFactory.java:652) ~[jackson-dataformat-xml-2.8.6.jar:2.8.6]
        at com.fasterxml.jackson.dataformat.xml.XmlFactory._createParser(XmlFactory.java:541) ~[jackson-dataformat-xml-2.8.6.jar:2.8.6]
        at com.fasterxml.jackson.dataformat.xml.XmlFactory._createParser(XmlFactory.java:29) ~[jackson-dataformat-xml-2.8.6.jar:2.8.6]
        at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:810) ~[jackson-core-2.8.6.jar:2.8.6]
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2915) ~[jackson-databind-2.8.6.jar:2.8.6]
        at fr.pilato.elasticsearch.crawler.fs.tika.XmlDocParser.asMap(XmlDocParser.java:47) ~[fscrawler-2.3-SNAPSHOT.jar:?]
        ... 7 more
````
Expected is that the parser does not attempt to parse such files as XML and chooses an other parser than XML.

**Comment by dadoonet** [comment]
Thanks for the full diagnostic. Much appreciated.
TBH I'm not sure what to do here.

I mean that if you want to send xml documents but actually are sending JPG files, then I doubt I can do anything.

**Comment by dadoonet** [comment]
Sure. It has been designed that way. If you say `"xml_support": true` you don't go through Tika and just converting basically XML to JSON using Jackson behind the scene.

If you want to use both, then you need to create 2 different FSCrawler jobs. One for XML which includes only `*.xml` files and another for all files but `*.xml` (using exclude). That way, XML will be parsed by Jackson. Other files will be parsed by Tika.

**Comment by Quix0r** [comment]
Ah, okay. And for index-separation leading to better performance and distribution of the index this also is a good idea.
