### ISSUE TITLE
Ingest pipeline should be applied to doc index only

### ISSUE THREAD

**Issue by dadoonet** [dadoonet/fscrawler#395]
As seen in https://github.com/dadoonet/fscrawler/issues/392#issuecomment-312421066 FSCrawler 2.2 uses the same pipeline for docs and folders. Which is wrong because you are not manipulating the same objects.

It causes bulk rejections for folders:

```
11:13:57,119 DEBUG [f.p.e.c.f.c.BulkProcessor] Error for job/folder/2388303e676399fcc46c92243c3b125d for null operation: {type=exception, reason=java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: field [content] not present as part of path [content], caused_by={type=illegal_argument_exception, reason=java.lang.IllegalArgumentException: field [content] not present as part of path [content], caused_by={type=illegal_argument_exception, reason=field [content] not present as part of path [content]}}, header={processor_type=gsub}}
```

**Comment by gwalashish** [comment]
Even after using the configuration which was working for you is not working for me from the command line,

```
{
  "name" : "fscrawler_test_ingest_pipeline_392",
  "fs" : {
    "url" : "/tmp/es"
  },
  "elasticsearch" : {
    "nodes" : [ {
      "host" : "127.0.0.1",
      "port" : 9200,
      "scheme" : "HTTP"
    } ],
    "pipeline" : "fscrawler_test_ingest_pipeline_392",
    "type" : "doc",
    "bulk_size" : 100,
    "flush_interval" : "5s"
  }
}
```

At least you tell me the thing which will work for files for now, that will solve the problem for the files for now.

**Comment by dadoonet** [comment]
Can you be more specific about what is not working?

**Comment by gwalashish** [comment]
It does not create the index only, please see below, 

> GET fscrawler_test_ingest_pipeline_392/_search


```
{
  "took": 0,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 0,
    "max_score": null,
    "hits": []
  }
}
```

I do not know what I am missing now, my _settings.json is given below,

```
{
  "name" : "fscrawler_test_ingest_pipeline_392",
    "fs" : {
        "url" : "/tmp/es"
          },
  "elasticsearch" : {
     "nodes" : [ {
      "host" : "127.0.0.1",
      "port" : 9200,
      "scheme" : "HTTP"
              } ],
      "pipeline" : "fscrawler_test_ingest_pipeline_392",
      "type" : "doc",
      "bulk_size" : 100,
      "flush_interval" : "5s"
                }
}
```

Please let me know if I am doing anything wrong above.

**Comment by gwalashish** [comment]
Now it worked for me as well but after I have deleted the old job completely and re-created a new job  with different name and copied the old _settings.json file which is given below,

```
{
  "name" : "fscrawler_test_ingest_pipeline_392",
    "fs" : {
        "url" : "/tmp/es"
          },
  "elasticsearch" : {
     "nodes" : [ {
      "host" : "127.0.0.1",
      "port" : 9200,
      "scheme" : "HTTP"
              } ],
      "pipeline" : "fscrawler_test_ingest_pipeline_392",
      "type" : "doc",
      "bulk_size" : 100,
      "flush_interval" : "5s"
                }
}

```

But this was the warning and error I got when I ran the Fscrawler but index was created successfully with the required fields.

```
# ./fscrawler testing_pdf
01:37:38,919 INFO  [f.p.e.c.f.FsCrawlerImpl] Starting FS crawler
01:37:38,921 INFO  [f.p.e.c.f.FsCrawlerImpl] FS crawler started in watch mode. It will run unless you stop it with CTRL+C.
01:37:41,428 INFO  [f.p.e.c.f.FsCrawlerImpl] FS crawler started for [fscrawler_test_ingest_pipeline_392] for [/tmp/es] every [15m]
01:37:41,992 WARN  [o.a.t.p.i.ImageParser] JBIG2ImageReader not loaded. jbig2 files will be ignored
01:37:44,344 WARN  [f.p.e.c.f.c.BulkProcessor] There was failures while executing bulk
java.lang.RuntimeException: 1 failures
        at fr.pilato.elasticsearch.crawler.fs.client.BulkResponse.buildFailureMessage(BulkResponse.java:73) ~[fscrawler-2.3-SNAPSHOT.jar:?]
        at fr.pilato.elasticsearch.crawler.fs.client.BulkProcessor$SimpleBulkProcessorListener.afterBulk(BulkProcessor.java:291) ~[fscrawler-2.3-SNAPSHOT.jar:?]
        at fr.pilato.elasticsearch.crawler.fs.client.BulkProcessor$AdvancedBulkProcessorListener.afterBulk(BulkProcessor.java:330) ~[fscrawler-2.3-SNAPSHOT.jar:?]
        at fr.pilato.elasticsearch.crawler.fs.client.BulkProcessor$RetryBulkProcessorListener.afterBulk(BulkProcessor.java:351) ~[fscrawler-2.3-SNAPSHOT.jar:?]
        at fr.pilato.elasticsearch.crawler.fs.client.BulkProcessor.execute(BulkProcessor.java:161) ~[fscrawler-2.3-SNAPSHOT.jar:?]
        at fr.pilato.elasticsearch.crawler.fs.client.BulkProcessor.executeWhenNeeded(BulkProcessor.java:146) ~[fscrawler-2.3-SNAPSHOT.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_121]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_121]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
01:37:44,349 WARN  [f.p.e.c.f.c.BulkProcessor] Throttling is activated. Got [0] successive errors so far.
01:37:44,493 ERROR [f.p.e.c.f.FsCrawlerImpl] As we got so far [1] errors, we are going to wait a bit here: [500] ms
```

> GET fscrawler_test_ingest_pipeline_392/_search

```
{
  "took": 1,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 1,
    "max_score": 1,
    "hits": [
      {
        "_index": "fscrawler_test_ingest_pipeline_392",
        "_type": "doc",
        "_id": "56375575e669cfc88cdc433e87c219b",
        "_score": 1,
        "_source": {
          "path": {
            "virtual": "/testing.pdf",
            "root": "824b64ab42d4b63cda6e747e2b80e5",
            "real": "/tmp/es/testing.pdf"
          },
          "file": {
            "extension": "pdf",
            "filename": "testing.pdf",
            "content_type": "application/pdf",
            "indexing_date": "2017-07-01T20:07:41.443+0000",
            "filesize": 6811,
            "last_modified": "2017-07-01T03:52:13.000+0000",
            "url": "file:///tmp/es/testing.pdf"
          },
          "meta": {},
          "ip_addr": "10.21.23.123",
          "content": "-10.21.23.123 is the IP address of the PXE.---"
        }
      }
    ]
  }
}
```

Thank you so much for the help, we will see into the folder thing as well to completely closed this issue.

**Comment by dadoonet** [comment]
Run it with --restart option

And may be --trace as well
