### ISSUE TITLE
Issues on Win Server2012

### ISSUE THREAD

**Issue by Ramon-zaro** [dadoonet/fscrawler#471]
Hello David, as I might have mentioned before I am running fscrawler on a win2012 system to crawl & index network drives for documents (primarily txt, pdf, doc, xls etc).

there are 2 such drives, one with about 1 million files & the other with about 4 million. it runs fine on the first one but in the second one I havent been able to get fscrawler complete the crawl cycle. it runs of some files and then it stops, the best I got was 2.5 mil, but it has also stopped after as low as 50k.
I ran fscrawler in debug mode after the first couple of failed runs. 
it was giving java heap space outofmemory error. 
at java.util.array.copyofrange <unknown source>
at java.lang.string <init> <unknown source>
etc
I am sorry the system is offline and I can't get you a full copy of the debug. However if you need anything specific from the debug I can get it for you.

Is this a RAM issue ? or is the size of the data itself a problem ? 
could you suggest minimum/ideal requirements.
regards.

P.S. is it possible to add the date as well to the debug response, currently only the time is recorded which makes it difficult to pinpoint problems over a multi-day run.

**Comment by dadoonet** [comment]
Did you try to change the HEAP settings for FSCrawler?

https://github.com/dadoonet/fscrawler/blob/master/README.md#jvm-settings

**Comment by Ramon-zaro** [comment]
sure, will give it a try. how much would you recommend ? not sure how much is set as default.

**Comment by dadoonet** [comment]
I don't know. May be 2 or 4 gb?

**Comment by dadoonet** [comment]
But I should revisit the code and use only streams if possible.

**Comment by dadoonet** [comment]
@Ramon-zaro Did you increase memory settings?

**Comment by dadoonet** [comment]
Would be BTW super helpful if you could share the full stacktrace when something like this is happening.

**Comment by dadoonet** [comment]
I also checked that we are using Streams as must as possible. But at the end of the day this is producing JSon documents which are hold in memory.
Could you share your FSCrawler settings for the job you are running?

**Comment by Ramon-zaro** [comment]
I did two things, set the remove deleted to false and set bitesize to 10. I did not change heap memory settings. that seems to have taken care of the issue.

**Comment by roselan** [comment]
We face the exact same issue, but I don't see this bytesize you speak of. Can you please enlighen me? ty!

**Comment by Ramon-zaro** [comment]
bulksize.

**Comment by roselan** [comment]
thank you.

After further investigation, I did notice tons of entries like htat in the log:
`10:22:07,284 [33mWARN [m [f.p.e.c.f.c.BulkProcessor] Error executing bulk
java.io.IOException: listener timeout after waiting for [30000] ms
	at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:660) ~[rest-5.5.0.jar:5.5.0]
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:219) ~[rest-5.5.0.jar:5.5.0]
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:191) ~[rest-5.5.0.jar:5.5.0]
	at fr.pilato.elasticsearch.crawler.fs.client.ElasticsearchClient.bulk(ElasticsearchClient.java:150) ~[fscrawler-2.3.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.client.BulkProcessor.execute(BulkProcessor.java:159) [fscrawler-2.3.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.client.BulkProcessor.executeIfNeeded(BulkProcessor.java:139) [fscrawler-2.3.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.client.BulkProcessor.internalAdd(BulkProcessor.java:132) [fscrawler-2.3.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.client.BulkProcessor.add(BulkProcessor.java:120) [fscrawler-2.3.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.client.BulkProcessor.add(BulkProcessor.java:88) [fscrawler-2.3.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.esIndex(FsCrawlerImpl.java:790) [fscrawler-2.3.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.esIndex(FsCrawlerImpl.java:761) [fscrawler-2.3.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.indexFile(FsCrawlerImpl.java:667) [fscrawler-2.3.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.addFilesRecursively(FsCrawlerImpl.java:455) [fscrawler-2.3.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.addFilesRecursively(FsCrawlerImpl.java:475) [fscrawler-2.3.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.addFilesRecursively(FsCrawlerImpl.java:475) [fscrawler-2.3.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.addFilesRecursively(FsCrawlerImpl.java:475) [fscrawler-2.3.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.addFilesRecursively(FsCrawlerImpl.java:475) [fscrawler-2.3.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.run(FsCrawlerImpl.java:339) [fscrawler-2.3.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]`

When restarting the server, around half a million of 
`10:30:00,504 [33mWARN [m [f.p.e.c.f.FsCrawlerImpl] trying to add new file while closing crawler. Document [data_folder]/[doc]/[6cf473345854c5348f10cc5f6d1d4d6c] has been ignored
10:30:00,504 [33mWARN [m [f.p.e.c.f.FsCrawlerImpl] trying to add new file while closing crawler. Document [data]/[doc]/[329d1e9363d3c9c766e725d5723c1c9] has been ignored
10:30:00,504 [33mWARN [m [f.p.e.c.f.FsCrawlerImpl] trying to add new file while closing crawler. Document [data]/[doc]/[309ea82e6f7c72b238b4bd1467422bf9] has been ignored
10:30:00,520 [33mWARN [m [f.p.e.c.f.FsCrawlerImpl] trying to add new file while closing crawler. Document [data]/[doc]/[2d035f7bc2d5d6f3be46bbf982da92] has been ignored
10:30:00,520 [33mWARN [m [f.p.e.c.f.FsCrawlerImpl] trying to add new file while closing crawler. Document [data]/[doc]/[9af392777fd864563f71bad48a040] has been ignored
10:30:00,520 [33mWARN [m [f.p.e.c.f.FsCrawlerImpl] trying to add new file while closing crawler. Document [data_folder]/[doc]/[eb5aa2e252a7a289844c59d9171b6dc] has been ignored
10:30:00,535 [33mWARN [m [f.p.e.c.f.FsCrawlerImpl] trying to add new file while closing crawler. Document [data]/[doc]/[a9586f895010adda57c26e28f8896bde] has been ignored
10:30:00,535 [33mWARN [m [f.p.e.c.f.FsCrawlerImpl] trying to add new file while closing crawler. Document [data]/[doc]/[27e576445aa5aa2059832e832ebd128] has been ignored
10:30:00,535 [33mWARN [m [f.p.e.c.f.FsCrawlerImpl] trying to add new file while closing crawler. Document [data]/[doc]/[83e969de277fb848c1c94855dfaf6072] has been ignored
10:30:00,535 [33mWARN [m [f.p.e.c.f.FsCrawlerImpl] trying to add new file while closing crawler. Document [data]/[doc]/[7cc45cfdd490ffc07d9c20f8516] has been ignored
10:30:00,551 [33mWARN [m [f.p.e.c.f.FsCrawlerImpl] trying to add new file while closing crawler. Document [data]/[doc]/[7e29c2780c58bb72697a954e69479f] has been ignored
10:30:00,551 [33mWARN [m [f.p.e.c.f.FsCrawlerImpl] trying to add new file while closing crawler. Document [data]/[doc]/[ac385342f5d2873fb691a37f2eaa677d] has been ignored
10:30:00,598 [33mWARN [m [f.p.e.c.f.FsCrawlerImpl] trying to add new file while closing crawler. Document [data]/[doc]/[908d742c4a73c069d16a7b276927cc1f] has been ignored
10:30:00,660 [33mWARN [m [f.p.e.c.f.FsCrawlerImpl] trying to add new file while closing crawler. Document [data]/[doc]/[b53a34663293e218ac83663af22b8fc] has been ignored`

My best guess is that bulk process chokes and prevent new files to be added. Can't wait for #399 to be implemented.

**Comment by dadoonet** [comment]
I hope that the recent implementation I added with #563 would help to solve the memory pressure issues you have been reporting at first.

That said, there is indeed a memory problem probably as reported in #566.
As this other bug report is super detailed, I'm going to close this.

@roselan Did you manage to fix the problem? Dis you try a more recent build?
