### ISSUE TITLE
Update Lucene Test Framework to 7.2.0

### ISSUE THREAD

**Issue by dadoonet** [dadoonet/fscrawler#481]
Only if possible

**Comment by dadoonet** [comment]
Does not work if Elasticsearch REST client does not use the same version...

```
java.lang.AssertionError: Version must be upgraded to [7.2.0] is still set to [7.1.0]

	at __randomizedtesting.SeedInfo.seed([3989DAD44077901]:0)
	at org.elasticsearch.Version.<clinit>(Version.java:142)
	at org.elasticsearch.common.logging.DeprecationLogger.<clinit>(DeprecationLogger.java:159)
	at org.elasticsearch.common.ParseField.<clinit>(ParseField.java:35)
	at org.elasticsearch.client.RestHighLevelClient.lambda$getDefaultNamedXContents$47(RestHighLevelClient.java:628)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1691)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.elasticsearch.client.RestHighLevelClient.getDefaultNamedXContents(RestHighLevelClient.java:629)
	at org.elasticsearch.client.RestHighLevelClient.<init>(RestHighLevelClient.java:211)
	at org.elasticsearch.client.RestHighLevelClient.<init>(RestHighLevelClient.java:196)
	at org.elasticsearch.client.RestHighLevelClient.<init>(RestHighLevelClient.java:188)
	at fr.pilato.elasticsearch.crawler.fs.client.ElasticsearchClient.<init>(ElasticsearchClient.java:64)
```
