### ISSUE TITLE
"String index out of range" warning, nothing getting indexed

### ISSUE THREAD

**Issue by SoShoTech** [dadoonet/fscrawler#612]
Hello, I am getting the following message each time I start fscrawler - "17:34:16,560 WARN  [f.p.e.c.f.FsParser] Error while crawling /tmp/es: String index out of range: -1".  This happens whether I use a custom directory, or the default tmp/es.  Am using Windows with the MSI version of ElasticSearch, fscrawler 2.5.  I also did a build of 2.6 and got the same result.  Am using dejavu to browse for data, but nothing is in there.  Any ideas on what could be going wrong?  Thanks!

**Comment by dadoonet** [comment]
Could you run with --debug option and share the full logs?

**Comment by SoShoTech** [comment]
Sure thing
`PS C:\Users\[me]\Downloads\elastic\fscrawler> bin/fscrawler adobe --debug
16:00:08,512 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [2/_settings.json] already exists
16:00:08,515 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [2/_settings_folder.json] already exists
16:00:08,515 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [5/_settings.json] already exists
16:00:08,515 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [5/_settings_folder.json] already exists
16:00:08,516 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [6/_settings.json] already exists
16:00:08,516 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [6/_settings_folder.json] already exists
16:00:08,517 DEBUG [f.p.e.c.f.c.FsCrawler] Starting job [adobe]...
16:00:09,768 DEBUG [f.p.e.c.f.c.ElasticsearchClient] Using elasticsearch >= 5, so we can use ingest node feature
16:00:09,768 DEBUG [f.p.e.c.f.c.ElasticsearchClient] Using elasticsearch >= 6, so we can use _doc as the default type name
16:00:09,808 INFO  [f.p.e.c.f.FsCrawlerImpl] Starting FS crawler
16:00:09,809 INFO  [f.p.e.c.f.FsCrawlerImpl] FS crawler started in watch mode. It will run unless you stop it with CTRL+C.
16:00:09,815 DEBUG [f.p.e.c.f.c.ElasticsearchClientManager] FS crawler connected to an elasticsearch [6.4.1] node.
16:00:09,816 DEBUG [f.p.e.c.f.c.ElasticsearchClient] create index [adobe]
16:00:09,842 DEBUG [f.p.e.c.f.c.ElasticsearchClient] create index [adobe_folder]
16:00:09,852 DEBUG [f.p.e.c.f.FsParser] creating fs crawler thread [adobe] for [../data/adobe] every [1d]
16:00:09,853 INFO  [f.p.e.c.f.FsParser] FS crawler started for [adobe] for [../data/adobe] every [1d]
16:00:09,853 DEBUG [f.p.e.c.f.FsParser] Fs crawler thread [adobe] is now running. Run #1...
16:00:09,861 WARN  [f.p.e.c.f.FsParser] Error while crawling ../data/adobe: String index out of range: -1
16:00:09,861 WARN  [f.p.e.c.f.FsParser] Full stacktrace
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.String.substring(String.java:1967) ~[?:1.8.0_152]
        at fr.pilato.elasticsearch.crawler.fs.FsParser.indexDirectory(FsParser.java:550) ~[fscrawler-core-2.5.jar:?]
        at fr.pilato.elasticsearch.crawler.fs.FsParser.run(FsParser.java:160) [fscrawler-core-2.5.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
16:00:09,865 DEBUG [f.p.e.c.f.FsParser] Fs crawler is going to sleep for 1d`

**Comment by trang94** [comment]
I also have the same issue now

**Comment by dadoonet** [comment]
I don't think we support relative paths like `../data/adobe`. What does your settings.json file look like?

**Comment by JohannesRoss** [comment]
I have come across this Problem. Here the Stacktrace:
`Path>fscrawler pdf --debug
14:25:02,071 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [2/_settings.json] already exists
14:25:02,071 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [2/_settings_folder.json] already exists
14:25:02,071 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [5/_settings.json] already exists
14:25:02,071 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [5/_settings_folder.json] already exists
14:25:02,071 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [6/_settings.json] already exists
14:25:02,071 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [6/_settings_folder.json] already exists
14:25:02,071 DEBUG [f.p.e.c.f.c.FsCrawler] Starting job [pdf]...
14:25:02,742 DEBUG [f.p.e.c.f.c.ElasticsearchClient] Using elasticsearch >= 5, so we can use ingest node feature
14:25:02,742 DEBUG [f.p.e.c.f.c.ElasticsearchClient] Using elasticsearch >= 6, so we can use _doc as the default type name
14:25:02,773 INFO  [f.p.e.c.f.FsCrawlerImpl] Starting FS crawler
14:25:02,773 INFO  [f.p.e.c.f.FsCrawlerImpl] FS crawler started in watch mode. It will run unless you stop it with CTRL+C.
14:25:02,773 DEBUG [f.p.e.c.f.c.ElasticsearchClientManager] FS crawler connected to an elasticsearch [6.5.4] node.
14:25:02,773 DEBUG [f.p.e.c.f.c.ElasticsearchClient] create index [pdf]
14:25:02,804 DEBUG [f.p.e.c.f.c.ElasticsearchClient] create index [pdf_folder]
14:25:02,820 DEBUG [f.p.e.c.f.FsParser] creating fs crawler thread [pdf] for [path] every [15m]
14:25:02,820 INFO  [f.p.e.c.f.FsParser] FS crawler started for [pdf] for [path] every [15m]
14:25:02,820 DEBUG [f.p.e.c.f.FsParser] Fs crawler thread [pdf] is now running. Run #1...
14:25:02,836 WARN  [f.p.e.c.f.FsParser] Error while crawling path: begin 0, end -1, length 26
14:25:02,836 WARN  [f.p.e.c.f.FsParser] Full stacktrace
java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 26
        at java.lang.String.checkBoundsBeginEnd(String.java:3410) ~[?:?]
        at java.lang.String.substring(String.java:1883) ~[?:?]
        at fr.pilato.elasticsearch.crawler.fs.FsParser.indexDirectory(FsParser.java:550) ~[fscrawler-core-2.5.jar:?]
        at fr.pilato.elasticsearch.crawler.fs.FsParser.run(FsParser.java:160) [fscrawler-core-2.5.jar:?]
        at java.lang.Thread.run(Thread.java:835) [?:?]
14:25:02,851 DEBUG [f.p.e.c.f.FsParser] Fs crawler is going to sleep for 15m`
(I replaced the path, cuz pivacy)

Here my settings.json: 
`{
  "name" : "pdf",
  "fs" : {
    "url" : "path",
    "update_rate" : "15m",
    "excludes" : [ "*/~*" ],
    "json_support" : false,
    "filename_as_id" : false,
    "add_filesize" : true,
    "remove_deleted" : true,
    "add_as_inner_object" : false,
    "store_source" : false,
    "index_content" : true,
    "attributes_support" : false,
    "raw_metadata" : true,
    "xml_support" : false,
    "index_folders" : true,
    "lang_detect" : false,
    "continue_on_error" : false,
    "pdf_ocr" : true,
    "ocr" : {
      "language" : "eng"
    }
  },
  "elasticsearch" : {
    "nodes" : [ {
      "host" : "127.0.0.1",
      "port" : 9200,
      "scheme" : "HTTP"
    } ],
    "bulk_size" : 100,
    "flush_interval" : "5s",
    "byte_size" : "10mb"
  },
  "rest" : {
    "scheme" : "HTTP",
    "host" : "127.0.0.1",
    "port" : 8080,
    "endpoint" : "fscrawler"
  }
}`
I'm using fscrawler 2.5 and Elasticsearch 6.5 on Windows 10. I'm pretty new to fscrawler and coun't find anything. Can someone help me?

**Comment by dadoonet** [comment]
> I'm using fscrawler 2.5 and Elasticsearch 6.5 on Windows 10. I'm pretty new to fscrawler and coun't find anything. Can someone help me?

Could you upgrade to at least 2.6 or 2.7-SNAPSHOT?

**Comment by JohannesRoss** [comment]
I'm now using 2.7-Snapshot and I get another Error:
`org.elasticsearch.ElasticsearchStatusException: Elasticsearch exception [type=illegal_argument_exception, reason=request [/pdf] contains unrecognized parameter: [include_type_name]]
`
I think there is already an issue with this.
Upgrading to 2.7 fixed my Index out of range Problem

**Comment by dadoonet** [comment]
@JohannesRoss Yeah. You are hitting this #720

**Comment by JohannesRoss** [comment]
I now have updated Elasticsearch to 7.0.1 and the crawler to 2.7-SNAPSHOT.
Now everything works fine.
Thank you for your support.
