### ISSUE TITLE
xml file crawling with xml_support=true is failing

### ISSUE THREAD

**Issue by suresh-nataraj** [dadoonet/fscrawler#618]
I am getting the below error while trying to crawl xml content. Could you please understand what is causing this issue ? I validated the xml and it looks fine.
```
21:28:38,146 WARN  [f.p.e.c.f.FsParser] Error while crawling /Users/sn2/Desktop/tech_docs_search_poc/xsmart: java.io.IOException: Expected END_ELEMENT, got event of type 1
21:28:38,146 WARN  [f.p.e.c.f.FsParser] Full stacktrace
java.lang.RuntimeException: java.io.IOException: Expected END_ELEMENT, got event of type 1
	at fr.pilato.elasticsearch.crawler.fs.tika.XmlDocParser.asMap(XmlDocParser.java:50) ~[fscrawler-tika-2.5.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.tika.XmlDocParser.generateMap(XmlDocParser.java:76) ~[fscrawler-tika-2.5.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.FsParser.indexFile(FsParser.java:480) ~[fscrawler-core-2.5.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.FsParser.addFilesRecursively(FsParser.java:266) ~[fscrawler-core-2.5.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.FsParser.run(FsParser.java:167) [fscrawler-core-2.5.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
Caused by: java.io.IOException: Expected END_ELEMENT, got event of type 1
	at com.fasterxml.jackson.dataformat.xml.deser.XmlTokenStream.skipEndElement(XmlTokenStream.java:190) ~[jackson-dataformat-xml-2.9.6.jar:2.9.6]
	at com.fasterxml.jackson.dataformat.xml.deser.FromXmlParser.nextToken(FromXmlParser.java:584) ~[jackson-dataformat-xml-2.9.6.jar:2.9.6]
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer.mapObject(UntypedObjectDeserializer.java:542) ~[jackson-databind-2.9.6.jar:2.9.6]
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer.deserialize(UntypedObjectDeserializer.java:248) ~[jackson-databind-2.9.6.jar:2.9.6]
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer.mapObject(UntypedObjectDeserializer.java:526) ~[jackson-databind-2.9.6.jar:2.9.6]
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer.deserialize(UntypedObjectDeserializer.java:248) ~[jackson-databind-2.9.6.jar:2.9.6]
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:527) ~[jackson-databind-2.9.6.jar:2.9.6]
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:364) ~[jackson-databind-2.9.6.jar:2.9.6]
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:29) ~[jackson-databind-2.9.6.jar:2.9.6]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013) ~[jackson-databind-2.9.6.jar:2.9.6]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3077) ~[jackson-databind-2.9.6.jar:2.9.6]
	at fr.pilato.elasticsearch.crawler.fs.tika.XmlDocParser.asMap(XmlDocParser.java:48) ~[fscrawler-tika-2.5.jar:?]
	... 5 more
```

**Comment by dadoonet** [comment]
Could you share the file which is producing this error?

**Comment by suresh-nataraj** [comment]
Can I share the file in mail ? Please provide me the mail id .

**Comment by dadoonet** [comment]
david (at) elastic.co

**Comment by dadoonet** [comment]
Hi @suresh-nataraj 

I'm not if I got your email. Could you send it again?

**Comment by dadoonet** [comment]
Closing. Feel free to reopen if you can send me the file again.
