### ISSUE TITLE
Limit of total fields (5000) reached

### ISSUE THREAD

**Issue by devgmk** [dadoonet/fscrawler#702]
We are getting time out errors after which the job is getting stopped. Below are the error messages we see in the elasticsearch logs.

```
[2019-03-27T04:18:31,678][DEBUG][o.e.a.a.i.m.p.TransportPutMappingAction] [node-2] failed to put mappings on indices [[[job1/MIBI14llQIWuphmORB-Plg]]], type [_doc]
java.lang.IllegalArgumentException: Limit of total fields [5000] in index [job1] has been exceeded
        at org.elasticsearch.index.mapper.MapperService.checkTotalFieldsLimit(MapperService.java:628) ~[elasticsearch-6.5.4.jar:6.5.4]
        at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:511) ~[elasticsearch-6.5.4.jar:6.5.4]
        at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:399) ~[elasticsearch-6.5.4.jar:6.5.4]
        at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:331) ~[elasticsearch-6.5.4.jar:6.5.4]
        at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.applyRequest(MetaDataMappingService.java:313) ~[elasticsearch-6.5.4.jar:6.5.4]
        at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.execute(MetaDataMappingService.java:229) ~[elasticsearch-6.5.4.jar:6.5.4]
        at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:639) ~[elasticsearch-6.5.4.jar:6.5.4]
        at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:268) ~[elasticsearch-6.5.4.jar:6.5.4]
        at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:198) [elasticsearch-6.5.4.jar:6.5.4]
        at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:133) [elasticsearch-6.5.4.jar:6.5.4]
        at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150) [elasticsearch-6.5.4.jar:6.5.4]
        at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188) [elasticsearch-6.5.4.jar:6.5.4]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:624) [elasticsearch-6.5.4.jar:6.5.4]
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:244) [elasticsearch-6.5.4.jar:6.5.4]
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:207) [elasticsearch-6.5.4.jar:6.5.4]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
```

**Comment by dadoonet** [comment]
Here is the important part: `Limit of total fields [5000] in index [job1]`. It means that you have been generated much more fields than expected.

Could you share the output of:

```
GET /job1/_mapping
```

**Comment by Ganesh2409** [comment]
I have increased the mappings limit to 5000 from the default limit of 2000. I have even tried with 10000 but we still got the timeout error.
 The mapping output is too big, I can't paste here as it is exceeding the max characters limit. Let me know if there is other way to share the mapping information.

**Comment by Ganesh2409** [comment]
Below is the error messages from fscrawler logs.

`WARN  [f.p.e.c.f.FsParserAbstract] Full stacktrace
java.io.IOException: listener timeout after waiting for [30000] ms
	at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:908) ~[elasticsearch-rest-client-6.6.0.jar:6.6.0]
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:229) ~[elasticsearch-rest-client-6.6.0.jar:6.6.0]
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1762) ~[elasticsearch-rest-high-level-client-6.6.0.jar:6.6.0]
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1732) ~[elasticsearch-rest-high-level-client-6.6.0.jar:6.6.0]
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1694) ~[elasticsearch-rest-high-level-client-6.6.0.jar:6.6.0]
	at org.elasticsearch.client.RestHighLevelClient.search(RestHighLevelClient.java:1090) ~[elasticsearch-rest-high-level-client-6.6.0.jar:6.6.0]
	at fr.pilato.elasticsearch.crawler.fs.client.v6.ElasticsearchClientV6.search(ElasticsearchClientV6.java:478) ~[fscrawler-elasticsearch-client-v6-2.7-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.FsParserAbstract.getFileDirectory(FsParserAbstract.java:355) ~[fscrawler-core-2.7-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.FsParserAbstract.addFilesRecursively(FsParserAbstract.java:309) ~[fscrawler-core-2.7-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.FsParserAbstract.addFilesRecursively(FsParserAbstract.java:291) ~[fscrawler-core-2.7-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.FsParserAbstract.addFilesRecursively(FsParserAbstract.java:291) ~[fscrawler-core-2.7-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.FsParserAbstract.addFilesRecursively(FsParserAbstract.java:291) ~[fscrawler-core-2.7-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.FsParserAbstract.addFilesRecursively(FsParserAbstract.java:291) ~[fscrawler-core-2.7-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.FsParserAbstract.addFilesRecursively(FsParserAbstract.java:291) ~[fscrawler-core-2.7-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.FsParserAbstract.addFilesRecursively(FsParserAbstract.java:291) ~[fscrawler-core-2.7-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.FsParserAbstract.addFilesRecursively(FsParserAbstract.java:291) ~[fscrawler-core-2.7-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.FsParserAbstract.addFilesRecursively(FsParserAbstract.java:291) ~[fscrawler-core-2.7-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.FsParserAbstract.run(FsParserAbstract.java:149) [fscrawler-core-2.7-SNAPSHOT.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]`

**Comment by dadoonet** [comment]
> Let me know if there is other way to share the mapping information.

Yes you can share the file on gist.github.com.

The latest logs you pasted seemed to be unrelated though.

**Comment by Ganesh2409** [comment]
Here is the link to the mappings file.

> https://gist.github.com/Ganesh2409/971edb42b951f9ddf31a3a337bd51873

The FSCrawler logs I have mentioned are from the FSCrawler during the timeout issue.
Then I have checked the elasticseach logs and found out **failed to put mappings on indices**(this error is continuously coming in the logs). After seeing this I have increased the mappings limit but again I hit the same issue.

**Comment by dadoonet** [comment]
Normally Kibana formats the output when you call:

```
GET /job1/_mapping
```

If you are not using Kibana, please add `?pretty` at the end to render the JSON document in a pretty format. That'd increase readability.

Anyway, I'd suggest to change your dynamic template:

```json
{  
                  "raw_as_text":{  
                     "path_match":"meta.raw.*",
                     "mapping":{  
                        "fields":{  
                           "keyword":{  
                              "ignore_above":256,
                              "type":"keyword"
                           }
                        },
                        "type":"text"
                     }
                  }
               }
```

Because it's creating 2 fields for every single meta-data you have.
And you have tons of metadata I've never heard about before.

* `97 ISSCC evening session award`
* `97 Jack Kilby award`
* ...
* `98 IEEE fellow awards`
* ...
* `AB`
* `AC`
* `AD`
* ...

Do you know what it is?
Do you really need to extract all the raw metadata? If not, I'd recommend disabling this: https://fscrawler.readthedocs.io/en/latest/admin/fs/local-fs.html#disabling-raw-metadata

**Comment by Ganesh2409** [comment]
We mainly need the File Content and its properties. I will try disabling the raw metadata and check again. Thanks for your inputs.

**Comment by dadoonet** [comment]
I might consider to disable `raw_metadata` by default. It seems to be only for advanced use cases.

**Comment by Ganesh2409** [comment]
I have disabled the raw metadata and started the indexing again. I still get the same time out error. Only this time there are no error messages in the Elasticsearch logs.

> 08:38:59,614 WARN  [f.p.e.c.f.FsParserAbstract] Error while crawling \\server\folder: listener timeout after waiting for [30000] ms
> 08:38:59,614 WARN  [f.p.e.c.f.FsParserAbstract] Full stacktrace
> java.io.IOException: listener timeout after waiting for [30000] ms
> 	at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:908) ~[elasticsearch-rest-client-6.6.0.jar:6.6.0]
> 	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:229) ~[elasticsearch-rest-client-6.6.0.jar:6.6.0]
> 	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1762) ~[elasticsearch-rest-high-level-client-6.6.0.jar:6.6.0]
> 	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1732) ~[elasticsearch-rest-high-level-client-6.6.0.jar:6.6.0]
> 	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1694) ~[elasticsearch-rest-high-level-client-6.6.0.jar:6.6.0]
> 	at org.elasticsearch.client.RestHighLevelClient.search(RestHighLevelClient.java:1090) ~[elasticsearch-rest-high-level-client-6.6.0.jar:6.6.0]
> 	at fr.pilato.elasticsearch.crawler.fs.client.v6.ElasticsearchClientV6.search(ElasticsearchClientV6.java:478) ~[fscrawler-elasticsearch-client-v6-2.7-SNAPSHOT.jar:?]
> 	at fr.pilato.elasticsearch.crawler.fs.FsParserAbstract.getFileDirectory(FsParserAbstract.java:355) ~[fscrawler-core-2.7-SNAPSHOT.jar:?]
> 	at fr.pilato.elasticsearch.crawler.fs.FsParserAbstract.addFilesRecursively(FsParserAbstract.java:309) ~[fscrawler-core-2.7-SNAPSHOT.jar:?]
> 	at fr.pilato.elasticsearch.crawler.fs.FsParserAbstract.addFilesRecursively(FsParserAbstract.java:291) ~[fscrawler-core-2.7-SNAPSHOT.jar:?]
> 	at fr.pilato.elasticsearch.crawler.fs.FsParserAbstract.addFilesRecursively(FsParserAbstract.java:291) ~[fscrawler-core-2.7-SNAPSHOT.jar:?]
> 	at fr.pilato.elasticsearch.crawler.fs.FsParserAbstract.addFilesRecursively(FsParserAbstract.java:291) ~[fscrawler-core-2.7-SNAPSHOT.jar:?]
> 	at fr.pilato.elasticsearch.crawler.fs.FsParserAbstract.addFilesRecursively(FsParserAbstract.java:291) ~[fscrawler-core-2.7-SNAPSHOT.jar:?]
> 	at fr.pilato.elasticsearch.crawler.fs.FsParserAbstract.addFilesRecursively(FsParserAbstract.java:291) ~[fscrawler-core-2.7-SNAPSHOT.jar:?]
> 	at fr.pilato.elasticsearch.crawler.fs.FsParserAbstract.run(FsParserAbstract.java:149) [fscrawler-core-2.7-SNAPSHOT.jar:?]
> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
> 08:38:59,617 INFO  [f.p.e.c.f.FsParserAbstract] FS crawler is stopping after 1 run
> 08:38:59,713 DEBUG [f.p.e.c.f.FsCrawlerImpl] Closing FS crawler [job1]
> 08:38:59,715 DEBUG [f.p.e.c.f.FsCrawlerImpl] FS crawler thread is now stopped
> 08:38:59,716 DEBUG [f.p.e.c.f.c.v.ElasticsearchClientV6] Closing Elasticsearch client manager

**Comment by dadoonet** [comment]
Do you have any logs in elasticsearch? Could you share them?
Is this happening as soon as you run FSCrawler or after some documents have been indexed?

**Comment by Ganesh2409** [comment]
There are no ERROR messages in the logs at the time of failure. This is happening after some documents are indexed. If I start the job again it is running without any issue for sometime and fails with the same timeout message.

**Comment by dadoonet** [comment]
Sorry for the late reply. Did you solve the problem at the end?

**Comment by dadoonet** [comment]
Not sure if it's still a problem. Closing but feel free to reopen or comment. Thanks!
