### ISSUE TITLE
FsCrawlerTestDatesIT.test_check_dates is flaky

### ISSUE THREAD

**Issue by dadoonet** [dadoonet/fscrawler#707]
```
  2> mvn integration-test -Dtests.seed=32630A4703F87548 -Dtests.class=fr.pilato.elasticsearch.crawler.fs.test.integration.FsCrawlerTestDatesIT -Dtests.method="test_check_dates" -Dtests.locale=ar-LB -Dtests.timezone=Africa/Niamey
FAILURE 15.3s | FsCrawlerTestDatesIT.test_check_dates <<<
   > Throwable #1: java.lang.AssertionError: 
   > Expected: "2019-03-28T07:56:59.887+0000"
   >      but: was "2019-03-28T07:56:53.362+0000"
   > 	at __randomizedtesting.SeedInfo.seed([32630A4703F87548:8DCC96C7D12A8476]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
   > 	at fr.pilato.elasticsearch.crawler.fs.test.integration.FsCrawlerTestDatesIT.compareHits(FsCrawlerTestDatesIT.java:105)
   > 	at fr.pilato.elasticsearch.crawler.fs.test.integration.FsCrawlerTestDatesIT.test_check_dates(FsCrawlerTestDatesIT.java:84)
```

**Comment by dadoonet** [comment]
Duplicate of #757
