### ISSUE TITLE
Race error in FsCrawlerTestDatesIT

### ISSUE THREAD

**Issue by dadoonet** [dadoonet/fscrawler#757]
Got an error from `fr.pilato.elasticsearch.crawler.fs.test.integration.FsCrawlerTestDatesIT.test_check_dates` test.

It looks like a racing error:

```
  2> mvn integration-test -Dtests.seed=44529D501CD604E5 -Dtests.class=fr.pilato.elasticsearch.crawler.fs.test.integration.FsCrawlerTestDatesIT -Dtests.method="test_check_dates" -Dtests.locale=nl -Dtests.timezone=Africa/Douala
FAILURE 13.7s | FsCrawlerTestDatesIT.test_check_dates <<<
   > Throwable #1: java.lang.AssertionError: 
   > Expected: not "2019-06-02T13:32:34.581+0000"
   >      but: was "2019-06-02T13:32:34.581+0000"
   > 	at __randomizedtesting.SeedInfo.seed([44529D501CD604E5:FBFD01D0CE04F5DB]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
   > 	at fr.pilato.elasticsearch.crawler.fs.test.integration.FsCrawlerTestDatesIT.compareHits(FsCrawlerTestDatesIT.java:109)
   > 	at fr.pilato.elasticsearch.crawler.fs.test.integration.FsCrawlerTestDatesIT.test_check_dates(FsCrawlerTestDatesIT.java:85)
   > 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   > 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   > 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   > 	at java.lang.reflect.Method.invoke(Method.java:498)
   > 	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
   > 	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
   > 	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
   > 	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
   > 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
   > 	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
   > 	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
   > 	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
   > 	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
   > 	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
   > 	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
   > 	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
   > 	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
   > 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
   > 	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
   > 	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
   > 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by dadoonet** [comment]
Let's see if we should always wait as described here https://discuss.elastic.co/t/does-elastic-searchs-acknowledged-means-actually-created/216608/3
