### ISSUE TITLE
Job settings exist but are not applied

### ISSUE THREAD

**Issue by supermuesli** [dadoonet/fscrawler#821]
**Describe the bug**

I am running two Elasticsearch servers on a single machine, one of which is version 7.0.2 and the other is version 7.3.2. Both run on different ports, namely 9200 and 9301. I want to use fscrawler-es7-2.7-SNAPSHOT on the instance that runs on port 9301. To achieve this I provide the job settings for *benchmark_test* in the default directory *~/.fscrawler/benchmark_test/_settings.yaml*. However, when I start the fscrawler instance, the provided job settings are ignored and replaced by the default settings. This causes the fscrawler to run on port 9200 instead of port 9301.

**To Reproduce**

Assume an Elasticsearch 7.0.2 instance is already running on the default port 9200. To start another instance of version 7.3.2, I run

```
./elasticsearch-7.3.2/bin/elasticsearch -E http.port=9301 -E transport.tcp.port=9401
```

. Once that instance is up and running, I extract the fscrawler into elasticsearch-7.3.2/ and then run

```
./elasticsearch-7.3.2/fscrawler-es7-2.7-SNAPSHOT/bin/fscrawler benchmark_test --trace
```

which produces the following log:

```
01:56:25,919 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [2/_settings.json] already exists
01:56:25,921 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [2/_settings_folder.json] already exists
01:56:25,921 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [5/_settings.json] already exists
01:56:25,921 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [5/_settings_folder.json] already exists
01:56:25,921 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [6/_settings.json] already exists
01:56:25,921 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [6/_settings_folder.json] already exists
01:56:25,921 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [7/_settings.json] already exists
01:56:25,921 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [7/_settings_folder.json] already exists
01:56:25,922 DEBUG [f.p.e.c.f.c.FsCrawlerCli] Cleaning existing status for job [benchmark_test]...
01:56:25,923 DEBUG [f.p.e.c.f.c.FsCrawlerCli] Starting job [benchmark_test]...
01:56:26,198 TRACE [f.p.e.c.f.c.FsCrawlerCli] settings used for this crawler: [---
name: "benchmark_test"
fs:
  url: "/tmp/es"
  update_rate: "15m"
  excludes:
  - "*/~*"
  json_support: false
  filename_as_id: false
  add_filesize: true
  remove_deleted: true
  add_as_inner_object: false
  store_source: false
  index_content: true
  attributes_support: false
  raw_metadata: false
  xml_support: false
  index_folders: true
  lang_detect: false
  continue_on_error: false
  ocr:
    language: "eng"
    enabled: true
    pdf_strategy: "ocr_and_text"
  follow_symlinks: false
elasticsearch:
  nodes:
  - url: "http://127.0.0.1:9200"
  bulk_size: 100
  flush_interval: "5s"
  byte_size: "10mb"
]
01:56:26,201 DEBUG [f.p.e.c.f.c.ElasticsearchClientUtil] Trying to find a client version 7
01:56:26,201 TRACE [f.p.e.c.f.c.ElasticsearchClientUtil] Trying to find a class named [fr.pilato.elasticsearch.crawler.fs.client.v7.ElasticsearchClientV7]
01:56:26,206 TRACE [f.p.e.c.f.c.ElasticsearchClientUtil] Found [fr.pilato.elasticsearch.crawler.fs.client.v7.ElasticsearchClientV7] class as the elasticsearch client implementation.
01:56:26,625 WARN  [f.p.e.c.f.c.v.ElasticsearchClientV7] failed to create elasticsearch client, disabling crawler...
01:56:26,626 FATAL [f.p.e.c.f.c.FsCrawlerCli] We can not start Elasticsearch Client. Exiting.
org.elasticsearch.ElasticsearchStatusException: Elasticsearch exception [type=security_exception, reason=missing authentication token for REST request [/]]
        at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:177) ~[elasticsearch-7.2.0.jar:7.2.0]
        at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:1721) ~[elasticsearch-rest-high-level-client-7.2.0.jar:7.2.0]
        at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:1698) ~[elasticsearch-rest-high-level-client-7.2.0.jar:7.2.0]
        at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1461) ~[elasticsearch-rest-high-level-client-7.2.0.jar:7.2.0]
        at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1433) ~[elasticsearch-rest-high-level-client-7.2.0.jar:7.2.0]
        at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1400) ~[elasticsearch-rest-high-level-client-7.2.0.jar:7.2.0]
        at org.elasticsearch.client.RestHighLevelClient.info(RestHighLevelClient.java:702) ~[elasticsearch-rest-high-level-client-7.2.0.jar:7.2.0]
        at fr.pilato.elasticsearch.crawler.fs.client.v7.ElasticsearchClientV7.getVersion(ElasticsearchClientV7.java:169) ~[fscrawler-elasticsearch-client-v7-2.7-SNAPSHOT.jar:?]
        at fr.pilato.elasticsearch.crawler.fs.client.ElasticsearchClient.checkVersion(ElasticsearchClient.java:199) ~[fscrawler-elasticsearch-client-base-2.7-SNAPSHOT.jar:?]
        at fr.pilato.elasticsearch.crawler.fs.client.v7.ElasticsearchClientV7.start(ElasticsearchClientV7.java:142) ~[fscrawler-elasticsearch-client-v7-2.7-SNAPSHOT.jar:?]
        at fr.pilato.elasticsearch.crawler.fs.cli.FsCrawlerCli.main(FsCrawlerCli.java:263) [fscrawler-cli-2.7-SNAPSHOT.jar:?]
        Suppressed: org.elasticsearch.client.ResponseException: method [GET], host [http://127.0.0.1:9200], URI [/], status line [HTTP/1.1 401 Unauthorized]
{"error":{"root_cause":[{"type":"security_exception","reason":"missing authentication token for REST request [/]","header":{"WWW-Authenticate":"Basic realm=\"security\" charset=\"UTF-8\""}}],"type":"security_exception","reason":"missing authentication token for REST request [/]","header":{"WWW-Authenticate":"Basic realm=\"security\" charset=\"UTF-8\""}},"status":401}
                at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:260) ~[elasticsearch-rest-client-7.2.0.jar:7.2.0]
                at org.elasticsearch.client.RestClient.performRequest(RestClient.java:238) ~[elasticsearch-rest-client-7.2.0.jar:7.2.0]
                at org.elasticsearch.client.RestClient.performRequest(RestClient.java:212) ~[elasticsearch-rest-client-7.2.0.jar:7.2.0]
                at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1448) ~[elasticsearch-rest-high-level-client-7.2.0.jar:7.2.0]
                at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1433) ~[elasticsearch-rest-high-level-client-7.2.0.jar:7.2.0]
                at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1400) ~[elasticsearch-rest-high-level-client-7.2.0.jar:7.2.0]
                at org.elasticsearch.client.RestHighLevelClient.info(RestHighLevelClient.java:702) ~[elasticsearch-rest-high-level-client-7.2.0.jar:7.2.0]
                at fr.pilato.elasticsearch.crawler.fs.client.v7.ElasticsearchClientV7.getVersion(ElasticsearchClientV7.java:169) ~[fscrawler-elasticsearch-client-v7-2.7-SNAPSHOT.jar:?]
                at fr.pilato.elasticsearch.crawler.fs.client.ElasticsearchClient.checkVersion(ElasticsearchClient.java:199) ~[fscrawler-elasticsearch-client-base-2.7-SNAPSHOT.jar:?]
                at fr.pilato.elasticsearch.crawler.fs.client.v7.ElasticsearchClientV7.start(ElasticsearchClientV7.java:142) ~[fscrawler-elasticsearch-client-v7-2.7-SNAPSHOT.jar:?]
                at fr.pilato.elasticsearch.crawler.fs.cli.FsCrawlerCli.main(FsCrawlerCli.java:263) [fscrawler-cli-2.7-SNAPSHOT.jar:?]
01:56:26,629 DEBUG [f.p.e.c.f.FsCrawlerImpl] Closing FS crawler [benchmark_test]
01:56:26,629 DEBUG [f.p.e.c.f.c.v.ElasticsearchClientV7] Closing Elasticsearch client manager
01:56:26,630 DEBUG [f.p.e.c.f.FsCrawlerImpl] ES Client Manager stopped
01:56:26,630 INFO  [f.p.e.c.f.FsCrawlerImpl] FS crawler [benchmark_test] stopped
```

Fscrawler tries to bind to the Elastsicsearch instance on port 9200, which requires authentification, thus the error. This happens since the provided job settings are apparently ignored. *~/.fscrawler/benchmark_test/_settings.yaml* looks like this:

```
---
name: "benchmark_test"
fs:
  url: "/tmp/es"
  update_rate: "1m"
  excludes:
  - "*/~*"
  json_support: false
  filename_as_id: false
  add_filesize: true
  remove_deleted: true
  add_as_inner_object: false
  store_source: false
  index_content: true
  attributes_support: false
  raw_metadata: false
  xml_support: false
  index_folders: true
  lang_detect: false
  continue_on_error: false
  ocr:
    language: "eng"
    enabled: true
    pdf_strategy: "ocr_and_text"
  follow_symlinks: false
elasticsearch:
  nodes:
  - url: "http://127.0.0.1:9301"
  bulk_size: 100
  flush_interval: "5s"
  byte_size: "10mb"
```

**Versions:**

 - OS: CentOs7 
 - Elasticsearch 7.0.2
 - Elasticsearch 7.3.2
 - Fscrawler-es7-2.7-SNAPSHOT

**Comment by supermuesli** [comment]
Found the problem. I accidently ran fscrawler with sudo like so:

```
sudo ./elasticsearch-7.3.2/fscrawler-es7-2.7-SNAPSHOT/bin/fscrawler benchmark_test --trace
```

. Note that I was operating as a user different from *root*, lets say *test_user*. This caused fscrawler to look for the default settings in the root directory of user *root* instead of user *test_user*. Thus, no settings were found and applied. Running without sudo solved the issue.

```
./elasticsearch-7.3.2/fscrawler-es7-2.7-SNAPSHOT/bin/fscrawler benchmark_test --trace
```
