### ISSUE TITLE
Cannot find Elasticsearch Client

### ISSUE THREAD

**Issue by LeonieVS** [dadoonet/fscrawler#853]
```
12:08:27,138 WARN  [f.p.e.c.f.c.v.ElasticsearchClientV7] failed to create elasticsearch client, disabling crawler...
12:08:27,138 FATAL [f.p.e.c.f.c.FsCrawlerCli] We can not start Elasticsearch Client. Exiting.
java.lang.IllegalArgumentException: HTTP Host may not be null
        at org.apache.http.util.Args.containsNoBlanks(Args.java:81) ~[httpcore-4.4.11.jar:4.4.11]
        at org.apache.http.HttpHost.create(HttpHost.java:108) ~[httpcore-4.4.11.jar:4.4.11]
        at fr.pilato.elasticsearch.crawler.fs.client.v7.ElasticsearchClientV7.lambda$buildRestClient$1(ElasticsearchClientV7.java:385) ~[fscrawler-elasticsearch-client-v7-2.7-SNAPSHOT.jar:?]
        at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_71]
        at fr.pilato.elasticsearch.crawler.fs.client.v7.ElasticsearchClientV7.buildRestClient(ElasticsearchClientV7.java:385) ~[fscrawler-elasticsearch-client-v7-2.7-SNAPSHOT.jar:?]
        at fr.pilato.elasticsearch.crawler.fs.client.v7.ElasticsearchClientV7.start(ElasticsearchClientV7.java:141) ~[fscrawler-elasticsearch-client-v7-2.7-SNAPSHOT.jar:?]
        at fr.pilato.elasticsearch.crawler.fs.cli.FsCrawlerCli.main(FsCrawlerCli.java:263) [fscrawler-cli-2.7-SNAPSHOT.jar:?]
12:08:27,138 INFO  [f.p.e.c.f.FsCrawlerImpl] FS crawler [first_crawl] stopped
12:08:27,154 INFO  [f.p.e.c.f.FsCrawlerImpl] FS crawler [first_crawl] stopped
```

I get the above error when trying to reindex the tmp/es folder into the first_crawl index using the FS-es7-2.7 SNAPSHOT from October 24 2019. 

Elasticsearch version 7.4.2 is running at the same time as this error is happening, all locally on the same Windows 10 machine. I'm rather new to ES, I got fscrawler to work previously, but since installing Tesseract for OCR I get this error. I have specified the path to Tesseract.exe and Tessdata but still no difference.

**Comment by dadoonet** [comment]
Could you share your FSCrawler job settings?

**Comment by dadoonet** [comment]
No feedback. I'm closing. Please add details if any.

**Comment by aabid0193** [comment]
Hi I'm having this issue as well and I know it was closed. I am trying to connect to an instance of elasticsearch that requires connection through a vpn where i am getting the following error

```
13:07:07,287 INFO  [f.p.e.c.f.c.BootstrapChecks] Memory [Free/Total=Percent]: HEAP [124mb/2gb=6.02%], RAM [4.4gb/8.3gb=54.06%], Swap [3.9gb/3.9gb=100.0%].
13:07:08,095 WARN  [f.p.e.c.f.c.v.ElasticsearchClientV7] failed to create elasticsearch client, disabling crawler...
13:07:08,097 FATAL [f.p.e.c.f.c.FsCrawlerCli] We can not start Elasticsearch Client. Exiting.
java.lang.IllegalArgumentException: HTTP Host may not be null
	at org.apache.http.util.Args.containsNoBlanks(Args.java:81) ~[httpcore-4.4.13.jar:4.4.13]
	at org.apache.http.HttpHost.create(HttpHost.java:108) ~[httpcore-4.4.13.jar:4.4.13]
	at fr.pilato.elasticsearch.crawler.fs.client.v7.ElasticsearchClientV7.lambda$buildRestClient$1(ElasticsearchClientV7.java:385) ~[fscrawler-elasticsearch-client-v7-2.7-SNAPSHOT.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_252]
	at fr.pilato.elasticsearch.crawler.fs.client.v7.ElasticsearchClientV7.buildRestClient(ElasticsearchClientV7.java:385) ~[fscrawler-elasticsearch-client-v7-2.7-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.client.v7.ElasticsearchClientV7.start(ElasticsearchClientV7.java:141) ~[fscrawler-elasticsearch-client-v7-2.7-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.cli.FsCrawlerCli.main(FsCrawlerCli.java:257) [fscrawler-cli-2.7-SNAPSHOT.jar:?]
13:07:08,107 INFO  [f.p.e.c.f.FsCrawlerImpl] FS crawler [resumes] stopped
13:07:08,110 INFO  [f.p.e.c.f.FsCrawlerImpl] FS crawler [resumes] stopped
```
   
   
   
The _settings.json folder is below.

```
---
name: "resumes"
fs:
  url: "path/to/resumes"
  update_rate: "1m"
  excludes:
  - "*/~*"
  - "*.swp"
  json_support: false
  filename_as_id: false
  add_filesize: true
  remove_deleted: false
  add_as_inner_object: false
  store_source: false
  index_content: true
  attributes_support: false
  raw_metadata: false
  xml_support: false
  index_folders: true
  lang_detect: true
  continue_on_error: true
  ocr:
    language: "eng"
    enabled: true
    pdf_strategy: "ocr_and_text"
  follow_symlinks: false
elasticsearch:
  nodes:
  - host: ""
  - port: 9220
  - username : "username"
  - password : "password"
  - scheme: "https"
  - ssl_show_warn: False
  - verify_certs: False
  - use_ssl: True
  bulk_size: 100
```

The port 9220 is where the elasticsearch instance of siren runs.

Siren container: https://hub.docker.com/r/sirensolutions/siren-platform

**Comment by dadoonet** [comment]
You can't have an empty host:

    host: ""

Use localhost or the ip

**Comment by aabid0193** [comment]
Yes I had the ip, just didn't add it to that comment, sorry. Adding the ip/localhost did not resolve the issue

```
---
name: "resumes"
fs:
  url: "path/to/resumes"
  update_rate: "1m"
  excludes:
  - "*/~*"
  - "*.swp"
  json_support: false
  filename_as_id: false
  add_filesize: true
  remove_deleted: false
  add_as_inner_object: false
  store_source: false
  index_content: true
  attributes_support: false
  raw_metadata: false
  xml_support: false
  index_folders: true
  lang_detect: true
  continue_on_error: true
  ocr:
    language: "eng"
    enabled: true
    pdf_strategy: "ocr_and_text"
  follow_symlinks: false
elasticsearch:
  nodes:
  - host: "localhost"
  - port: 9220
  - username : "username"
  - password : "password"
  - scheme: "https"
  - ssl_show_warn: False
  - verify_certs: False
  - use_ssl: True
  bulk_size: 100
```

**Comment by dadoonet** [comment]
What is the error message then?

**Comment by aabid0193** [comment]
same error

```
13:31:31,002 INFO  [f.p.e.c.f.c.BootstrapChecks] Memory [Free/Total=Percent]: HEAP [124.2mb/2gb=6.03%], RAM [4.4gb/8.3gb=53.96%], Swap [3.9gb/3.9gb=100.0%].
13:31:31,900 WARN  [f.p.e.c.f.c.v.ElasticsearchClientV7] failed to create elasticsearch client, disabling crawler...
13:31:31,901 FATAL [f.p.e.c.f.c.FsCrawlerCli] We can not start Elasticsearch Client. Exiting.
java.lang.IllegalArgumentException: HTTP Host may not be null
	at org.apache.http.util.Args.containsNoBlanks(Args.java:81) ~[httpcore-4.4.13.jar:4.4.13]
	at org.apache.http.HttpHost.create(HttpHost.java:108) ~[httpcore-4.4.13.jar:4.4.13]
	at fr.pilato.elasticsearch.crawler.fs.client.v7.ElasticsearchClientV7.lambda$buildRestClient$1(ElasticsearchClientV7.java:385) ~[fscrawler-elasticsearch-client-v7-2.7-SNAPSHOT.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_252]
	at fr.pilato.elasticsearch.crawler.fs.client.v7.ElasticsearchClientV7.buildRestClient(ElasticsearchClientV7.java:385) ~[fscrawler-elasticsearch-client-v7-2.7-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.client.v7.ElasticsearchClientV7.start(ElasticsearchClientV7.java:141) ~[fscrawler-elasticsearch-client-v7-2.7-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.cli.FsCrawlerCli.main(FsCrawlerCli.java:257) [fscrawler-cli-2.7-SNAPSHOT.jar:?]
```

**Comment by dadoonet** [comment]
Look at the docs and how to define a node: https://fscrawler.readthedocs.io/en/latest/admin/fs/elasticsearch.html

**Comment by aabid0193** [comment]
I see there was an issue with how I was configuring the node. Now I am running into an SSL error:
```
14:21:13,460 INFO  [f.p.e.c.f.c.BootstrapChecks] Memory [Free/Total=Percent]: HEAP [124mb/2gb=6.02%], RAM [4.2gb/8.3gb=50.89%], Swap [3.9gb/3.9gb=100.0%].
14:21:15,891 WARN  [f.p.e.c.f.c.v.ElasticsearchClientV7] failed to create elasticsearch client, disabling crawler...
14:21:15,897 FATAL [f.p.e.c.f.c.FsCrawlerCli] We can not start Elasticsearch Client. Exiting.
javax.net.ssl.SSLHandshakeException: General SSLEngine problem
	at org.elasticsearch.client.RestClient.extractAndWrapCause(RestClient.java:818) ~[elasticsearch-rest-client-7.6.1.jar:7.6.1]
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:248) ~[elasticsearch-rest-client-7.6.1.jar:7.6.1]
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:235) ~[elasticsearch-rest-client-7.6.1.jar:7.6.1]
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1514) ~[elasticsearch-rest-high-level-client-7.6.1.jar:7.6.1]
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1499) ~[elasticsearch-rest-high-level-client-7.6.1.jar:7.6.1]
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1466) ~[elasticsearch-rest-high-level-client-7.6.1.jar:7.6.1]
	at org.elasticsearch.client.RestHighLevelClient.info(RestHighLevelClient.java:730) ~[elasticsearch-rest-high-level-client-7.6.1.jar:7.6.1]
	at fr.pilato.elasticsearch.crawler.fs.client.v7.ElasticsearchClientV7.getVersion(ElasticsearchClientV7.java:169) ~[fscrawler-elasticsearch-client-v7-2.7-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.client.ElasticsearchClient.checkVersion(ElasticsearchClient.java:181) ~[fscrawler-elasticsearch-client-base-2.7-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.client.v7.ElasticsearchClientV7.start(ElasticsearchClientV7.java:142) ~[fscrawler-elasticsearch-client-v7-2.7-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.cli.FsCrawlerCli.main(FsCrawlerCli.java:257) [fscrawler-cli-2.7-SNAPSHOT.jar:?]
Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
	at sun.security.ssl.Handshaker.checkThrown(Handshaker.java:1566) ~[?:1.8.0_252]
	at sun.security.ssl.SSLEngineImpl.checkTaskThrown(SSLEngineImpl.java:545) ~[?:1.8.0_252]
	at sun.security.ssl.SSLEngineImpl.writeAppRecord(SSLEngineImpl.java:1217) ~[?:1.8.0_252]
	at sun.security.ssl.SSLEngineImpl.wrap(SSLEngineImpl.java:1185) ~[?:1.8.0_252]
	at javax.net.ssl.SSLEngine.wrap(SSLEngine.java:471) ~[?:1.8.0_252]
	at org.apache.http.nio.reactor.ssl.SSLIOSession.doWrap(SSLIOSession.java:270) ~[httpcore-nio-4.4.13.jar:4.4.13]
	at org.apache.http.nio.reactor.ssl.SSLIOSession.doHandshake(SSLIOSession.java:316) ~[httpcore-nio-4.4.13.jar:4.4.13]
	at org.apache.http.nio.reactor.ssl.SSLIOSession.isAppInputReady(SSLIOSession.java:537) ~[httpcore-nio-4.4.13.jar:4.4.13]
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:120) ~[httpcore-nio-4.4.13.jar:4.4.13]
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162) ~[httpcore-nio-4.4.13.jar:4.4.13]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337) ~[httpcore-nio-4.4.13.jar:4.4.13]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315) ~[httpcore-nio-4.4.13.jar:4.4.13]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276) ~[httpcore-nio-4.4.13.jar:4.4.13]
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104) ~[httpcore-nio-4.4.13.jar:4.4.13]
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591) ~[httpcore-nio-4.4.13.jar:4.4.13]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_252]
Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:198) ~[?:1.8.0_252]
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1729) ~[?:1.8.0_252]
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:333) ~[?:1.8.0_252]
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:325) ~[?:1.8.0_252]
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1688) ~[?:1.8.0_252]
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:226) ~[?:1.8.0_252]
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1082) ~[?:1.8.0_252]
	at sun.security.ssl.Handshaker$1.run(Handshaker.java:1015) ~[?:1.8.0_252]
	at sun.security.ssl.Handshaker$1.run(Handshaker.java:1012) ~[?:1.8.0_252]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_252]
	at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1504) ~[?:1.8.0_252]
	at org.apache.http.nio.reactor.ssl.SSLIOSession.doRunTask(SSLIOSession.java:288) ~[httpcore-nio-4.4.13.jar:4.4.13]
	at org.apache.http.nio.reactor.ssl.SSLIOSession.doHandshake(SSLIOSession.java:356) ~[httpcore-nio-4.4.13.jar:4.4.13]
	at org.apache.http.nio.reactor.ssl.SSLIOSession.isAppInputReady(SSLIOSession.java:537) ~[httpcore-nio-4.4.13.jar:4.4.13]
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:120) ~[httpcore-nio-4.4.13.jar:4.4.13]
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162) ~[httpcore-nio-4.4.13.jar:4.4.13]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337) ~[httpcore-nio-4.4.13.jar:4.4.13]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315) ~[httpcore-nio-4.4.13.jar:4.4.13]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276) ~[httpcore-nio-4.4.13.jar:4.4.13]
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104) ~[httpcore-nio-4.4.13.jar:4.4.13]
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591) ~[httpcore-nio-4.4.13.jar:4.4.13]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_252]
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:450) ~[?:1.8.0_252]
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:317) ~[?:1.8.0_252]
	at sun.security.validator.Validator.validate(Validator.java:262) ~[?:1.8.0_252]
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:330) ~[?:1.8.0_252]
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:289) ~[?:1.8.0_252]
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:144) ~[?:1.8.0_252]
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1675) ~[?:1.8.0_252]
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:226) ~[?:1.8.0_252]
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1082) ~[?:1.8.0_252]
	at sun.security.ssl.Handshaker$1.run(Handshaker.java:1015) ~[?:1.8.0_252]
	at sun.security.ssl.Handshaker$1.run(Handshaker.java:1012) ~[?:1.8.0_252]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_252]
	at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1504) ~[?:1.8.0_252]
	at org.apache.http.nio.reactor.ssl.SSLIOSession.doRunTask(SSLIOSession.java:288) ~[httpcore-nio-4.4.13.jar:4.4.13]
	at org.apache.http.nio.reactor.ssl.SSLIOSession.doHandshake(SSLIOSession.java:356) ~[httpcore-nio-4.4.13.jar:4.4.13]
	at org.apache.http.nio.reactor.ssl.SSLIOSession.isAppInputReady(SSLIOSession.java:537) ~[httpcore-nio-4.4.13.jar:4.4.13]
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:120) ~[httpcore-nio-4.4.13.jar:4.4.13]
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162) ~[httpcore-nio-4.4.13.jar:4.4.13]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337) ~[httpcore-nio-4.4.13.jar:4.4.13]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315) ~[httpcore-nio-4.4.13.jar:4.4.13]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276) ~[httpcore-nio-4.4.13.jar:4.4.13]
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104) ~[httpcore-nio-4.4.13.jar:4.4.13]
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591) ~[httpcore-nio-4.4.13.jar:4.4.13]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_252]
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141) ~[?:1.8.0_252]
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126) ~[?:1.8.0_252]
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280) ~[?:1.8.0_252]
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:445) ~[?:1.8.0_252]
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:317) ~[?:1.8.0_252]
	at sun.security.validator.Validator.validate(Validator.java:262) ~[?:1.8.0_252]
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:330) ~[?:1.8.0_252]
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:289) ~[?:1.8.0_252]
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:144) ~[?:1.8.0_252]
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1675) ~[?:1.8.0_252]
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:226) ~[?:1.8.0_252]
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1082) ~[?:1.8.0_252]
	at sun.security.ssl.Handshaker$1.run(Handshaker.java:1015) ~[?:1.8.0_252]
	at sun.security.ssl.Handshaker$1.run(Handshaker.java:1012) ~[?:1.8.0_252]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_252]
	at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1504) ~[?:1.8.0_252]
	at org.apache.http.nio.reactor.ssl.SSLIOSession.doRunTask(SSLIOSession.java:288) ~[httpcore-nio-4.4.13.jar:4.4.13]
	at org.apache.http.nio.reactor.ssl.SSLIOSession.doHandshake(SSLIOSession.java:356) ~[httpcore-nio-4.4.13.jar:4.4.13]
	at org.apache.http.nio.reactor.ssl.SSLIOSession.isAppInputReady(SSLIOSession.java:537) ~[httpcore-nio-4.4.13.jar:4.4.13]
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:120) ~[httpcore-nio-4.4.13.jar:4.4.13]
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162) ~[httpcore-nio-4.4.13.jar:4.4.13]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337) ~[httpcore-nio-4.4.13.jar:4.4.13]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315) ~[httpcore-nio-4.4.13.jar:4.4.13]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276) ~[httpcore-nio-4.4.13.jar:4.4.13]
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104) ~[httpcore-nio-4.4.13.jar:4.4.13]
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591) ~[httpcore-nio-4.4.13.jar:4.4.13]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_252]
14:21:15,919 INFO  [f.p.e.c.f.FsCrawlerImpl] FS crawler [resumes] stopped
14:21:15,920 INFO  [f.p.e.c.f.FsCrawlerImpl] FS crawler [resumes] stopped

```

I know I can configure the CA certificates as mentioned in the docs below.
https://fscrawler.readthedocs.io/en/latest/admin/fs/elasticsearch.html?highlight=certificate#ssl-configuration.

But my question is, is there a way to set certificate verification to false, I don't see this is the documentation, but using something like setting verify_certs and/or ca_certs to false as shown in the __settings.yaml_ file below:

```
---
name: "resumes"
fs:
  url: "/home/student/resumes"
  update_rate: "1m"
  excludes:
  - "*/~*"
  - "*.swp"
  json_support: false
  filename_as_id: false
  add_filesize: true
  remove_deleted: false
  add_as_inner_object: false
  store_source: false
  index_content: true
  attributes_support: false
  raw_metadata: false
  xml_support: false
  index_folders: true
  lang_detect: true
  continue_on_error: true
  ocr:
    language: "eng"
    enabled: true
    pdf_strategy: "ocr_and_text"
  follow_symlinks: false
elasticsearch:
  nodes:
  - url: "https://10.71.2.132:9220"
  ca_certs: False
  verify_certs: False
  username : "sirenadmin"
  password : "password"
  bulk_size: 100
  flush_interval: "5s"
  byte_size: "10mb"
```

**Comment by aabid0193** [comment]
I think this is related to https://github.com/dadoonet/fscrawler/issues/928
This is still an open issue..
