### ISSUE TITLE
How to use with Amazon Elasticsearch Service

### ISSUE THREAD

**Issue by DaLiangLee** [dadoonet/fscrawler#854]
_settings.yaml
```
---
name: "job_name"
fs:
  url: "\\tmp\\es"
  update_rate: "15m"
  includes:
  - "*/*.doc"
  - "*/*.docx"
  - "*/*.pdf"
  - "*/*.xlsx"
  - "*/*.pub"
  excludes:
  - "*/~*"
  json_support: false
  filename_as_id: false
  add_filesize: true
  remove_deleted: true
  add_as_inner_object: false
  store_source: false
  index_content: true
  attributes_support: false
  raw_metadata: false
  xml_support: false
  index_folders: true
  lang_detect: false
  continue_on_error: false
  ocr:
    language: "eng"
    enabled: true
    pdf_strategy: "ocr_and_text"
  follow_symlinks: false
elasticsearch:
  nodes:
  - url: "https://vpc-xxxxxxxxxxxxxxxxxxx.es.amazonaws.com"
  bulk_size: 100
  flush_interval: "5s"
  byte_size: "10mb"
```

message

```
[AAAAAAA fscrawler-es7-2.7-SNAPSHOT]$ bin/fscrawler job_name
07:01:39,516 INFO  [f.p.e.c.f.c.BootstrapChecks] Memory [Free/Total=Percent]: HEAP [41.8mb/880mb=4.75%], RAM [1.2gb/3.8gb=32.37%], Swap [0b/0b=0.0].
07:01:40,352 WARN  [f.p.e.c.f.c.v.ElasticsearchClientV7] failed to create elasticsearch client, disabling crawler...
07:01:40,352 FATAL [f.p.e.c.f.c.FsCrawlerCli] We can not start Elasticsearch Client. Exiting.
java.net.ConnectException: Connection refused
        at org.elasticsearch.client.RestClient.extractAndWrapCause(RestClient.java:788) ~[elasticsearch-rest-client-7.4.1.jar:7.4.1]
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:218) ~[elasticsearch-rest-client-7.4.1.jar:7.4.1]
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:205) ~[elasticsearch-rest-client-7.4.1.jar:7.4.1]
        at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1454) ~[elasticsearch-rest-high-level-client-7.4.1.jar:7.4.1]
        at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1439) ~[elasticsearch-rest-high-level-client-7.4.1.jar:7.4.1]
        at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1406) ~[elasticsearch-rest-high-level-client-7.4.1.jar:7.4.1]
        at org.elasticsearch.client.RestHighLevelClient.info(RestHighLevelClient.java:702) ~[elasticsearch-rest-high-level-client-7.4.1.jar:7.4.1]
        at fr.pilato.elasticsearch.crawler.fs.client.v7.ElasticsearchClientV7.getVersion(ElasticsearchClientV7.java:169) ~[fscrawler-elasticsearch-client-v7-2.7-SNAPSHOT.jar:?]
        at fr.pilato.elasticsearch.crawler.fs.client.ElasticsearchClient.checkVersion(ElasticsearchClient.java:199) ~[fscrawler-elasticsearch-client-base-2.7-SNAPSHOT.jar:?]
        at fr.pilato.elasticsearch.crawler.fs.client.v7.ElasticsearchClientV7.start(ElasticsearchClientV7.java:142) ~[fscrawler-elasticsearch-client-v7-2.7-SNAPSHOT.jar:?]
        at fr.pilato.elasticsearch.crawler.fs.cli.FsCrawlerCli.main(FsCrawlerCli.java:263) [fscrawler-cli-2.7-SNAPSHOT.jar:?]
Caused by: java.net.ConnectException: Connection refused
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:1.8.0_222]
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:1.8.0_222]
        at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvent(DefaultConnectingIOReactor.java:171) ~[httpcore-nio-4.4.11.jar:4.4.11]
        at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:145) ~[httpcore-nio-4.4.11.jar:4.4.11]
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:351) ~[httpcore-nio-4.4.11.jar:4.4.11]
        at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:221) ~[httpasyncclient-4.1.4.jar:4.1.4]
        at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64) ~[httpasyncclient-4.1.4.jar:4.1.4]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_222]
07:01:40,357 INFO  [f.p.e.c.f.FsCrawlerImpl] FS crawler [job_name] stopped
[AAAAAAA fscrawler-es7-2.7-SNAPSHOT]$
```

Please help!!

**Comment by DaLiangLee** [comment]
I have been searching on Google for a long time and have not found any similar problems，a frustrating day

**Comment by dadoonet** [comment]
I don't know AWS Elasticsearch as I'm always using the official service https://cloud.elastic.co which is also available from the marketplace https://aws.amazon.com/marketplace/pp/B01N6YCISK.

Cloud by elastic is one way to have access to all features, all managed by us. Think about what is there yet like Security, Monitoring, Reporting, SQL, Canvas, APM, Logs UI, Infra UI, SIEM, Maps UI and what is coming next :) ...

Is your AWS Elasticsearch cluster available?
May be some APIs in AWS service are not available? Could you run it with `--trace` option?

**Comment by DaLiangLee** [comment]
> 我不知道AWS Elasticsearch，因为我一直在使用官方服务https://cloud.elastic.co，该服务也可以从市场[https://aws.amazon.com/marketplace/pp/B01N6YCISK获得](https://aws.amazon.com/marketplace/pp/B01N6YCISK)。
> 
> 弹性云是一种访问所有功能（由我们管理）的一种方式。考虑一下安全性，监视，报告，SQL，Canvas，APM，Logs UI，Infra UI，SIEM，Maps UI以及接下来将要发生的事情:) ...
> 
> 您的AWS Elasticsearch集群可用吗？
> 可能AWS服务中的某些API不可用？您可以`--trace`选择运行它吗？

Fscrawler can't connect aws elasticsearch service...

`[developer@ip-fscrawler-es7-2.7-SNAPSHOT]$ bin/fscrawler job_name --trace
04:27:55,281 INFO  [f.p.e.c.f.c.BootstrapChecks] Memory [Free/Total=Percent]: HEAP [42.2mb/880mb=4.8%], RAM [1.3gb/3.8gb=35.06%], Swap [0b/0b=0.0].
04:27:55,288 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [2/_settings.json] already exists
04:27:55,288 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [2/_settings_folder.json] already exists
04:27:55,288 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [5/_settings.json] already exists
04:27:55,288 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [5/_settings_folder.json] already exists
04:27:55,288 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [6/_settings.json] already exists
04:27:55,288 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [6/_settings_folder.json] already exists
04:27:55,288 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [7/_settings.json] already exists
04:27:55,288 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [7/_settings_folder.json] already exists
04:27:55,289 DEBUG [f.p.e.c.f.c.FsCrawlerCli] Starting job [job_name]...
04:27:55,655 TRACE [f.p.e.c.f.c.FsCrawlerCli] settings used for this crawler: [---
name: "job_name"
fs:
  url: "/tmp/es"
  update_rate: "15m"
  excludes:
  - "*/~*"
  json_support: false
  filename_as_id: false
  add_filesize: true
  remove_deleted: true
  add_as_inner_object: false
  store_source: false
  index_content: true
  attributes_support: false
  raw_metadata: false
  xml_support: false
  index_folders: true
  lang_detect: false
  continue_on_error: false
  ocr:
    language: "eng"
    enabled: true
    pdf_strategy: "ocr_and_text"
  follow_symlinks: false
elasticsearch:
  nodes:
  - url: "http://127.0.0.1:9200"
  bulk_size: 100
  flush_interval: "5s"
  byte_size: "10mb"
]
04:27:55,659 DEBUG [f.p.e.c.f.c.ElasticsearchClientUtil] Trying to find a client version 7
04:27:55,659 TRACE [f.p.e.c.f.c.ElasticsearchClientUtil] Trying to find a class named [fr.pilato.elasticsearch.crawler.fs.client.v7.ElasticsearchClientV7]
04:27:55,665 TRACE [f.p.e.c.f.c.ElasticsearchClientUtil] Found [fr.pilato.elasticsearch.crawler.fs.client.v7.ElasticsearchClientV7] class as the elasticsearch client implementation.
04:27:56,092 WARN  [f.p.e.c.f.c.v.ElasticsearchClientV7] failed to create elasticsearch client, disabling crawler...
04:27:56,092 FATAL [f.p.e.c.f.c.FsCrawlerCli] We can not start Elasticsearch Client. Exiting.
java.net.ConnectException: Connection refused
`

???
elasticsearch:
  nodes:
  - url: "http://127.0.0.1:9200"

`$ find -name '_settings*'
./test/_default/7/_settings.json
./test/_default/7/_settings_folder.json
./test/_default/5/_settings.json
./test/_default/5/_settings_folder.json
./test/_default/2/_settings.json
./test/_default/2/_settings_folder.json
./test/_default/6/_settings.json
./test/_default/6/_settings_folder.json
`
Elasticsearch nodes Why is this? I can't find the _settings.yaml file, thanks

**Comment by DaLiangLee** [comment]
Thank you！  --trace, great

**Comment by dadoonet** [comment]
Did you find the problem?

**Comment by DaLiangLee** [comment]
> Did you find the problem?

Yes, I found the problem because _setting.yaml is not configured. Since two files with the same name were generated, I did not modify the file in the .fscrawler folder.

**Comment by dadoonet** [comment]
Thanks. I'm closing the issue then.
