### ISSUE TITLE
Connection timed out

### ISSUE THREAD

**Issue by huan415201** [dadoonet/fscrawler#875]
Hi, I tried to use SSH settings, and I can't make it work, this is my _settings.yaml file:

```yaml
---
name: "ssh-demo-job"
fs:
  url: "\\AxS\\WeblibAccess"
  update_rate: "15m"
  excludes:
  - "*/~*"
  json_support: false
  filename_as_id: false
  add_filesize: true
  remove_deleted: true
  add_as_inner_object: false
  store_source: false
  index_content: true
  attributes_support: false
  raw_metadata: false
  xml_support: false
  index_folders: true
  lang_detect: false
  continue_on_error: false
  ocr:
    language: "eng"
    enabled: true
    pdf_strategy: "ocr_and_text"
  follow_symlinks: false
server:
  hostname: 192.168.72.21
  port: 22
  username: "hvhuan"
  protocol: "ssh"
elasticsearch:
  nodes:
  - url: "http://192.168.95.48:9200"
  bulk_size: 100
  flush_interval: "5s"
  byte_size: "10mb"
```

And this is the result:

```
C:\fscrawler-es7-2.7-SNAPSHOT\bin>fscrawler ssh-demo-job --loop 1
16:19:28,675 INFO  [f.p.e.c.f.c.BootstrapChecks] Memory [Free/Total=Percent]: HEAP [87.2mb/1.7gb=4.88%], RAM [2.6gb/7.8gb=34.02%], Swap [3.6gb/14.1gb=25.88%].
16:19:29,373 INFO  [f.p.e.c.f.c.v.ElasticsearchClientV7] Elasticsearch Client for version 7.x connected to a node running version 7.5.0
16:19:29,419 INFO  [f.p.e.c.f.FsCrawlerImpl] Starting FS crawler
16:19:29,551 INFO  [f.p.e.c.f.FsParserAbstract] FS crawler started for [ssh-demo-job] for [192.168.72.21/AxS/WeblibAccess] every [15m]
16:19:50,563 WARN  [f.p.e.c.f.FsParserAbstract] Error while crawling 192.168.72.21/AxS/WeblibAccess: java.net.ConnectException: Connection timed out: connect
16:19:50,565 WARN  [f.p.e.c.f.FsParserAbstract] Error while closing the connection: java.lang.NullPointerException
16:19:50,565 INFO  [f.p.e.c.f.FsParserAbstract] FS crawler is stopping after 1 run
16:19:50,631 INFO  [f.p.e.c.f.FsCrawlerImpl] FS crawler [ssh-demo-job] stopped
16:19:50,633 INFO  [f.p.e.c.f.FsCrawlerImpl] FS crawler [ssh-demo-job] stopped
```

FSCrawler: es7 2.7
Elasticsearch: 7.5.0
OS: Windows 10

**Comment by dadoonet** [comment]
Could you run the same command with `--trace` option?

```
C:\fscrawler-es7-2.7-SNAPSHOT\bin>fscrawler ssh-demo-job --loop 1 --trace
```

And share the full output here?

**Comment by huan415201** [comment]
This is the output with --trace:
```
C:\fscrawler-es7-2.7-SNAPSHOT\bin>fscrawler ssh-demo-job --loop 1 --trace
16:54:35,018 INFO  [f.p.e.c.f.c.BootstrapChecks] Memory [Free/Total=Percent]: HEAP [87.1mb/1.7gb=4.88%], RAM [2gb/7.8gb=26.72%], Swap [3.1gb/14.1gb=22.53%].
16:54:35,021 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [2/_settings.json] already exists
16:54:35,022 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [2/_settings_folder.json] already exists
16:54:35,022 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [5/_settings.json] already exists
16:54:35,023 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [5/_settings_folder.json] already exists
16:54:35,024 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [6/_settings.json] already exists
16:54:35,024 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [6/_settings_folder.json] already exists
16:54:35,025 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [7/_settings.json] already exists
16:54:35,025 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [7/_settings_folder.json] already exists
16:54:35,026 DEBUG [f.p.e.c.f.c.FsCrawlerCli] Starting job [ssh-demo-job]...
16:54:35,259 TRACE [f.p.e.c.f.c.FsCrawlerCli] settings used for this crawler: [---
name: "ssh-demo-job"
fs:
  url: "192.168.72.21/AxS/WeblibAccess"
  update_rate: "15m"
  excludes:
  - "*/~*"
  json_support: false
  filename_as_id: false
  add_filesize: true
  remove_deleted: true
  add_as_inner_object: false
  store_source: false
  index_content: true
  attributes_support: false
  raw_metadata: false
  xml_support: false
  index_folders: true
  lang_detect: false
  continue_on_error: false
  ocr:
    language: "eng"
    enabled: true
    pdf_strategy: "ocr_and_text"
  follow_symlinks: false
server:
  hostname: "192.168.72.21"
  port: 22
  username: "hvhuan"
  protocol: "ssh"
elasticsearch:
  nodes:
  - url: "http://192.168.95.48:9200"
  bulk_size: 100
  flush_interval: "5s"
  byte_size: "10mb"
]
16:54:35,263 DEBUG [f.p.e.c.f.c.ElasticsearchClientUtil] Trying to find a client version 7
16:54:35,264 TRACE [f.p.e.c.f.c.ElasticsearchClientUtil] Trying to find a class named [fr.pilato.elasticsearch.crawler.fs.client.v7.ElasticsearchClientV7]
16:54:35,275 TRACE [f.p.e.c.f.c.ElasticsearchClientUtil] Found [fr.pilato.elasticsearch.crawler.fs.client.v7.ElasticsearchClientV7] class as the elasticsearch client implementation.
16:54:35,717 INFO  [f.p.e.c.f.c.v.ElasticsearchClientV7] Elasticsearch Client for version 7.x connected to a node running version 7.5.0
16:54:35,763 INFO  [f.p.e.c.f.FsCrawlerImpl] Starting FS crawler
16:54:35,767 DEBUG [f.p.e.c.f.c.v.ElasticsearchClientV7] FS crawler connected to an elasticsearch [org.elasticsearch.client.core.MainResponse$Version@8cc81083] node.
16:54:35,768 DEBUG [f.p.e.c.f.c.v.ElasticsearchClientV7] create index [ssh-demo-job]
16:54:35,768 TRACE [f.p.e.c.f.c.v.ElasticsearchClientV7] index settings: [{
  "settings": {
    "number_of_shards": 1,
    "index.mapping.total_fields.limit": 2000,
    "analysis": {
      "analyzer": {
        "fscrawler_path": {
          "tokenizer": "fscrawler_path"
        }
      },
      "tokenizer": {
        "fscrawler_path": {
          "type": "path_hierarchy"
        }
      }
    }
  },
  "mappings": {
    "dynamic_templates": [
      {
        "raw_as_text": {
          "path_match": "meta.raw.*",
          "mapping": {
            "type": "text",
            "fields": {
              "keyword": {
                "type": "keyword",
                "ignore_above": 256
              }
            }
          }
        }
      }
    ],
    "properties": {
          "suggest-filename": {
                "type": "completion"
          },
      "attachment": {
        "type": "binary",
        "doc_values": false
      },
      "attributes": {
        "properties": {
          "group": {
            "type": "keyword"
          },
          "owner": {
            "type": "keyword"
          }
        }
      },
      "content": {
        "type": "text"
      },
      "file": {
        "properties": {
          "content_type": {
            "type": "keyword"
          },
          "filename": {
            "type": "keyword",
                        "copy_to": "suggest-filename"
          },
          "extension": {
            "type": "keyword"
          },
          "filesize": {
            "type": "long"
          },
          "indexed_chars": {
            "type": "long"
          },
          "indexing_date": {
            "type": "date",
            "format": "dateOptionalTime"
          },
          "created": {
            "type": "date",
            "format": "dateOptionalTime"
          },
          "last_modified": {
            "type": "date",
            "format": "dateOptionalTime"
          },
          "last_accessed": {
            "type": "date",
            "format": "dateOptionalTime"
          },
          "checksum": {
            "type": "keyword"
          },
          "url": {
            "type": "keyword",
            "index": false
          }
        }
      },
      "meta": {
        "properties": {
          "author": {
            "type": "text"
          },
          "date": {
            "type": "date",
            "format": "dateOptionalTime"
          },
          "keywords": {
            "type": "text"
          },
          "title": {
            "type": "text"
          },
          "language": {
            "type": "keyword"
          },
          "format": {
            "type": "text"
          },
          "identifier": {
            "type": "text"
          },
          "contributor": {
            "type": "text"
          },
          "coverage": {
            "type": "text"
          },
          "modifier": {
            "type": "text"
          },
          "creator_tool": {
            "type": "keyword"
          },
          "publisher": {
            "type": "text"
          },
          "relation": {
            "type": "text"
          },
          "rights": {
            "type": "text"
          },
          "source": {
            "type": "text"
          },
          "type": {
            "type": "text"
          },
          "description": {
            "type": "text"
          },
          "created": {
            "type": "date",
            "format": "dateOptionalTime"
          },
          "print_date": {
            "type": "date",
            "format": "dateOptionalTime"
          },
          "metadata_date": {
            "type": "date",
            "format": "dateOptionalTime"
          },
          "latitude": {
            "type": "text"
          },
          "longitude": {
            "type": "text"
          },
          "altitude": {
            "type": "text"
          },
          "rating": {
            "type": "byte"
          },
          "comments": {
            "type": "text"
          }
        }
      },
      "path": {
        "properties": {
          "real": {
            "type": "keyword",
            "fields": {
              "tree": {
                "type": "text",
                "analyzer": "fscrawler_path",
                "fielddata": true
              },
              "fulltext": {
                "type": "text"
              }
            }
          },
          "root": {
            "type": "keyword"
          },
          "virtual": {
            "type": "keyword",
            "fields": {
              "tree": {
                "type": "text",
                "analyzer": "fscrawler_path",
                "fielddata": true
              },
              "fulltext": {
                "type": "text"
              }
            }
          }
        }
      }
    }
  }
}
]
16:54:35,890 DEBUG [f.p.e.c.f.c.v.ElasticsearchClientV7] wait for yellow health on index [ssh-demo-job]
16:54:35,901 TRACE [f.p.e.c.f.c.v.ElasticsearchClientV7] health response: {"cluster_name":"app-search-docker-cluster","status":"yellow","timed_out":false,"number_of_nodes":1,"number_of_data_nodes":1,"active_primary_shards":1,"active_shards":1,"relocating_shards":0,"initializing_shards":0,"unassigned_shards":1,"delayed_unassigned_shards":0,"number_of_pending_tasks":0,"number_of_in_flight_fetch":0,"task_max_waiting_in_queue_millis":0,"active_shards_percent_as_number":78.0}
16:54:35,902 DEBUG [f.p.e.c.f.c.v.ElasticsearchClientV7] create index [ssh-demo-job_folder]
16:54:35,903 TRACE [f.p.e.c.f.c.v.ElasticsearchClientV7] index settings: [{
  "settings": {
    "analysis": {
      "analyzer": {
        "fscrawler_path": {
          "tokenizer": "fscrawler_path"
        }
      },
      "tokenizer": {
        "fscrawler_path": {
          "type": "path_hierarchy"
        }
      }
    }
  },
  "mappings": {
    "properties" : {
      "real" : {
        "type" : "keyword",
        "store" : true
      },
      "root" : {
        "type" : "keyword",
        "store" : true
      },
      "virtual" : {
        "type" : "keyword",
        "store" : true
      }
    }
  }
}
]
16:54:35,909 DEBUG [f.p.e.c.f.c.v.ElasticsearchClientV7] wait for yellow health on index [ssh-demo-job_folder]
16:54:35,914 TRACE [f.p.e.c.f.c.v.ElasticsearchClientV7] health response: {"cluster_name":"app-search-docker-cluster","status":"yellow","timed_out":false,"number_of_nodes":1,"number_of_data_nodes":1,"active_primary_shards":1,"active_shards":1,"relocating_shards":0,"initializing_shards":0,"unassigned_shards":1,"delayed_unassigned_shards":0,"number_of_pending_tasks":0,"number_of_in_flight_fetch":0,"task_max_waiting_in_queue_millis":0,"active_shards_percent_as_number":78.0}
16:54:35,917 DEBUG [f.p.e.c.f.FsParserAbstract] creating fs crawler thread [ssh-demo-job] for [192.168.72.21/AxS/WeblibAccess] every [15m]
16:54:35,918 INFO  [f.p.e.c.f.FsParserAbstract] FS crawler started for [ssh-demo-job] for [192.168.72.21/AxS/WeblibAccess] every [15m]
16:54:35,919 DEBUG [f.p.e.c.f.FsParserAbstract] Fs crawler thread [ssh-demo-job] is now running. Run #1...
16:54:35,920 DEBUG [f.p.e.c.f.c.s.FileAbstractorSSH] Opening SSH connection to hvhuan@192.168.72.21
16:54:56,935 WARN  [f.p.e.c.f.FsParserAbstract] Error while crawling 192.168.72.21/AxS/WeblibAccess: java.net.ConnectException: Connection timed out: connect
16:54:56,936 WARN  [f.p.e.c.f.FsParserAbstract] Full stacktrace
com.jcraft.jsch.JSchException: java.net.ConnectException: Connection timed out: connect
        at com.jcraft.jsch.Util.createSocket(Util.java:349) ~[jsch-0.1.55.jar:?]
        at com.jcraft.jsch.Session.connect(Session.java:215) ~[jsch-0.1.55.jar:?]
        at com.jcraft.jsch.Session.connect(Session.java:183) ~[jsch-0.1.55.jar:?]
        at fr.pilato.elasticsearch.crawler.fs.crawler.ssh.FileAbstractorSSH.openSSHConnection(FileAbstractorSSH.java:133) ~[fscrawler-crawler-ssh-2.7-SNAPSHOT.jar:?]
        at fr.pilato.elasticsearch.crawler.fs.crawler.ssh.FileAbstractorSSH.open(FileAbstractorSSH.java:110) ~[fscrawler-crawler-ssh-2.7-SNAPSHOT.jar:?]
        at fr.pilato.elasticsearch.crawler.fs.FsParserAbstract.run(FsParserAbstract.java:127) [fscrawler-core-2.7-SNAPSHOT.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
Caused by: java.net.ConnectException: Connection timed out: connect
        at java.net.DualStackPlainSocketImpl.connect0(Native Method) ~[?:1.8.0_202]
        at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79) ~[?:1.8.0_202]
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_202]
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_202]
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_202]
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172) ~[?:1.8.0_202]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_202]
        at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_202]
        at java.net.Socket.connect(Socket.java:538) ~[?:1.8.0_202]
        at java.net.Socket.<init>(Socket.java:434) ~[?:1.8.0_202]
        at java.net.Socket.<init>(Socket.java:211) ~[?:1.8.0_202]
        at com.jcraft.jsch.Util.createSocket(Util.java:343) ~[jsch-0.1.55.jar:?]
        ... 6 more
16:54:57,070 WARN  [f.p.e.c.f.FsParserAbstract] Error while closing the connection: java.lang.NullPointerException
16:54:57,071 INFO  [f.p.e.c.f.FsParserAbstract] FS crawler is stopping after 1 run
16:54:57,100 DEBUG [f.p.e.c.f.FsCrawlerImpl] Closing FS crawler [ssh-demo-job]
16:54:57,100 DEBUG [f.p.e.c.f.FsCrawlerImpl] FS crawler thread is now stopped
16:54:57,102 DEBUG [f.p.e.c.f.c.v.ElasticsearchClientV7] Closing Elasticsearch client manager
16:54:57,108 DEBUG [f.p.e.c.f.FsCrawlerImpl] ES Client Manager stopped
16:54:57,109 INFO  [f.p.e.c.f.FsCrawlerImpl] FS crawler [ssh-demo-job] stopped
16:54:57,113 DEBUG [f.p.e.c.f.FsCrawlerImpl] Closing FS crawler [ssh-demo-job]
16:54:57,114 DEBUG [f.p.e.c.f.FsCrawlerImpl] FS crawler thread is now stopped
16:54:57,116 DEBUG [f.p.e.c.f.c.v.ElasticsearchClientV7] Closing Elasticsearch client manager
16:54:57,117 DEBUG [f.p.e.c.f.FsCrawlerImpl] ES Client Manager stopped
```

I have a feeling that it's something wrong with the url, I'm not sure if "192.168.72.21/AxS/WeblibAccess" is correct. In the file explorer I can access to it by typing "\\192.168.72.21\AxS\WeblibAccess", so I did try the url "\\\192.168.72.21\\AxS\\WeblibAccess" but after that the executor cannot recognise "ssh-demo-job" (due to the "\\\" part)

**Comment by dadoonet** [comment]
But do you have a SSH service running on `192.168.72.21`? I mean that `\\192.168.72.21\\AxS\\WeblibAccess` seems like a mounted dir to me. Not behind a SSH service.

**Comment by huan415201** [comment]
Yes I do have service on 192.168.72.21

**Comment by dadoonet** [comment]
Can you run from the machine where FSCrawler is running:

```
ssh 192.168.72.21
```

With your `hvhuan` username and password and then run:

```
ls -l /AxS/WeblibAccess
```

?

**Comment by huan415201** [comment]
```
C:\Users\hvhuan>ssh -p 22 hvhuan@192.168.72.21
ssh: connect to host 192.168.72.21 port 22: Connection timed out
```
So this means the input for crawler is correct, problem is the ssh connection right?

**Comment by dadoonet** [comment]
Yes. You need first to make work your SSH service if you want to use SSH.
But as you can access the mounted drive, I' not sure you actually need SSH for this.

Can't you use the normal "path" option to be `\\192.168.72.21\\AxS\\WeblibAccess`?

**Comment by huan415201** [comment]
If I use this:
```yaml
---
name: "ssh-demo-job"
fs:
  url: "\\192.168.72.21\\AxS\\WeblibAccess"
```
The output said path doesn't exist:
```
C:\fscrawler-es7-2.7-SNAPSHOT\bin>fscrawler ssh-demo-job --loop 1
18:12:17,593 INFO  [f.p.e.c.f.c.BootstrapChecks] Memory [Free/Total=Percent]: HEAP [87.2mb/1.7gb=4.88%], RAM [2.1gb/7.8gb=27.25%], Swap [3.1gb/14.1gb=22.44%].
18:12:18,290 INFO  [f.p.e.c.f.c.v.ElasticsearchClientV7] Elasticsearch Client for version 7.x connected to a node running version 7.5.0
18:12:18,337 INFO  [f.p.e.c.f.FsCrawlerImpl] Starting FS crawler
18:12:18,503 INFO  [f.p.e.c.f.FsParserAbstract] FS crawler started for [ssh-demo-job] for [\192.168.72.21\AxS\WeblibAccess] every [15m]
18:12:18,505 WARN  [f.p.e.c.f.FsParserAbstract] Error while crawling \192.168.72.21\AxS\WeblibAccess: \192.168.72.21\AxS\WeblibAccess doesn't exists.
18:12:18,506 INFO  [f.p.e.c.f.FsParserAbstract] FS crawler is stopping after 1 run
18:12:18,607 INFO  [f.p.e.c.f.FsCrawlerImpl] FS crawler [ssh-demo-job] stopped
18:12:18,610 INFO  [f.p.e.c.f.FsCrawlerImpl] FS crawler [ssh-demo-job] stopped
```
I think it should be:
```
"\\192.168.72.21\AxS\WeblibAccess"
```
instead of "\192.168.72.21\AxS\WeblibAccess" like the error said.

**Comment by dadoonet** [comment]
It should be:

```
\\\\192.168.72.21\\AxS\\WeblibAccess
```

Or:

```
//192.168.72.21/AxS/WeblibAccess
```

Could you try?

**Comment by huan415201** [comment]
I tried the first one, it seems work, now I got a new error:
```
C:\fscrawler-es7-2.7-SNAPSHOT\bin>fscrawler ssh-demo-job --loop 1
09:46:32,986 INFO  [f.p.e.c.f.c.BootstrapChecks] Memory [Free/Total=Percent]: HEAP [87.3mb/1.7gb=4.89%], RAM [2.1gb/7.8gb=27.83%], Swap [3.1gb/14.1gb=22.62%].
09:46:33,672 INFO  [f.p.e.c.f.c.v.ElasticsearchClientV7] Elasticsearch Client for version 7.x connected to a node running version 7.5.0
09:46:33,718 INFO  [f.p.e.c.f.FsCrawlerImpl] Starting FS crawler
09:46:33,858 INFO  [f.p.e.c.f.FsParserAbstract] FS crawler started for [ssh-demo-job] for [\\192.168.72.21\AxS\WeblibAccess] every [15m]
09:46:34,247 WARN  [o.a.t.p.PDFParser] J2KImageReader not loaded. JPEG2000 files will not be processed.
See https://pdfbox.apache.org/2.0/dependencies.html#jai-image-io
for optional dependencies.

09:46:38,138 WARN  [o.a.p.p.f.PDType1Font] Using fallback font Arial-BoldMT for Frutiger-BlackCn
09:46:38,954 WARN  [f.p.e.c.f.FsParserAbstract] Can't find stored field name to check existing filenames in path [\\192.168.72.21\AxS\WeblibAccess\9.2.0_docs]. Please set store: true on field [file.filename]
09:46:38,954 WARN  [f.p.e.c.f.FsParserAbstract] Error while crawling \\192.168.72.21\AxS\WeblibAccess: Mapping is incorrect: please set stored: true on field [file.filename].
09:46:38,955 INFO  [f.p.e.c.f.FsParserAbstract] FS crawler is stopping after 1 run
09:46:39,001 INFO  [f.p.e.c.f.FsCrawlerImpl] FS crawler [ssh-demo-job] stopped
09:46:39,046 INFO  [f.p.e.c.f.FsCrawlerImpl] FS crawler [ssh-demo-job] stopped
```
This is the _settings/json file in .fscrawler/_default/7/:
```json
{
  "settings": {
    "number_of_shards": 1,
    "index.mapping.total_fields.limit": 2000,
    "analysis": {
      "analyzer": {
        "fscrawler_path": {
          "tokenizer": "fscrawler_path"
        }
      },
      "tokenizer": {
        "fscrawler_path": {
          "type": "path_hierarchy"
        }
      }
    }
  },
  "mappings": {
    "dynamic_templates": [
      {
        "raw_as_text": {
          "path_match": "meta.raw.*",
          "mapping": {
            "type": "text",
            "fields": {
              "keyword": {
                "type": "keyword",
                "ignore_above": 256
              }
            }
          }
        }
      }
    ],
    "properties": {
	  "suggest-filename": {
		"type": "completion"
	  },
      "attachment": {
        "type": "binary",
        "doc_values": false
      },
      "attributes": {
        "properties": {
          "group": {
            "type": "keyword"
          },
          "owner": {
            "type": "keyword"
          }
        }
      },
      "content": {
        "type": "text"
      },
      "file": {
        "properties": {
          "content_type": {
            "type": "keyword"
          },
          "filename": {
            "type": "keyword",
			"store": true,
			"copy_to": "suggest-filename"
          },
          "extension": {
            "type": "keyword"
          },
          "filesize": {
            "type": "long"
          },
          "indexed_chars": {
            "type": "long"
          },
          "indexing_date": {
            "type": "date",
            "format": "dateOptionalTime"
          },
          "created": {
            "type": "date",
            "format": "dateOptionalTime"
          },
          "last_modified": {
            "type": "date",
            "format": "dateOptionalTime"
          },
          "last_accessed": {
            "type": "date",
            "format": "dateOptionalTime"
          },
          "checksum": {
            "type": "keyword"
          },
          "url": {
            "type": "keyword",
            "index": false
          }
        }
      },
      "meta": {
        "properties": {
          "author": {
            "type": "text"
          },
          "date": {
            "type": "date",
            "format": "dateOptionalTime"
          },
          "keywords": {
            "type": "text"
          },
          "title": {
            "type": "text"
          },
          "language": {
            "type": "keyword"
          },
          "format": {
            "type": "text"
          },
          "identifier": {
            "type": "text"
          },
          "contributor": {
            "type": "text"
          },
          "coverage": {
            "type": "text"
          },
          "modifier": {
            "type": "text"
          },
          "creator_tool": {
            "type": "keyword"
          },
          "publisher": {
            "type": "text"
          },
          "relation": {
            "type": "text"
          },
          "rights": {
            "type": "text"
          },
          "source": {
            "type": "text"
          },
          "type": {
            "type": "text"
          },
          "description": {
            "type": "text"
          },
          "created": {
            "type": "date",
            "format": "dateOptionalTime"
          },
          "print_date": {
            "type": "date",
            "format": "dateOptionalTime"
          },
          "metadata_date": {
            "type": "date",
            "format": "dateOptionalTime"
          },
          "latitude": {
            "type": "text"
          },
          "longitude": {
            "type": "text"
          },
          "altitude": {
            "type": "text"
          },
          "rating": {
            "type": "byte"
          },
          "comments": {
            "type": "text"
          }
        }
      },
      "path": {
        "properties": {
          "real": {
            "type": "keyword",
            "fields": {
              "tree": {
                "type": "text",
                "analyzer": "fscrawler_path",
                "fielddata": true
              },
              "fulltext": {
                "type": "text"
              }
            }
          },
          "root": {
            "type": "keyword"
          },
          "virtual": {
            "type": "keyword",
            "fields": {
              "tree": {
                "type": "text",
                "analyzer": "fscrawler_path",
                "fielddata": true
              },
              "fulltext": {
                "type": "text"
              }
            }
          }
        }
      }
    }
  }
}
```
As you can see in the ```file.filename``` there is ```store``` attribute with value is ```true``` but the executor somehow doesn't recognise it.

**Comment by huan415201** [comment]
For somehow when I turn everything off and start over again, it worked as usual. Thank you!

**Comment by dadoonet** [comment]
Awesome. Let's close this issue then. 😉
