### ISSUE TITLE
By monitoring the pdf file cannot be uploaded to elasticsearch

### ISSUE THREAD

**Issue by 1176967052** [dadoonet/fscrawler#904]
**Describe the bug**
Error caught for [job_bb_folder]/[_doc]/[edf47d3d7980bdbba21df1b7142be1eb]: ElasticsearchException[Elasticsearch exception [type=illegal_argument_exception, reason=Rejecting mapping update to [job_bb_folder] as the final mapping would have more than 1 type: [_doc, doc]]]
02:32:28,988 WARN  [f.p.e.c.f.c.v.ElasticsearchClientV6] Got [1] failures of [1] requests

then 

02:36:25,406 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] computeVirtualPathName(/Users/fscrawler/fscrawler-es6-2.6/data, /Users/fscrawler/fscrawler-es6-2.6/data/xxx.pdf) = /xxx.pdf
02:36:25,406 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] directory = [false], filename = [/xxx.pdf], includes = [null], excludes = [[*/~*]]
02:36:25,406 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] filename = [/xxx.pdf], excludes = [[*/~*]]
02:36:25,406 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] filename = [/xxx.pdf], includes = [null]
02:36:25,406 DEBUG [f.p.e.c.f.FsParserAbstract] [/xxx.pdf] can be indexed: [true]
02:36:25,406 DEBUG [f.p.e.c.f.FsParserAbstract]   - file: /xxx.pdf
02:36:25,406 DEBUG [f.p.e.c.f.FsParserAbstract]     - not modified: creation date 2020-02-17T22:03:03 , file date 2020-02-17T22:03:03, last scan date 2020-02-18T02:34:22.669
02:36:25,406 DEBUG [f.p.e.c.f.FsParserAbstract] Looking for removed files in [/Users/fscrawler/fscrawler-es6-2.6/data]...
02:36:25,483 WARN  [f.p.e.c.f.FsParserAbstract] Can't find stored field name to check existing filenames in path [/Users/fscrawler/fscrawler-es6-2.6/data]. Please set store: true on field [file.filename]
02:36:25,483 WARN  [f.p.e.c.f.FsParserAbstract] Error while crawling /Users/fscrawler/fscrawler-es6-2.6/data: Mapping is incorrect: please set stored: true on field [file.filename].
02:36:25,484 WARN  [f.p.e.c.f.FsParserAbstract] Full stacktrace
java.lang.RuntimeException: Mapping is incorrect: please set stored: true on field [file.filename].
	at fr.pilato.elasticsearch.crawler.fs.FsParserAbstract.getFileDirectory(FsParserAbstract.java:382) ~[fscrawler-core-2.6.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.FsParserAbstract.addFilesRecursively(FsParserAbstract.java:317) ~[fscrawler-core-2.6.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.FsParserAbstract.run(FsParserAbstract.java:157) [fscrawler-core-2.6.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
02:36:25,487 DEBUG [f.p.e.c.f.FsParserAbstract] Fs crawler is going to sleep for 2m
02:38:25,492 DEBUG [f.p.e.c.f.FsParserAbstract] Fs crawler is now waking up again...

**To Reproduce**

1. ./bin/fscrawler job_bb
2.  vim /Users/.fscrawler/job_bb/_settings.json
3.  {
  "name" : "job_bb",
  "fs" : {
    "url" : "/Users/fscrawler/fscrawler-es6-2.6/data",
    "update_rate" : "2m",
    "excludes" : [ "*/~*" ],
    "json_support" : false,
    "filename_as_id" : false,
    "add_filesize" : true,
    "remove_deleted" : true,
    "add_as_inner_object" : false,
    "store_source" : false,
    "index_content" : true,
    "attributes_support" : false,
    "raw_metadata" : true,
    "xml_support" : false,
    "index_folders" : true,
    "lang_detect" : false,
    "continue_on_error" : false,
    "pdf_ocr" : true,
    "ocr" : {
      "language" : "eng"
    }
  },
"elasticsearch" : {
    "nodes" : [ {
      "url" : "http://175.24.178.145:9200"
    } ],
    "bulk_size" : 100,
    "flush_interval" : "5s",
    "byte_size" : "10mb"
  },
  "rest" : {
    "url" : "http://127.0.0.1:8080/fscrawler"
  }
}
4. ./bin/fscrawler job_bb --loop -1 --debug
5. see error 
**Expected behavior**

**Versions:**
 - OS: [ MacOS]
 - Version [ 2.6]
 - elasticsearch[6.5.0]

Hello, what should I do?

**Comment by dadoonet** [comment]
Could you try with the latest 6.8 elasticsearch version?
Could you first delete the existing index and restart FSCrawler with the `--restart` option?

**Comment by dadoonet** [comment]
And i forgot. Please use the latest FSCrawler snapshot.
