### ISSUE TITLE
Indexing subdirectory of remote url throws error

### ISSUE THREAD

**Issue by LaaKii** [dadoonet/fscrawler#923]
I index files on a remote Windows machine.
It's not possible to index subdirectorys, because the following error is thrown:

` 11:00:40,889 WARN  [f.p.e.c.f.FsParserAbstract] Error while crawling /D:/TestData: String index out of range: -1
11:00:40,889 WARN  [f.p.e.c.f.FsParserAbstract] Full stacktrace
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.String.substring(Unknown Source) ~[?:1.8.0_202]
        at fr.pilato.elasticsearch.crawler.fs.FsParserAbstract.indexDirectory(FsParserAbstract.java:541) ~[fscrawler-core-2.7-SNAPSHOT.jar:?]
        at fr.pilato.elasticsearch.crawler.fs.FsParserAbstract.addFilesRecursively(FsParserAbstract.java:289) ~[fscrawler-core-2.7-SNAPSHOT.jar:?]
        at fr.pilato.elasticsearch.crawler.fs.FsParserAbstract.run(FsParserAbstract.java:149) [fscrawler-core-2.7-SNAPSHOT.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_202]
11:00:40,905 DEBUG [f.p.e.c.f.FsParserAbstract] Fs crawler is going to sleep for 15m`

It works fine if there are no subdirectories.

**To Reproduce**

1. Use a remote windows machine
2. Set Url in config to a folder which contains subdirectories
3. Run fscrawler

**Expected behavior**

´The expected behavior would be the same as it is when running fscrawler locally. The directory configured in the `settings.yml` and all subdirectories should be indexed.

**Versions:**
 - OS: [Windows 10] & [Windows Server 2016]
 - Version [e.g. 2.7]

**Comment by dadoonet** [comment]
Hey 


Sorry for the late reply. What does your settings file look like? I guess the path is set to `/D:/TestData`, right?

**Comment by LaaKii** [comment]
Hey,

also sorry for my late feedback. Currently there's no option for me to test it, till July. I'll answer your questions then.

Sorry in advance.
