### ISSUE TITLE
java.lang.IllegalArgumentException: HTTP Host may not be null

### ISSUE THREAD

**Issue by henryse** [dadoonet/fscrawler#950]
**Describe the bug**

Unable to get 

**Job Settings**

├── _default
│   ├── 6
│   │   ├── _settings.json
│   │   └── _settings_folder.json
│   └── 7
│       ├── _settings.json
│       └── _settings_folder.json
├── _settings.json
├── case-documents
│   └── _settings.json
├── empty
├── fscrawler_rest
│   └── _settings.json
└── myjob
    └── _settings.json

```case-documents/_settings.json
{
  "name": "case-documents",
  "fs": {
    "url": "/usr/share/fscrawler/data",
    "filename_as_id": true
  },
  "elasticsearch": {
    "nodes": [
      {
        "host": "dragonfly.jacksonville.applegate.farm",
        "port": 9200,
        "scheme": "HTTP"
      }
    ],
    "index": "case-documents",
    "pipeline": "case_pipeline",
    "type": "doc"
  }
}

```

```
Starting production_fscrawler_1 ... done
Attaching to production_fscrawler_1
fscrawler_1  | 19:47:06,257 INFO  [f.p.e.c.f.c.BootstrapChecks] Memory [Free/Total=Percent]: HEAP [18.7mb/443mb=4.24%], RAM [114.4mb/1.9gb=5.74%], Swap [1008.3mb/1023.9mb=98.48%].
fscrawler_1  | 19:47:06,280 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [6/_settings.json] already exists
fscrawler_1  | 19:47:06,281 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [6/_settings_folder.json] already exists
fscrawler_1  | 19:47:06,284 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [7/_settings.json] already exists
fscrawler_1  | 19:47:06,286 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [7/_settings_folder.json] already exists
fscrawler_1  | 19:47:06,292 DEBUG [f.p.e.c.f.c.FsCrawlerCli] Starting job [case-documents]...
fscrawler_1  | 19:47:07,158 DEBUG [f.p.e.c.f.c.ElasticsearchClientUtil] Trying to find a client version 7
fscrawler_1  | 19:47:07,238 WARN  [f.p.e.c.f.c.v.ElasticsearchClientV7] failed to create elasticsearch client, disabling crawler...
fscrawler_1  | 19:47:07,238 FATAL [f.p.e.c.f.c.FsCrawlerCli] We can not start Elasticsearch Client. Exiting.
fscrawler_1  | java.lang.IllegalArgumentException: HTTP Host may not be null
fscrawler_1  | 	at org.apache.http.util.Args.containsNoBlanks(Args.java:81) ~[httpcore-4.4.13.jar:4.4.13]
fscrawler_1  | 	at org.apache.http.HttpHost.create(HttpHost.java:108) ~[httpcore-4.4.13.jar:4.4.13]
fscrawler_1  | 	at fr.pilato.elasticsearch.crawler.fs.client.v7.ElasticsearchClientV7.lambda$buildRestClient$1(ElasticsearchClientV7.java:385) ~[fscrawler-elasticsearch-client-v7-2.7-SNAPSHOT.jar:?]
fscrawler_1  | 	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_252]
fscrawler_1  | 	at fr.pilato.elasticsearch.crawler.fs.client.v7.ElasticsearchClientV7.buildRestClient(ElasticsearchClientV7.java:385) ~[fscrawler-elasticsearch-client-v7-2.7-SNAPSHOT.jar:?]
fscrawler_1  | 	at fr.pilato.elasticsearch.crawler.fs.client.v7.ElasticsearchClientV7.start(ElasticsearchClientV7.java:141) ~[fscrawler-elasticsearch-client-v7-2.7-SNAPSHOT.jar:?]
fscrawler_1  | 	at fr.pilato.elasticsearch.crawler.fs.cli.FsCrawlerCli.main(FsCrawlerCli.java:257) [fscrawler-cli-2.7-SNAPSHOT.jar:?]
fscrawler_1  | 19:47:07,250 DEBUG [f.p.e.c.f.FsCrawlerImpl] Closing FS crawler [case-documents]
fscrawler_1  | 19:47:07,250 DEBUG [f.p.e.c.f.c.v.ElasticsearchClientV7] Closing Elasticsearch client manager
fscrawler_1  | 19:47:07,251 DEBUG [f.p.e.c.f.FsCrawlerImpl] ES Client Manager stopped
fscrawler_1  | 19:47:07,251 INFO  [f.p.e.c.f.FsCrawlerImpl] FS crawler [case-documents] stopped
fscrawler_1  | 19:47:07,266 DEBUG [f.p.e.c.f.FsCrawlerImpl] Closing FS crawler [case-documents]
fscrawler_1  | 19:47:07,268 DEBUG [f.p.e.c.f.c.v.ElasticsearchClientV7] Closing Elasticsearch client manager
fscrawler_1  | 19:47:07,268 DEBUG [f.p.e.c.f.FsCrawlerImpl] ES Client Manager stopped
fscrawler_1  | 19:47:07,270 INFO  [f.p.e.c.f.FsCrawlerImpl] FS crawler [case-documents] stopped
```

**Expected behavior**

Program runs.

**Versions:**
FROM openjdk:8

RUN apt-get update \
    && apt-get install -y wget \
    && apt-get install -y unzip \
    && apt-get install -y maven \
    && apt-get install -y tesseract-ocr \
    && apt-get install -y tesseract-ocr-fra \
    && apt-get install -y gosu bash openssl

RUN update-ca-certificates -f
WORKDIR /runtime

ENV FSCRAWLER_FILE fscrawler-es7-2.7-20200422.091346-98.zip
ENV FSCRAWLER_BASE fscrawler-es7-2.7-SNAPSHOT

RUN mkdir /usr/share/fscrawler
WORKDIR /usr/share/fscrawler
RUN wget https://oss.sonatype.org/content/repositories/snapshots/fr/pilato/elasticsearch/crawler/fscrawler-es7/2.7-SNAPSHOT/${FSCRAWLER_FILE}
RUN unzip ${FSCRAWLER_FILE} -d temp \
    && mv temp/${FSCRAWLER_BASE} fscrawler \
    && rm ${FSCRAWLER_FILE} \
    && rm -r temp

ENV PATH /usr/share/fscrawler/fscrawler/bin:$PATH

# ensure fscrawler user exists
RUN addgroup --system fscrawler && adduser --system --ingroup fscrawler fscrawler

VOLUME /usr/share/fscrawler/data
RUN mkdir /usr/share/fscrawler/config-mount \
    && touch /usr/share/fscrawler/config-mount/empty

COPY entry.sh /
RUN chmod +x /entry.sh

ENTRYPOINT ["/entry.sh"]
CMD ["fscrawler", "--trace", "--config_dir", "/usr/share/fscrawler/config", "config-documents"]

**Attachment**

If the bug is related to a given file, please share this file so we can reuse it in tests
to reproduce the problem and may be use it in our integration tests.

**Comment by dadoonet** [comment]
The way you need to specify nodes changed. See https://fscrawler.readthedocs.io/en/latest/admin/fs/elasticsearch.html#node-settings

Use something like instead (note that it's better to use yaml now):

```yml
name: "case-documents"
elasticsearch:
  nodes:
  - url: "http://dragonfly.jacksonville.applegate.farm:9200"
```

**Comment by dadoonet** [comment]
But I agree that it should be forward compatible if possible.

**Comment by dadoonet** [comment]
I'm going to close the issue as I think that my first answer solved the problem. Feel free to reopen if this is not the case.
