### ISSUE TITLE
The mapping definition cannot be nested under a type [_doc] unless include_type_name is set to true.

### ISSUE THREAD

**Issue by Petros99** [dadoonet/fscrawler#957]
**Describe the bug**

FSCrawler es6-2.7 snapshot unable to add documents to Elasticsearch 6.7.2 host
Elasticsearch throws: `The mapping definition cannot be nested under a type [_doc] unless include_type_name is set to true.`
**Job Settings**

```json
{
   "name":"test",
   "fs":{
      "url":"/home/petros/dev/bioinform/fscrawler/test-documents/src/main/resources/documents",
      "store_source":false,
      "index_content":true,
      "attributes_support":true,
      "continue_on_error":true,
      "indexed_chars":"50",
      "pdf_ocr":false
   },
   "elasticsearch":{
      "nodes":[
         {
            "url":"http://192.168.56.101:9200"
         }
      ],
      "index":"readsclient_bilck28bkfn0hhsvszlq_rex_local_test",
      "index_folder":"readsclient_bilck28bkfn0hhsvszlq_rex_local_test_folder"
   },
   "server":{
      "hostname":null,
      "port":null,
      "username":null,
      "password":null,
      "protocol":"local"
   }
}
```

**Logs**

```
19:28:47,737 [32mINFO [m [f.p.e.c.f.c.BootstrapChecks] Memory [Free/Total=Percent]: HEAP [174.5mb/2gb=8.52%], RAM [3.6gb/15.4gb=23.89%], Swap [29.7gb/29.8gb=99.74%].
19:28:47,739 [36mDEBUG[m [f.p.e.c.f.f.FsCrawlerUtil] Mapping [6/_settings.json] already exists
19:28:47,739 [36mDEBUG[m [f.p.e.c.f.f.FsCrawlerUtil] Mapping [6/_settings_folder.json] already exists
19:28:47,739 [36mDEBUG[m [f.p.e.c.f.f.FsCrawlerUtil] Mapping [7/_settings.json] already exists
19:28:47,739 [36mDEBUG[m [f.p.e.c.f.f.FsCrawlerUtil] Mapping [7/_settings_folder.json] already exists
19:28:47,740 [36mDEBUG[m [f.p.e.c.f.c.FsCrawlerCli] Starting job [test]...
19:28:47,882 [33mWARN [m [f.p.e.c.f.s.Fs] pdf_ocr setting has been deprecated and is replaced by ocr.pdf_strategy: no_ocr.
19:28:47,909 [30mTRACE[m [f.p.e.c.f.c.FsCrawlerCli] settings used for this crawler: [---
name: "test"
fs:
url: "/home/petros/dev/bioinform/fscrawler/test-documents/src/main/resources/documents"
update_rate: "15m"
json_support: false
filename_as_id: false
add_filesize: true
remove_deleted: true
add_as_inner_object: false
store_source: false
index_content: true
indexed_chars: "50.0"
attributes_support: true
raw_metadata: false
xml_support: false
index_folders: true
lang_detect: false
continue_on_error: true
ocr:
language: "eng"
enabled: true
pdf_strategy: "no_ocr"
follow_symlinks: false
server:
port: 0
protocol: "local"
elasticsearch:
nodes:
- url: "http://192.168.56.101:9200"
index: "readsclient_bilck28bkfn0hhsvszlq_rex_local_test"
index_folder: "readsclient_bilck28bkfn0hhsvszlq_rex_local_test_folder"
bulk_size: 100
flush_interval: "5s"
byte_size: "10mb"
]
19:28:47,912 [36mDEBUG[m [f.p.e.c.f.c.ElasticsearchClientUtil] Trying to find a client version 7
19:28:47,912 [30mTRACE[m [f.p.e.c.f.c.ElasticsearchClientUtil] Trying to find a class named [fr.pilato.elasticsearch.crawler.fs.client.v7.ElasticsearchClientV7]
19:28:47,912 [30mTRACE[m [f.p.e.c.f.c.ElasticsearchClientUtil] ElasticsearchClient class not found for version 7 in the classpath. Skipping...
19:28:47,912 [36mDEBUG[m [f.p.e.c.f.c.ElasticsearchClientUtil] Trying to find a client version 6
19:28:47,913 [30mTRACE[m [f.p.e.c.f.c.ElasticsearchClientUtil] Trying to find a class named [fr.pilato.elasticsearch.crawler.fs.client.v6.ElasticsearchClientV6]
19:28:47,917 [30mTRACE[m [f.p.e.c.f.c.ElasticsearchClientUtil] Found [fr.pilato.elasticsearch.crawler.fs.client.v6.ElasticsearchClientV6] class as the elasticsearch client implementation.
19:28:48,386 [32mINFO [m [f.p.e.c.f.c.v.ElasticsearchClientV6] Elasticsearch Client for version 6.x connected to a node running version 6.7.2
19:28:48,425 [32mINFO [m [f.p.e.c.f.FsCrawlerImpl] Starting FS crawler
19:28:48,425 [32mINFO [m [f.p.e.c.f.FsCrawlerImpl] FS crawler started in watch mode. It will run unless you stop it with CTRL+C.
19:28:48,430 [36mDEBUG[m [f.p.e.c.f.c.v.ElasticsearchClientV6] FS crawler connected to an elasticsearch [6.7.2] node.
19:28:48,431 [36mDEBUG[m [f.p.e.c.f.c.v.ElasticsearchClientV6] create index [readsclient_bilck28bkfn0hhsvszlq_rex_local_test]
19:28:48,431 [30mTRACE[m [f.p.e.c.f.c.v.ElasticsearchClientV6] index settings: [{
"settings": {
"number_of_shards": 1,
"index.mapping.total_fields.limit": 2000,
"analysis": {
"analyzer": {
"fscrawler_path": {
"tokenizer": "fscrawler_path"
}
},
"tokenizer": {
"fscrawler_path": {
"type": "path_hierarchy"
}
}
}
},
"mappings": {
"_doc": {
"dynamic_templates": [
{
"raw_as_text": {
"path_match": "meta.raw.*",
"mapping": {
"type": "text",
"fields": {
"keyword": {
"type": "keyword",
"ignore_above": 256
}
}
}
}
}
],
"properties": {
"attachment": {
"type": "binary",
"doc_values": false
},
"attributes": {
"properties": {
"group": {
"type": "keyword"
},
"owner": {
"type": "keyword"
}
}
},
"content": {
"type": "text"
},
"file": {
"properties": {
"content_type": {
"type": "keyword"
},
"filename": {
"type": "keyword",
"store": true
},
"extension": {
"type": "keyword"
},
"filesize": {
"type": "long"
},
"indexed_chars": {
"type": "long"
},
"indexing_date": {
"type": "date",
"format": "dateOptionalTime"
},
"created": {
"type": "date",
"format": "dateOptionalTime"
},
"last_modified": {
"type": "date",
"format": "dateOptionalTime"
},
"last_accessed": {
"type": "date",
"format": "dateOptionalTime"
},
"checksum": {
"type": "keyword"
},
"url": {
"type": "keyword",
"index": false
}
}
},
"meta": {
"properties": {
"author": {
"type": "text"
},
"date": {
"type": "date",
"format": "dateOptionalTime"
},
"keywords": {
"type": "text"
},
"title": {
"type": "text"
},
"language": {
"type": "keyword"
},
"format": {
"type": "text"
},
"identifier": {
"type": "text"
},
"contributor": {
"type": "text"
},
"coverage": {
"type": "text"
},
"modifier": {
"type": "text"
},
"creator_tool": {
"type": "keyword"
},
"publisher": {
"type": "text"
},
"relation": {
"type": "text"
},
"rights": {
"type": "text"
},
"source": {
"type": "text"
},
"type": {
"type": "text"
},
"description": {
"type": "text"
},
"created": {
"type": "date",
"format": "dateOptionalTime"
},
"print_date": {
"type": "date",
"format": "dateOptionalTime"
},
"metadata_date": {
"type": "date",
"format": "dateOptionalTime"
},
"latitude": {
"type": "text"
},
"longitude": {
"type": "text"
},
"altitude": {
"type": "text"
},
"rating": {
"type": "byte"
},
"comments": {
"type": "text"
}
}
},
"path": {
"properties": {
"real": {
"type": "keyword",
"fields": {
"tree": {
"type": "text",
"analyzer": "fscrawler_path",
"fielddata": true
},
"fulltext": {
"type": "text"
}
}
},
"root": {
"type": "keyword"
},
"virtual": {
"type": "keyword",
"fields": {
"tree": {
"type": "text",
"analyzer": "fscrawler_path",
"fielddata": true
},
"fulltext": {
"type": "text"
}
}
}
}
}
}
}
}
}
]
19:28:48,590 [33mWARN [m [f.p.e.c.f.c.v.ElasticsearchClientV6] failed to create index [readsclient_bilck28bkfn0hhsvszlq_rex_local_test], disabling crawler...
19:28:48,590 [1;31mFATAL[m [f.p.e.c.f.c.FsCrawlerCli] Fatal error received while running the crawler: [Elasticsearch exception [type=illegal_argument_exception, reason=The mapping definition cannot be nested under a type [_doc] unless include_type_name is set to true.]]
19:28:48,590 [36mDEBUG[m [f.p.e.c.f.c.FsCrawlerCli] error caught
org.elasticsearch.ElasticsearchStatusException: Elasticsearch exception [type=illegal_argument_exception, reason=The mapping definition cannot be nested under a type [_doc] unless include_type_name is set to true.]
at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:177) ~[elasticsearch-6.8.9.jar:6.8.9]
at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:2053) ~[elasticsearch-rest-high-level-client-6.8.9.jar:6.8.9]
at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:2030) ~[elasticsearch-rest-high-level-client-6.8.9.jar:6.8.9]
at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1777) ~[elasticsearch-rest-high-level-client-6.8.9.jar:6.8.9]
at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1749) ~[elasticsearch-rest-high-level-client-6.8.9.jar:6.8.9]
at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1708) ~[elasticsearch-rest-high-level-client-6.8.9.jar:6.8.9]
at org.elasticsearch.client.IndicesClient.create(IndicesClient.java:152) ~[elasticsearch-rest-high-level-client-6.8.9.jar:6.8.9]
at fr.pilato.elasticsearch.crawler.fs.client.v6.ElasticsearchClientV6.createIndex(ElasticsearchClientV6.java:239) ~[fscrawler-elasticsearch-client-v6-2.7-SNAPSHOT.jar:?]
at fr.pilato.elasticsearch.crawler.fs.client.v6.ElasticsearchClientV6.createIndex(ElasticsearchClientV6.java:604) ~[fscrawler-elasticsearch-client-v6-2.7-SNAPSHOT.jar:?]
at fr.pilato.elasticsearch.crawler.fs.client.v6.ElasticsearchClientV6.createIndices(ElasticsearchClientV6.java:437) ~[fscrawler-elasticsearch-client-v6-2.7-SNAPSHOT.jar:?]
at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl.start(FsCrawlerImpl.java:99) ~[fscrawler-core-2.7-SNAPSHOT.jar:?]
at fr.pilato.elasticsearch.crawler.fs.cli.FsCrawlerCli.main(FsCrawlerCli.java:264) [fscrawler-cli-2.7-SNAPSHOT.jar:?]
Suppressed: org.elasticsearch.client.ResponseException: method [PUT], host [http://192.168.56.101:9200], URI [/readsclient_bilck28bkfn0hhsvszlq_rex_local_test?master_timeout=30s&include_type_name=false&timeout=30s], status line [HTTP/1.1 400 Bad Request]
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"The mapping definition cannot be nested under a type [_doc] unless include_type_name is set to true."}],"type":"illegal_argument_exception","reason":"The mapping definition cannot be nested under a type [_doc] unless include_type_name is set to true."},"status":400}
at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:936) ~[elasticsearch-rest-client-6.8.9.jar:6.8.9]
at org.elasticsearch.client.RestClient.performRequest(RestClient.java:233) ~[elasticsearch-rest-client-6.8.9.jar:6.8.9]
at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1764) ~[elasticsearch-rest-high-level-client-6.8.9.jar:6.8.9]
at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1749) ~[elasticsearch-rest-high-level-client-6.8.9.jar:6.8.9]
at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1708) ~[elasticsearch-rest-high-level-client-6.8.9.jar:6.8.9]
at org.elasticsearch.client.IndicesClient.create(IndicesClient.java:152) ~[elasticsearch-rest-high-level-client-6.8.9.jar:6.8.9]
at fr.pilato.elasticsearch.crawler.fs.client.v6.ElasticsearchClientV6.createIndex(ElasticsearchClientV6.java:239) ~[fscrawler-elasticsearch-client-v6-2.7-SNAPSHOT.jar:?]
at fr.pilato.elasticsearch.crawler.fs.client.v6.ElasticsearchClientV6.createIndex(ElasticsearchClientV6.java:604) ~[fscrawler-elasticsearch-client-v6-2.7-SNAPSHOT.jar:?]
at fr.pilato.elasticsearch.crawler.fs.client.v6.ElasticsearchClientV6.createIndices(ElasticsearchClientV6.java:437) ~[fscrawler-elasticsearch-client-v6-2.7-SNAPSHOT.jar:?]
at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl.start(FsCrawlerImpl.java:99) ~[fscrawler-core-2.7-SNAPSHOT.jar:?]
at fr.pilato.elasticsearch.crawler.fs.cli.FsCrawlerCli.main(FsCrawlerCli.java:264) [fscrawler-cli-2.7-SNAPSHOT.jar:?]
Caused by: org.elasticsearch.client.ResponseException: method [PUT], host [http://192.168.56.101:9200], URI [/readsclient_bilck28bkfn0hhsvszlq_rex_local_test?master_timeout=30s&include_type_name=false&timeout=30s], status line [HTTP/1.1 400 Bad Request]
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"The mapping definition cannot be nested under a type [_doc] unless include_type_name is set to true."}],"type":"illegal_argument_exception","reason":"The mapping definition cannot be nested under a type [_doc] unless include_type_name is set to true."},"status":400}
at org.elasticsearch.client.RestClient$1.completed(RestClient.java:552) ~[elasticsearch-rest-client-6.8.9.jar:6.8.9]
at org.elasticsearch.client.RestClient$1.completed(RestClient.java:537) ~[elasticsearch-rest-client-6.8.9.jar:6.8.9]
at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:122) ~[httpcore-4.4.13.jar:4.4.13]
at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:181) ~[httpasyncclient-4.1.4.jar:4.1.4]
at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:448) ~[httpcore-nio-4.4.13.jar:4.4.13]
at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:338) ~[httpcore-nio-4.4.13.jar:4.4.13]
at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265) ~[httpcore-nio-4.4.13.jar:4.4.13]
at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81) ~[httpasyncclient-4.1.4.jar:4.1.4]
at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39) ~[httpasyncclient-4.1.4.jar:4.1.4]
at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114) ~[httpcore-nio-4.4.13.jar:4.4.13]
at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162) ~[httpcore-nio-4.4.13.jar:4.4.13]
at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337) ~[httpcore-nio-4.4.13.jar:4.4.13]
at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315) ~[httpcore-nio-4.4.13.jar:4.4.13]
at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276) ~[httpcore-nio-4.4.13.jar:4.4.13]
at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104) ~[httpcore-nio-4.4.13.jar:4.4.13]
at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591) ~[httpcore-nio-4.4.13.jar:4.4.13]
at java.lang.Thread.run(Thread.java:834) ~[?:?]
19:28:48,596 [36mDEBUG[m [f.p.e.c.f.FsCrawlerImpl] Closing FS crawler [test]
19:28:48,596 [36mDEBUG[m [f.p.e.c.f.c.v.ElasticsearchClientV6] Closing Elasticsearch client manager
19:28:48,603 [36mDEBUG[m [f.p.e.c.f.FsCrawlerImpl] ES Client Manager stopped
19:28:48,604 [32mINFO [m [f.p.e.c.f.FsCrawlerImpl] FS crawler [test] stopped
19:28:48,605 [36mDEBUG[m [f.p.e.c.f.FsCrawlerImpl] Closing FS crawler [test]
19:28:48,611 [36mDEBUG[m [f.p.e.c.f.c.v.ElasticsearchClientV6] Closing Elasticsearch client manager
19:28:48,613 [36mDEBUG[m [f.p.e.c.f.FsCrawlerImpl] ES Client Manager stopped
19:28:48,613 [32mINFO [m [f.p.e.c.f.FsCrawlerImpl] FS crawler [test] stopped
fscrawler process for config: test terminated due to receipt of signal null
```

**Expected behavior**
documents are indexed

**Versions:**
 - OS: Linux 5.4.0-29-generic #33-Ubuntu 
 - Version fscrawler-es6-2.7-20200515.152132-116

**Attachment**

No attachments, issue appears using test documents.

**Comment by dadoonet** [comment]
Sadly the only workaround is by upgrading your elasticsearch to 6.8.

**Comment by dadoonet** [comment]
Or may be try to remove `_doc` in the mapping definition?

**Comment by Petros99** [comment]
changing `_doc` to `doc` in the default mappings results in the following error: ```20:15:52,384 [1;31mFATAL[m [f.p.e.c.f.c.FsCrawlerCli] Fatal error received while running the crawler: [Elasticsearch exception [type=mapper_parsing_exception, reason=Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters: [doc : {dynamic_templates=[{raw_as_text={path_match=meta.raw.*, mapping={type=text, fields={keyword={ignore_above=256, type=keyword}}}}}], properties={path={properties={virtual={type=keyword, fields={tree={fielddata=true, analyzer=fscrawler_path, type=text}, fulltext={type=text}}}, root={type=keyword}, real={type=keyword, fields={tree={fielddata=true, analyzer=fscrawler_path, type=text}, fulltext={type=text}}}}}, file={properties={extension={type=keyword}, filename={store=true, type=keyword}, indexed_chars={type=long}, last_accessed={format=dateOptionalTime, type=date}, content_type={type=keyword}, indexing_date={format=dateOptionalTime, type=date}, created={format=dateOptionalTime, type=date}, checksum={type=keyword}, filesize={type=long}, last_modified={format=dateOptionalTime, type=date}, url={index=false, type=keyword}}}, attachment={type=binary, doc_values=false}, meta={properties={date={format=dateOptionalTime, type=date}, altitude={type=text}, keywords={type=text}, modifier={type=text}, latitude={type=text}, rating={type=byte}, description={type=text}, language={type=keyword}, source={type=text}, title={type=text}, creator_tool={type=keyword}, type={type=text}, relation={type=text}, contributor={type=text}, rights={type=text}, metadata_date={format=dateOptionalTime, type=date}, longitude={type=text}, coverage={type=text}, identifier={type=text}, comments={type=text}, author={type=text}, created={format=dateOptionalTime, type=date}, format={type=text}, publisher={type=text}, print_date={format=dateOptionalTime, type=date}}}, attributes={properties={owner={type=keyword}, group={type=keyword}}}, content={type=text}}}]]]```

Is there another place where the definition needs to be changed?

**Comment by dadoonet** [comment]
I said remove not replace.

**Comment by Petros99** [comment]
My apologies, removing the `_doc` field changes the error.

It is now a 404, index not found.
```{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"elasticsearch","index_uuid":"_na_","index":"elasticsearch"}],"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"elasticsearch","index_uuid":"_na_","index":"elasticsearch"},"status":404}```

**Comment by dadoonet** [comment]
Just to be sure. What is the full logs when you run with `--trace`?
But if I'm not mistaken, you need to switch to es 6.8.

**Comment by Petros99** [comment]
The issue no longer occurs after a restart and reset of the Elasticsearch server, and I am no longer able to replicate it. I have been checking everything I can think of but the original issue does not occur. It could not be that I was writing to the same index with different mappings, in the logs above I was not writing to the same index that I had written to using the previous version.
