### ISSUE TITLE
Using cloud id gives "invalid IPv6 Address"

### ISSUE THREAD

**Issue by tdaroly** [dadoonet/fscrawler#994]
**I am currently using the elasticsearch cloud service to crawl and index some local data that i have. 
In the _settings.yaml file i have added the cloud_id according to elasticsearch cloud platform
This is my _settings.yaml file
**

**Job Settings**

```yml
---
name: "kosgo_index_cloud"
fs:
  url: "E:\\tmp"
  update_rate: "15m"
  excludes:
  - "*/~*"
  json_support: false
  filename_as_id: false
  add_filesize: true
  remove_deleted: true
  add_as_inner_object: false
  store_source: false
  index_content: true
  attributes_support: false
  raw_metadata: false
  xml_support: false
  index_folders: true
  lang_detect: false
  continue_on_error: false
  ocr:
    language: "eng"
    enabled: true
    pdf_strategy: "ocr_and_text"
  follow_symlinks: false
elasticsearch:
  # username: "elastic"
  # password: "changeme"
  nodes:
  # With Cloud ID
  - cloud_id: "fscrawler:randomID"
  # With URL
    # - url: "https://url_elastcisearch"


  bulk_size: 1000
  flush_interval: "5s"
  byte_size: "10mb"


```

**Logs**

```
PS C:\Users\Zam\Desktop\fscrawler-es7-2.7-SNAPSHOT> .\bin\fscrawler kosgo_index_cloud
15:06:35,527 INFO  [f.p.e.c.f.c.BootstrapChecks] Memory [Free/Total=Percent]: HEAP [111.5mb/1.7gb=6.23%], RAM [1.6gb/7.8gb=20.9%], Swap [4.7gb/13.3gb=35.79%].
15:06:36,877 WARN  [f.p.e.c.f.c.v.ElasticsearchClientV7] failed to create elasticsearch client, disabling crawler...
15:06:36,877 FATAL [f.p.e.c.f.c.FsCrawlerCli] We can not start Elasticsearch Client. Exiting.
java.io.IOException: c1f0305611d345daa2592c252a0cd504.eastus2.azure.elastic-cloud.com:9243: invalid IPv6 address
        at org.elasticsearch.client.RestClient.extractAndWrapCause(RestClient.java:828) ~[elasticsearch-rest-client-7.8.0.jar:7.8.0]
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:248) ~[elasticsearch-rest-client-7.8.0.jar:7.8.0]
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:235) ~[elasticsearch-rest-client-7.8.0.jar:7.8.0]
        at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1611) ~[elasticsearch-rest-high-level-client-7.8.0.jar:7.8.0]
        at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1596) ~[elasticsearch-rest-high-level-client-7.8.0.jar:7.8.0]
        at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1563) ~[elasticsearch-rest-high-level-client-7.8.0.jar:7.8.0]
        at org.elasticsearch.client.RestHighLevelClient.info(RestHighLevelClient.java:764) ~[elasticsearch-rest-high-level-client-7.8.0.jar:7.8.0]
        at fr.pilato.elasticsearch.crawler.fs.client.v7.ElasticsearchClientV7.getVersion(ElasticsearchClientV7.java:169) ~[fscrawler-elasticsearch-client-v7-2.7-SNAPSHOT.jar:?]
        at fr.pilato.elasticsearch.crawler.fs.client.ElasticsearchClient.checkVersion(ElasticsearchClient.java:181) ~[fscrawler-elasticsearch-client-base-2.7-SNAPSHOT.jar:?]
        at fr.pilato.elasticsearch.crawler.fs.client.v7.ElasticsearchClientV7.start(ElasticsearchClientV7.java:142) ~[fscrawler-elasticsearch-client-v7-2.7-SNAPSHOT.jar:?]
        at fr.pilato.elasticsearch.crawler.fs.cli.FsCrawlerCli.main(FsCrawlerCli.java:257) [fscrawler-cli-2.7-SNAPSHOT.jar:?]
Caused by: java.net.UnknownHostException: c1f0305611d345daa2592c252a0cd504.eastus2.azure.elastic-cloud.com:9243: invalid IPv6 address
        at java.net.InetAddress.getAllByName(InetAddress.java:1170) ~[?:1.8.0_251]
        at java.net.InetAddress.getAllByName(InetAddress.java:1127) ~[?:1.8.0_251]
        at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45) ~[httpclient-4.5.12.jar:4.5.12]
        at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager$InternalAddressResolver.resolveRemoteAddress(PoolingNHttpClientConnectionManager.java:664) ~[httpasyncclient-4.1.4.jar:4.1.4]
        at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager$InternalAddressResolver.resolveRemoteAddress(PoolingNHttpClientConnectionManager.java:635) ~[httpasyncclient-4.1.4.jar:4.1.4]
        at org.apache.http.nio.pool.AbstractNIOConnPool.processPendingRequest(AbstractNIOConnPool.java:474) ~[httpcore-nio-4.4.13.jar:4.4.13]
        at org.apache.http.nio.pool.AbstractNIOConnPool.lease(AbstractNIOConnPool.java:280) ~[httpcore-nio-4.4.13.jar:4.4.13]
        at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.requestConnection(PoolingNHttpClientConnectionManager.java:295) ~[httpasyncclient-4.1.4.jar:4.1.4]
        at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.requestConnection(AbstractClientExchangeHandler.java:377) ~[httpasyncclient-4.1.4.jar:4.1.4]
        at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.start(DefaultClientExchangeHandlerImpl.java:129) ~[httpasyncclient-4.1.4.jar:4.1.4]
        at org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute(InternalHttpAsyncClient.java:141) ~[httpasyncclient-4.1.4.jar:4.1.4]
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:244) ~[elasticsearch-rest-client-7.8.0.jar:7.8.0]
        ... 9 more
15:06:36,885 INFO  [f.p.e.c.f.FsCrawlerImpl] FS crawler [kosgo_index_cloud] stopped
15:06:36,886 INFO  [f.p.e.c.f.FsCrawlerImpl] FS crawler [kosgo_index_cloud] stopped
```

**Expected behavior**

Expected to load the local data into the cloud

**Versions:**
 - OS: [Windows 10]

**Comment by dadoonet** [comment]
Agreed. Found also that bug while working on #991. I have a fix for it. Would you try a build from that branch?

**Comment by tdaroly** [comment]
Sure, can you elaborate further what you mean by a build from that branch ? Should i clone that branch and building on my local machine ?

**Comment by dadoonet** [comment]
Latest build from that branch is available at https://www.dropbox.com/s/07msuwno2gw3noq/fscrawler-es7-2.7-SNAPSHOT.zip?dl=0

**Comment by tdaroly** [comment]
Thanks, using the build from that branch fixed it. The data is now being uploaded to the elasticsearch service.

On a side note: I am really really interested with the technology and the concept of building a file system crawler and id like to get a bit more involved with FSCrawler.
I learnt basic programming with Java in College, but i do have experience with other technology tools that may help. I would love to contribute towards FSCrawler by learning and writing code. Thanks 👍

**Comment by dadoonet** [comment]
I'm going to leave it open until the PR is merged if you don't mind.

**Comment by sagarpatel07** [comment]
I am getting same issue with Java high level client for ES 7.8.1.
below is my code:
```
RestClientBuilder builder = RestClient.builder("cloudid");
RestHighLevelClient restHighLevelClient = new RestHighLevelClient(builder);
boolean status = restHighLevelClient.ping(RequestOptions.DEFAULT);
```
Below is error stack trace:
```
ERROR ESConfig java.io.IOException: xxx.xxx.xxx.elastic-cloud.com:9243: invalid IPv6 address
 java.io.IOException: xxx.xxx.xxx.elastic-cloud.com:9243: invalid IPv6 address
	at org.elasticsearch.client.RestClient.extractAndWrapCause(RestClient.java:828)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:248)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:235)
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1611)
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1596)
	at org.elasticsearch.client.RestHighLevelClient.ping(RestHighLevelClient.java:754)
	at com.xxx.xxx.elasticsearch.ESConfig.connection(ESConfig.java:75)
	at com.xxx.xxx.elasticsearch.ESConfig.createInstance(ESConfig.java:41)
	at com.xxx.xxx.EsConnectionTest.testConnection(EsConnectionTest.java:11)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:542)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: java.net.UnknownHostException: xxx.xxx.xxx.elastic-cloud.com:9243: invalid IPv6 address
	at java.net.InetAddress.getAllByName(Unknown Source)
	at java.net.InetAddress.getAllByName(Unknown Source)
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager$InternalAddressResolver.resolveRemoteAddress(PoolingNHttpClientConnectionManager.java:664)
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager$InternalAddressResolver.resolveRemoteAddress(PoolingNHttpClientConnectionManager.java:635)
	at org.apache.http.nio.pool.AbstractNIOConnPool.processPendingRequest(AbstractNIOConnPool.java:474)
	at org.apache.http.nio.pool.AbstractNIOConnPool.lease(AbstractNIOConnPool.java:280)
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.requestConnection(PoolingNHttpClientConnectionManager.java:295)
	at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.requestConnection(AbstractClientExchangeHandler.java:377)
	at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.start(DefaultClientExchangeHandlerImpl.java:129)
	at org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute(InternalHttpAsyncClient.java:141)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:244)
	... 33 more

```

**Comment by dadoonet** [comment]
@sagarpatel07 this is not related to FSCrawler project. Could you instead open a discussion in discuss.elastic.co?
